import { DAY_STEPS, PHASE_STEPS } from '../shared/constants.js';
import { clamp } from '../shared/utils.js';
import { allDefs, qualityLabel } from '../items/catalog.js';
import { ageStacks } from '../inventory/inventory.js';
import { derivedCharacter } from '../characters/characters.js';

export function phaseInfo(state){const step=state.calendar.stepOfDay||0,idx=Math.floor(step/PHASE_STEPS)%3;return{index:idx,key:['morning','day','night'][idx],name:['朝','昼','夜'][idx],icon:['🌅','☀️','🌙'][idx],remaining:PHASE_STEPS-(step%PHASE_STEPS),stepInPhase:step%PHASE_STEPS,phaseSteps:PHASE_STEPS};}
export function matureProcesses(state){const now=state.calendar.totalSteps||0,m=[];for(const p of state.timedProcesses||[]){if(!p.ready&&p.readyAt<=now){p.ready=true;m.push(p.id);}}return m;}
function fatigueStacksForAwake(awake){return awake>=DAY_STEPS*2?clamp(Math.floor((awake-DAY_STEPS*2)/PHASE_STEPS)+1,1,7):0;}
function groupedExpired(xs){const out={};for(const x of xs){const key=`${x.id}:${x.quality}`;out[key]=(out[key]||0)+x.count;}return out;}
export function advanceTime(state,steps,opts={}){steps=Math.max(0,Math.floor(steps||0));const before=phaseInfo(state),beforeDay=state.calendar.day,oldFatigue=state.condition.fatigueStacks||0,newTotal=(state.calendar.totalSteps||0)+steps,expired=ageStacks(state,newTotal);state.calendar.totalSteps=newTotal;state.calendar.day=Math.floor(newTotal/DAY_STEPS)+1;state.calendar.stepOfDay=newTotal%DAY_STEPS;if(opts.resting){state.condition.awakeSteps=0;state.condition.fatigueStacks=0;}else if(opts.awake!==false){state.condition.awakeSteps=(state.condition.awakeSteps||0)+steps;state.condition.fatigueStacks=fatigueStacksForAwake(state.condition.awakeSteps);}const matured=matureProcesses(state),after=phaseInfo(state);for(const c of Object.values(state.characters||{})){const d=derivedCharacter(state,c);c.hp=Math.min(c.hp,d.maxHp);c.mp=Math.min(c.mp,d.maxMp);}return{before,after,changed:before.key!==after.key||beforeDay!==state.calendar.day,day:state.calendar.day,steps,expired:groupedExpired(expired),matured,fatigueBefore:oldFatigue,fatigueAfter:state.condition.fatigueStacks||0};}
export function timeMessages(t){const out=[];if(t.changed)out.push(`${t.after.icon} ${t.day}日目 ${t.after.name}になった。`);for(const [key,n] of Object.entries(t.expired||{})){const [id,q]=key.split(':');out.push(`${allDefs(id)?.name||id}${qualityLabel(Number(q))}×${n}が傷んだ。`);}if(t.fatigueAfter>t.fatigueBefore)out.push(`徹夜疲労が進行。全能力 -${t.fatigueAfter*10}%。`);if((t.matured||[]).length)out.push(`完成した作業が ${t.matured.length} 件ある。`);return out;}
export function startTimedProcess(state,id,duration,payload={}){const job={id,startedAt:state.calendar.totalSteps,readyAt:state.calendar.totalSteps+Math.max(1,duration),ready:false,payload};state.timedProcesses.push(job);return job;}
export function collectTimedProcess(state,id){const i=state.timedProcesses.findIndex(x=>x.id===id&&x.ready);if(i<0)return null;return state.timedProcesses.splice(i,1)[0];}
