import { alchemyRecipes, consumables, materials } from '../../data/index.js';
import { derived } from '../characters/characters.js';
import { addStack, containerFree, materialCount, storageContainerFor, takeItems } from '../inventory/inventory.js';
import { allDefs, qualityLabel } from '../items/catalog.js';
import { clamp } from '../shared/utils.js';
import { advanceTime, timeMessages } from '../time/clock.js';

export function alchemyRecipeProduct(r){if(r?.consumable){const def=consumables[r.consumable];return{kind:'consumable',id:r.consumable,count:r.count||1,def,name:r.name||def?.name||r.consumable,icon:r.icon||def?.icon||'🧪'};}if(r?.material){const def=materials[r.material];return{kind:'material',id:r.material,count:r.count||1,def,name:r.name||def?.name||r.material,icon:r.icon||def?.icon||'🧴'};}return null;}
function alchemyRecipe(recipeId){return typeof recipeId==='string'?alchemyRecipes.find(x=>x.id===recipeId):recipeId;}
export function alchemyMaxBatch(state,recipeId,cap=99){const r=alchemyRecipe(recipeId),p=alchemyRecipeProduct(r);if(state.run||!r||!p)return 0;let max=Math.max(0,Math.floor(cap));for(const[id,n]of Object.entries(r.cost||{}))max=Math.min(max,Math.floor(materialCount(state,id)/Math.max(1,n)));if(r.gold)max=Math.min(max,Math.floor(state.gold/r.gold));const container=p.kind==='consumable'?'bag':storageContainerFor(p.id),bulk=(p.def?.bulk||1)*(p.count||1);if(bulk>0)max=Math.min(max,Math.floor(containerFree(state,container)/bulk));return Math.max(0,max);}
export function canAlchemy(state,recipeId='a_potion'){return alchemyMaxBatch(state,recipeId,1)>=1;}
function reserveAlchemy(state,r,count=1){if(!r||count<1||alchemyMaxBatch(state,r,count)<count)return null;const taken=[],qualityWeight={sum:0,count:0};for(const[id,n]of Object.entries(r.cost||{})){const got=takeItems(state,id,n*count,{containers:['storage','fresh_storage','bag'],preferLowQuality:true});if(got.count<n*count)return null;for(const x of got.taken){taken.push(x);qualityWeight.sum+=(x.quality||0)*x.count;qualityWeight.count+=x.count;}}state.gold-=(r.gold||0)*count;return{recipeId:r.id,count,taken,materialQuality:qualityWeight.count?qualityWeight.sum/qualityWeight.count:0,gold:(r.gold||0)*count};}
function alchemyOutput(state,r,count,quality,steps){const p=alchemyRecipeProduct(r),container=p.kind==='consumable'?'bag':storageContainerFor(p.id),total=(p.count||1)*count,added=addStack(state,p.id,total,{quality,container}),t=advanceTime(state,steps);return{ok:added===total,product:p,count:added,quality,steps,msg:`${p.name}${qualityLabel(quality)}×${added}を調合した。 ${steps}step経過。 ${timeMessages(t).join(' ')}`};}
export function beginManualAlchemy(state,recipeId){if(state.run)return{ok:false,msg:'調合は村で。'};const r=alchemyRecipe(recipeId);if(!r||alchemyMaxBatch(state,r,1)<1)return{ok:false,msg:'材料・瓶代・保管容量のどれかが足りない。'};const reservation=reserveAlchemy(state,r,1);if(!reservation)return{ok:false,msg:'材料を用意できなかった。'};return{ok:true,recipe:r,reservation,msg:`${r.name}の材料を釜へ用意した。`};}
export function completeManualAlchemy(state,reservation,score=.5,elapsedMs=0){if(!reservation?.recipeId)return{ok:false,msg:'調合情報がない。'};const r=alchemyRecipe(reservation.recipeId);if(!r)return{ok:false,msg:'レシピが見つからない。'};const elapsedSteps=Math.max(r.steps||8,Math.ceil(Math.max(0,elapsedMs)/3000));if(score<.30){const id=r.consumable?'failed_potion':'alchemy_sludge',def=allDefs(id),container=r.consumable?'bag':storageContainerFor(id),added=addStack(state,id,1,{quality:0,container}),t=advanceTime(state,elapsedSteps);return{ok:added===1,failed:true,product:{kind:r.consumable?'consumable':'material',id,def,name:def?.name||id,icon:def?.icon||'🧫'},count:added,quality:null,steps:elapsedSteps,score,materialQuality:reservation.materialQuality,msg:`${def?.name||'失敗作'}×${added}ができた。 ${elapsedSteps}step経過。 ${timeMessages(t).join(' ')}`};}const q=score>=.87?3:score>=.70?2:score>=.50?1:0,out=alchemyOutput(state,r,1,q,elapsedSteps);out.score=score;out.materialQuality=reservation.materialQuality;return out;}
function simpleAlchemyQuality(state){const dex=derived(state).dexterity;return dex>=85?3:dex>=42?2:dex>=18?1:0;}
export function simpleAlchemy(state,recipeId,count=1){if(state.run)return{ok:false,msg:'調合は村で。'};const r=alchemyRecipe(recipeId),max=alchemyMaxBatch(state,r,99);count=Math.max(1,Math.min(Math.floor(count||1),max));if(!r||max<1)return{ok:false,msg:'材料・瓶代・保管容量のどれかが足りない。'};const reservation=reserveAlchemy(state,r,count);if(!reservation)return{ok:false,msg:'材料を用意できなかった。'};const q=simpleAlchemyQuality(state),base=r.steps||8,steps=count===1?base:Math.ceil(base*(1+(count-1)*.45)),out=alchemyOutput(state,r,count,q,steps);out.mode=count===1?'simple':'batch';return out;}
export function brewAlchemy(state,recipeId,performance=.5){const start=beginManualAlchemy(state,recipeId);if(!start.ok)return start;const q=clamp(Math.floor(clamp(performance,0,1)*4),0,3);return alchemyOutput(state,start.recipe,1,q,start.recipe.steps||8);}
export function brewPotion(state,quality=.5){return brewAlchemy(state,'a_potion',quality);}
