import assert from 'node:assert/strict';
import { defaultState, startExpedition } from '../src/core/game.js';
import { AppUI } from '../src/ui/app.js';
const root={innerHTML:'',querySelectorAll(){return[]},querySelector(){return null},appendChild(){}};const s=defaultState();const ui=new AppUI(root,s,async()=>{});
ui.render();assert.match(root.innerHTML,/周辺探索へ出発/);
ui.tab='items';ui.itemScene='menu';ui.render();assert.match(root.innerHTML,/倉庫/);ui.itemScene='bag';ui.render();assert.match(root.innerHTML,/品質0/);ui.itemScene='warehouse';ui.render();assert.match(root.innerHTML,/3倍長持ち|劣化速度1\/3/);
ui.tab='production';ui.productionMode='forge';ui.render();assert.match(root.innerHTML,/60step/);
ui.tab='equipment';ui.render();assert.match(root.innerHTML,/からだ上/);
startExpedition(s);s.run.location='west_road';ui.render();assert.match(root.innerHTML,/足踏み/);assert.match(root.innerHTML,/map-player-marker/);ui.runBagOpen=true;ui.render();assert.match(root.innerHTML,/バックパック/);ui.runBagOpen=false;
s.battle={enemyId:'slime',enemyHp:18,enemyMaxHp:18,enemyAtk:6,enemyDef:1,expReward:8,over:false,won:false,guarding:false,turn:1,reason:'test',log:['スライムが あらわれた！']};ui.battleVisible=true;ui.render();assert.match(root.innerHTML,/battle-button-grid/);ui.battleMenu='items';ui.render();assert.match(root.innerHTML,/どうぐ/);
console.log('ui smoke ok');
