import assert from 'node:assert/strict';
import {defaultState,startExpedition} from '../src/core/game.js';
import {AppUI} from '../src/ui/app.js';
const root={innerHTML:'',querySelectorAll(){return[]},querySelector(){return null},appendChild(){}};const s=defaultState();const ui=new AppUI(root,s,async()=>{});
ui.render();assert.match(root.innerHTML,/80G/);assert.match(root.innerHTML,/きようさ/);
ui.tab='items';ui.itemScene='warehouse';ui.render();assert.match(root.innerHTML,/換金品を全て売る/);
ui.tab='production';ui.render();assert.match(root.innerHTML,/Rank 2|R2/);
ui.tab='equipment';ui.render();assert.match(root.innerHTML,/出来栄え/);
startExpedition(s);ui.render();assert.match(root.innerHTML,/村へ戻る/);s.run.location='west_road';ui.render();assert.match(root.innerHTML,/足踏み/);assert.match(root.innerHTML,/map-player-marker/);
s.battle={enemyId:'slime',enemyHp:18,enemyMaxHp:18,enemyAtk:6,enemyDef:1,enemyAgi:5,expReward:8,over:false,won:false,escaped:false,guarding:false,turn:1,escapeAttempts:0,reason:'test',log:['スライムが あらわれた！']};ui.battleVisible=true;ui.render();assert.match(root.innerHTML,/にげる/);assert.match(root.innerHTML,/33%/);
console.log('ui smoke ok');
