import assert from 'node:assert/strict';
import {defaultState,startExpedition} from '../src/core/game.js';
import {AppUI} from '../src/ui/app.js';
const root={innerHTML:'',querySelectorAll(){return[]},querySelector(){return null},appendChild(){}};const s=defaultState();const ui=new AppUI(root,s,async()=>{});
ui.render();assert.match(root.innerHTML,/80G/);assert.match(root.innerHTML,/きようさ/);
ui.tab='items';ui.itemScene='warehouse';s.itemStacks.push({stackId:'wh_gel',id:'slime_gel',count:3,quality:1,container:'storage',remainingLife:null,lastAgedStep:s.calendar.totalSteps},{stackId:'wh_herb',id:'fresh_herb',count:2,quality:2,container:'fresh_storage',remainingLife:300,lastAgedStep:s.calendar.totalSteps});ui.render();assert.match(root.innerHTML,/換金品を全て売る/);assert.match(root.innerHTML,/スライムゼリー/);assert.match(root.innerHTML,/☆1/);ui.warehouseMode='fresh';ui.render();assert.match(root.innerHTML,/生鮮倉庫/);assert.match(root.innerHTML,/薬草/);assert.match(root.innerHTML,/☆2/);ui.warehouseMode='normal';
ui.tab='production';ui.productionMode='menu';ui.render();assert.match(root.innerHTML,/鍛冶/);assert.match(root.innerHTML,/調合/);ui.productionMode='forge';ui.forgeCategory='weapon';ui.render();assert.match(root.innerHTML,/R2|Rank 2|武器/);
ui.tab='equipment';ui.render();assert.match(root.innerHTML,/出来栄え/);
startExpedition(s);ui.render();assert.match(root.innerHTML,/村へ戻る/);s.run.location='west_road';ui.render();assert.match(root.innerHTML,/足踏み/);assert.match(root.innerHTML,/map-player-marker/);
s.battle={enemyId:'slime',enemyHp:18,enemyMaxHp:18,enemyAtk:6,enemyDef:1,enemyAgi:5,expReward:8,over:false,won:false,escaped:false,guarding:false,turn:1,escapeAttempts:0,reason:'test',log:['スライムが あらわれた！']};ui.battleVisible=true;ui.render();assert.match(root.innerHTML,/にげる/);assert.match(root.innerHTML,/33%/);
console.log('ui smoke ok');
