import {
  EQUIPMENT_SLOTS, adjacentNodes, backpackCapacity, backpacks, brewPotion, buyConsumable, camp, campStatus,
  canAlchemy, canCraft, collectForgeOrder, command, consumables, currentLocation, defeatReturn, derived, enemies,
  equip, expToNext, finishBattle, forgeOrders, harvestResult, items, materialCount, materials, orderCraft,
  perishableCount, perishableSummary, phaseInfo, recipes, resourceStatus, restAtTown, sellAll, sellMaterial,
  selfCraft, sleepDuration, startExpedition, travelTo, upgradeBackpack, useFieldItem, useRura, usedCapacity,
  worldEdges, worldNodes
} from '../core/game.js';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(a,b)=>Math.max(0,Math.min(100,b?100*a/b:0));
const fmtCost=cost=>Object.entries(cost).map(([id,n])=>`${materials[id].icon}${materials[id].name} ${n}`).join(' / ');
const freshnessLabel=n=>`あと${n}step${n<=15?' ⚠️':''}`;

export class AppUI{
  constructor(root,state,onChange){
    this.root=root;this.state=state;this.onChange=onChange;
    this.tab='home';this.itemScene='menu';this.productionMode='forge';this.equipSlot='weapon';
    this.modal=null;this.minigame=null;this.runBagOpen=false;this.installPrompt=null;
    this.toastTimer=null;this.fishTimer=null;this.fishMissTimer=null;this.battleVisible=false;this.battleTransitionTimer=null;
    this.battleFx=null;this.commandLocked=false;this.fxTimer=null;
  }
  setInstallPrompt(e){this.installPrompt=e;this.render();}
  async mutate(fn){const r=fn?.();await this.onChange();this.render();return r;}
  toast(msg){if(!msg)return;const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),2600);if(this.state.settings.vibrate&&navigator.vibrate)navigator.vibrate(15);}

  render(){
    if(this.state.battle){if(!this.battleVisible){this.battleVisible=true;return this.renderBattleTransition();}return this.renderBattle();}
    this.battleVisible=false;this.commandLocked=false;this.battleFx=null;clearTimeout(this.battleTransitionTimer);clearTimeout(this.fxTimer);
    if(this.state.run)return this.renderRun();
    const content={home:()=>this.home(),items:()=>this.itemsTab(),production:()=>this.production(),equipment:()=>this.equipment(),settings:()=>this.settings()}[this.tab]?.()||this.home();
    this.root.innerHTML=`<div class="shell">${this.topbar()}<main>${content}</main>${this.nav()}</div>${this.overlayHtml()}`;this.bindCommon();
  }

  timeText(){const p=phaseInfo(this.state);return `${p.icon} ${this.state.calendar.day}日目 ${p.name} ${p.stepInPhase}/30`;}
  topbar(){return `<header class="topbar"><div class="brand">GRINDQUEST<small>field expedition RPG</small></div><div class="time-pill">${this.timeText()}</div></header>`;}
  nav(){const tabs=[['home','🏘️','村'],['items','🎒','アイテム'],['production','⚒️','生産'],['equipment','🛡️','装備'],['settings','⚙️','設定']];return `<nav class="bottom-nav five">${tabs.map(([id,ic,l])=>`<button class="nav-btn ${this.tab===id?'active':''}" data-tab="${id}"><span>${ic}</span>${l}</button>`).join('')}</nav>`;}

  fatigueChip(){const stacks=this.state.condition?.fatigueStacks||0,awake=this.state.condition?.awakeSteps||0;if(stacks)return `<span class="fatigue-chip danger-chip">🥱 -${stacks*10}%</span>`;if(awake>=120)return `<span class="fatigue-chip warn-chip">🥱 ${awake}step</span>`;return `<span class="fatigue-chip">覚醒 ${awake}</span>`;}
  playerCard(){const p=this.state.player,d=derived(this.state),need=expToNext(p.level),phase=phaseInfo(this.state);return `<section class="hero-card">
    <div class="row"><div class="avatar">🧑‍⚔️</div><div class="grow"><h1>${esc(p.name)} <span class="tiny muted">Lv.${p.level}</span></h1><div class="tiny muted">${items[p.equipment.weapon]?.name||'なし'} / ${items[p.equipment.body]?.name||'なし'}</div></div><b>${this.state.gold}G</b></div>
    <div class="section"><div class="tiny row between"><span>HP ${p.hp}/${d.maxHp}</span><span>MP ${p.mp}/${d.maxMp}</span></div><div class="bar"><i style="width:${pct(p.hp,d.maxHp)}%"></i></div><div class="bar mp"><i style="width:${pct(p.mp,d.maxMp)}%"></i></div><div class="tiny muted top-gap">EXP ${p.exp}/${need}</div><div class="bar exp"><i style="width:${pct(p.exp,need)}%"></i></div></div>
    <div class="stats"><div class="stat"><b>${d.atk}</b><span>こうげき</span></div><div class="stat"><b>${d.def}</b><span>しゅび</span></div><div class="stat"><b>${backpackCapacity(this.state)}</b><span>バッグ</span></div></div>
    <div class="calendar-strip"><div><b>${phase.icon} ${this.state.calendar.day}日目 ${phase.name}</b><span>あと${phase.remaining}step</span></div>${this.fatigueChip()}</div>
  </section>`;}

  home(){const sleep=sleepDuration(this.state);return `${this.playerCard()}
    <section class="section"><div class="section-title"><h2>村から出る</h2><span class="tiny muted">歩いて、拾って、帰る</span></div><div class="card"><p class="tiny muted">EXPは戦闘・探索・採集のその場で獲得。持ち帰る必要があるのは素材と生鮮品。</p><button class="btn primary big" data-action="start-expedition">🗺️ 周辺探索へ出発</button></div></section>
    <section class="section"><div class="section-title"><h2>家</h2></div><div class="card"><div class="row between"><div class="grow"><b>しっかり眠る</b><div class="tiny muted">今なら${sleep}step。HP/MP全回復、徹夜疲労解除。</div></div><button class="btn" data-action="town-rest">🛏️ 寝る</button></div></div></section>
    <section class="section"><div class="section-title"><h2>最近の記録</h2></div><div class="card">${this.state.log.slice(0,5).map(x=>`<div class="line-item"><span class="tiny">${esc(x)}</span></div>`).join('')}</div></section>`;}

  nextPack(){const ids=['cheap','canvas','explorer'],i=ids.indexOf(this.state.backpack);return i>=0?backpacks[ids[i+1]]:null;}
  freshMap(container='storage'){return Object.fromEntries(perishableSummary(this.state,container).map(x=>[x.id,x]));}

  itemsTab(){if(this.itemScene==='shop')return this.shop();if(this.itemScene==='warehouse')return this.warehouse();return `<div class="scene-header"><div><h2>アイテム</h2><div class="tiny muted">村の施設へ入る</div></div><span class="pill">${this.state.gold}G</span></div><div class="facility-grid">
    <button class="facility-card" data-scene="shop"><span>🏪</span><b>道具屋</b><small>保存薬・キャンプ道具・バッグ</small></button>
    <button class="facility-card" data-scene="warehouse"><span>📦</span><b>倉庫・売却</b><small>素材、生鮮品、持ち帰った品</small></button>
  </div>`;}
  sceneBack(){return `<button class="icon-btn" data-scene="menu">←</button>`;}
  shop(){const nextPack=this.nextPack();return `<div class="scene-header"><div class="row">${this.sceneBack()}<div><h2>道具屋</h2><div class="tiny muted">「いらっしゃい！」</div></div></div><span class="pill">${this.state.gold}G</span></div><div class="shop-counter">🧑‍💼<div><b>旅支度なら任せな。</b><small>重さも忘れずにな。</small></div></div><div class="cards">${Object.values(consumables).map(c=>`<div class="card shop-row"><div class="item-icon">${c.icon}</div><div class="grow"><b>${c.name}</b><div class="tiny muted">${c.desc}</div><div class="tiny">所持 ${this.state.consumables[c.id]||0} / 容量${c.bulk}</div></div><button class="btn small" data-action="buy" data-id="${c.id}" ${(c.max&&(this.state.consumables[c.id]||0)>=c.max)?'disabled':''}>${c.price}G</button></div>`).join('')}
    <div class="card shop-row"><div class="item-icon">${backpacks[this.state.backpack].icon}</div><div class="grow"><b>${backpacks[this.state.backpack].name}</b><div class="tiny muted">現在容量 ${backpackCapacity(this.state)}</div>${nextPack?`<div class="tiny">次: ${nextPack.name} / ${nextPack.capacity}</div>`:'<div class="tiny">最大サイズ</div>'}</div>${nextPack?`<button class="btn small" data-action="upgrade-pack">${nextPack.price}G</button>`:'<span class="tag">MAX</span>'}</div></div>`;}
  warehouse(){const fresh=this.freshMap('storage'),mats=Object.entries(materials).filter(([id])=>materialCount(this.state,id)>0);return `<div class="scene-header"><div class="row">${this.sceneBack()}<div><h2>倉庫・売却</h2><div class="tiny muted">素材がお金になる</div></div></div><span class="pill">${this.state.gold}G</span></div><div class="card"><div class="row between"><span class="tiny muted">生鮮品は倉庫でも寿命が進む。</span><button class="btn small" data-action="sell-all" ${mats.length?'':'disabled'}>全部売る</button></div></div><section class="section"><div class="cards">${mats.length?mats.map(([id,m])=>{const f=fresh[id],n=materialCount(this.state,id);return `<div class="card shop-row ${f&&f.remaining<=15?'fresh-critical':''}"><div class="item-icon">${m.icon}</div><div class="grow"><b>${m.name} ×${n}</b><div class="tiny muted">売値 ${m.value}G / 容量${m.bulk}</div>${f?`<div class="freshness ${f.remaining<=15?'critical':''}">⏳ ${freshnessLabel(f.remaining)}</div>`:''}</div><button class="btn small" data-action="sell" data-id="${id}">1個売る</button></div>`}).join(''):'<div class="card empty">倉庫は空っぽ。</div>'}</div></section>`;}

  production(){return `<div class="scene-header"><div><h2>生産</h2><div class="tiny muted">時間を使って装備と薬を作る</div></div><span class="pill">${this.state.gold}G</span></div><div class="segmented"><button class="${this.productionMode==='forge'?'active':''}" data-production="forge">⚒️ 鍛冶</button><button class="${this.productionMode==='alchemy'?'active':''}" data-production="alchemy">🧪 調合</button></div>${this.productionMode==='forge'?this.forge():this.alchemy()}`;}
  forge(){const orders=forgeOrders(this.state);return `<section class="section"><div class="section-title"><h3>依頼中</h3><span class="tiny muted">鍛冶屋は並行して仕事する</span></div>${orders.length?`<div class="cards">${orders.map(o=>{const it=items[o.payload.item],remain=Math.max(0,o.readyAt-this.state.calendar.totalSteps);return `<div class="card shop-row"><div class="item-icon">${it.icon}</div><div class="grow"><b>${it.name}</b><div class="tiny ${o.ready?'good-text':'muted'}">${o.ready?'完成済み':`完成まで ${remain}step`}</div></div>${o.ready?`<button class="btn good small" data-action="collect-forge" data-id="${o.id}">受取</button>`:'<span class="tag">作業中</span>'}</div>`}).join('')}</div>`:'<div class="card empty">依頼中の装備はない。</div>'}</section>
    <section class="section"><div class="section-title"><h3>レシピ</h3><span class="tiny muted">依頼60step / 自作12step</span></div><div class="cards">${recipes.map(r=>{const it=items[r.item],can=canCraft(this.state,r);return `<div class="card recipe-card"><div class="row"><div class="item-icon">${it.icon}</div><div class="grow"><h3>${it.name}</h3><div class="tiny muted">${it.desc}</div><div class="tiny top-gap">${fmtCost(r.cost)}</div></div></div><div class="dual-actions"><button class="btn ${can?'':'disabled-look'}" data-action="order-craft" data-id="${r.id}" ${can?'':'disabled'}>👨‍🏭 頼む<small>60step後</small></button><button class="btn primary ${can?'':'disabled-look'}" data-action="self-craft" data-id="${r.id}" ${can?'':'disabled'}>🔨 自分で打つ<small>ミニゲーム</small></button></div></div>`}).join('')}</div></section>`;}
  alchemy(){const ok=canAlchemy(this.state);return `<section class="section"><div class="alchemy-bench"><div class="alchemy-bottle">🧪</div><div><h3>ポーション</h3><div class="tiny muted">薬草と森キノコを煮出し、瓶に詰める。</div></div></div><div class="card"><div class="line-item"><span>🌿 薬草</span><b>1</b></div><div class="line-item"><span>🍄 森キノコ</span><b>1</b></div><div class="line-item"><span>🫙 瓶代</span><b>20G</b></div><div class="line-item"><span>⏱️ 所要時間</span><b>8step</b></div><button class="btn primary big" data-action="brew" ${ok?'':'disabled'}>ぐつぐつ調合する</button><p class="tiny muted top-gap">※品質を決める調合ミニゲームは次段階で追加予定。</p></div></section>`;}

  equipment(){const p=this.state.player,d=derived(this.state),slotName=Object.fromEntries(EQUIPMENT_SLOTS)[this.equipSlot],available=Object.entries(this.state.ownedItems).filter(([id,n])=>n>0&&items[id]?.slot===this.equipSlot);return `<div class="scene-header"><div><h2>そうび</h2><div class="tiny muted">DQ9風のスロット選択</div></div><span class="pill">Lv.${p.level}</span></div><div class="dq9-equip">
    <section class="equip-character"><div class="equip-avatar">🧑‍⚔️</div><b>${esc(p.name)}</b><div class="equip-statline"><span>こうげき力</span><b>${d.atk}</b></div><div class="equip-statline"><span>しゅび力</span><b>${d.def}</b></div><div class="equip-statline"><span>最大HP</span><b>${d.maxHp}</b></div><div class="equip-statline"><span>最大MP</span><b>${d.maxMp}</b></div></section>
    <section class="equip-slots">${EQUIPMENT_SLOTS.map(([slot,label])=>{const id=p.equipment[slot],it=items[id];return `<button class="equip-slot ${this.equipSlot===slot?'selected':''}" data-equip-slot="${slot}"><span>${label}</span><b>${it?`${it.icon} ${it.name}`:'－'}</b><i>›</i></button>`}).join('')}</section>
  </div><section class="section"><div class="section-title"><h3>${slotName}</h3><span class="tiny muted">持っている装備</span></div><div class="cards">${available.length?available.map(([id,n])=>{const it=items[id],eq=p.equipment[this.equipSlot]===id;return `<div class="card equip-choice"><div class="item-icon">${it.icon}</div><div class="grow"><b>${it.name}${n>1?` ×${n}`:''}</b><div class="tiny muted">攻+${it.atk||0} 守+${it.def||0} HP+${it.hp||0} MP+${it.mp||0}</div><div class="tiny muted">${it.desc}</div></div>${eq?'<span class="tag">E</span>':`<button class="btn small" data-action="equip" data-id="${id}">そうび</button>`}</div>`}).join(''):'<div class="card empty">この部位の装備はまだ持っていない。</div>'}</div></section>`;}

  settings(){return `<div class="section-title"><h2>設定・セーブ</h2></div><div class="cards">${this.installPrompt?`<div class="card"><h3>📲 ホーム画面に追加</h3><button class="btn primary top-gap" data-action="install">インストール</button></div>`:''}<div class="card"><h3>放置探索</h3><p class="tiny muted">v0.5でも封印中。コードだけ保持。</p></div><div class="card"><h3>時間管理</h3><p class="tiny muted">移動・戦闘・アイテム使用・採集・睡眠・鍛冶・調合が同じstep時計を使う。</p></div><div class="card"><h3>セーブデータ</h3><div class="cards top-gap"><button class="btn" data-action="export">セーブを書き出す</button><label class="btn center">セーブを読み込む<input type="file" id="import-file" accept="application/json" hidden></label><button class="btn danger" data-action="reset">最初からやり直す</button></div></div></div>`;}

  compactRunHud(){const p=this.state.player,d=derived(this.state),used=usedCapacity(this.state),cap=backpackCapacity(this.state),need=expToNext(p.level);return `<section class="run-hud-compact"><div class="run-hud-top"><b>Lv.${p.level}</b><div class="mini-gauge hp"><span>HP ${p.hp}</span><i><em style="width:${pct(p.hp,d.maxHp)}%"></em></i></div><div class="mini-gauge mp"><span>MP ${p.mp}</span><i><em style="width:${pct(p.mp,d.maxMp)}%"></em></i></div><span class="run-exp">EXP ${p.exp}/${need}</span><span class="run-pack">🎒${used}/${cap}</span><button class="bag-open-btn" data-action="open-run-bag">🎒 開く</button></div>${(this.state.condition?.fatigueStacks||0)?`<div class="run-fatigue">🥱 全能力 -${this.state.condition.fatigueStacks*10}%</div>`:''}</section>`;}

  renderRun(){const run=this.state.run,loc=currentLocation(this.state),adj=new Set(adjacentNodes(loc.id).map(x=>x.id)),resource=resourceStatus(this.state);
    const edges=worldEdges.map(e=>{const a=worldNodes[e.a],b=worldNodes[e.b];return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="field-edge"/>`;}).join('');
    const nodes=Object.values(worldNodes).map(n=>{const can=adj.has(n.id),current=n.id===loc.id,visited=run.visited.includes(n.id),camp=n.campSafety==='safe'?' ⛺':n.campSafety==='semi'?' ⚠️':'';return `<button class="field-node ${can?'reachable':''} ${current?'current-location':''} ${visited?'visited':''}" style="left:${n.x}%;top:${n.y}%" data-action="travel" data-id="${n.id}" ${can?'':'disabled'}>${current?'<i class="map-player-marker">🧑‍⚔️</i>':''}<span>${n.icon}</span><small>${n.name}${camp}</small></button>`;}).join('');
    this.root.innerHTML=`<div class="shell run-shell"><header class="run-topbar"><div><b>${loc.icon} ${loc.name}</b><small>${loc.desc}</small></div><span>${this.timeText()}</span></header><main>${this.compactRunHud()}
      ${run.lastEvent?`<section class="event-strip"><b>出来事</b><span>${esc(run.lastEvent)}</span></section>`:''}
      <section class="section"><div class="section-title"><h2>周辺地図</h2><span class="tiny muted">現在地 🧑‍⚔️</span></div><div class="map-stage"><div class="map-viewport" id="map-viewport"><div class="field-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${edges}</svg>${nodes}</div></div>${this.mapAction(resource)}</div></section>
      <section class="location-mini"><b>${loc.icon} ${loc.name}</b><span>${loc.desc}</span></section>
    </main></div>${this.overlayHtml()}${this.runBagOpen?this.runBagHtml():''}`;this.bindCommon();setTimeout(()=>this.centerMap(),0);
  }
  mapAction(rs){if(!rs)return'';if(rs.used)return `<div class="map-action-overlay used">✓ 採集済み</div>`;if(rs.kind==='herb')return `<button class="map-action-overlay resource" data-action="gather-herb">🌿 採取</button>`;const labels={mining:'⛏️ 採掘',fishing:'🎣 釣る',woodcut:'🪓 伐採'};return `<button class="map-action-overlay resource" data-action="start-mini" data-kind="${rs.kind}">${labels[rs.kind]}</button>`;}
  centerMap(){const vp=this.root.querySelector('#map-viewport'),node=this.root.querySelector('.current-location');if(!vp||!node)return;vp.scrollTo({left:Math.max(0,node.offsetLeft-vp.clientWidth/2),top:Math.max(0,node.offsetTop-vp.clientHeight/2),behavior:'instant'});}

  runBagHtml(){const p=this.state.player,d=derived(this.state),fresh=perishableSummary(this.state,'bag'),cargo=Object.entries(this.state.run?.cargo||{}).filter(([,n])=>n>0),cs=campStatus(this.state);return `<div class="run-bag-backdrop"><section class="run-bag-panel"><header><div><h2>🎒 バックパック</h2><small>${usedCapacity(this.state)}/${backpackCapacity(this.state)}　${currentLocation(this.state).name}</small></div><button class="icon-btn" data-action="close-run-bag">×</button></header><div class="bag-health"><div><span>HP ${p.hp}/${d.maxHp}</span><div class="bar"><i style="width:${pct(p.hp,d.maxHp)}%"></i></div></div><div><span>MP ${p.mp}/${d.maxMp}</span><div class="bar mp"><i style="width:${pct(p.mp,d.maxMp)}%"></i></div></div></div>
    <div class="bag-section"><h3>使う</h3><div class="field-item-grid"><button class="field-item" data-run-item="fresh_herb" ${perishableCount(this.state,'fresh_herb','bag')?'':'disabled'}><span>🌿</span><b>薬草 ×${perishableCount(this.state,'fresh_herb','bag')}</b><small>HP+24 / 2step</small></button><button class="field-item" data-run-item="potion" ${(this.state.consumables.potion||0)?'':'disabled'}><span>🧪</span><b>ポーション ×${this.state.consumables.potion||0}</b><small>HP+45 / 2step</small></button><button class="field-item magic-item" data-action="rura" ${(this.state.consumables.rura_potion||0)?'':'disabled'}><span>🌀</span><b>ルーラ ×${this.state.consumables.rura_potion||0}</b><small>村へ直行 / 1step</small></button>${cs?.allowed?`<button class="field-item camp-item" data-action="camp" ${cs.hasSet?'':'disabled'}><span>⛺</span><b>キャンプ</b><small>${cs.safety==='safe'?'安全':'襲撃の可能性'} / 約70%回復</small></button>`:''}</div></div>
    <div class="bag-section"><h3>生鮮品</h3>${fresh.length?fresh.map(x=>`<div class="bag-row"><span>${materials[x.id].icon} ${materials[x.id].name}</span><b>×${x.count}</b><small>${freshnessLabel(x.remaining)}</small></div>`).join(''):'<div class="empty">なし</div>'}</div>
    <div class="bag-section"><h3>素材</h3>${cargo.length?cargo.map(([id,n])=>`<div class="bag-row"><span>${materials[id].icon} ${materials[id].name}</span><b>×${n}</b><small>容量${materials[id].bulk*n}</small></div>`).join(''):'<div class="empty">なし</div>'}</div>
  </section></div>`;}

  renderBattleTransition(){clearTimeout(this.battleTransitionTimer);this.root.querySelector('.encounter-transition-overlay')?.remove();const overlay=document.createElement('div');overlay.className='encounter-transition-overlay';overlay.innerHTML='<div class="encounter-flash">魔物の気配……</div><div class="encounter-blackout"></div>';this.root.appendChild(overlay);this.battleTransitionTimer=setTimeout(()=>{if(this.state.battle)this.renderBattle();},620);}
  renderBattle(){const b=this.state.battle,e=enemies[b.enemyId],p=this.state.player,d=derived(this.state),phase=phaseInfo(this.state),herbs=perishableCount(this.state,'fresh_herb','bag'),fx=this.battleFx||{};this.root.innerHTML=`<div class="battle-shell retro-battle">
    <div class="battle-topline"><span>${currentLocation(this.state).name}</span><span>${phase.icon} ${this.state.calendar.day}日目 ${phase.name}　TURN ${b.turn}</span></div>
    <main class="battle-main"><section class="battle-scene ${fx.stage==='player'?'player-strike':''} ${fx.action==='skill'?'skill-strike':''}"><div class="enemy-name-window rpg-window"><b>${e.name}</b><span>HP ${b.enemyHp}/${b.enemyMaxHp}</span><div class="retro-hp"><i style="width:${pct(b.enemyHp,b.enemyMaxHp)}%"></i></div></div><div class="enemy-sprite retro-enemy ${fx.stage==='player'&&fx.enemyDamage?'enemy-hit':''}">${e.icon}</div>${fx.stage==='player'&&fx.enemyDamage?`<div class="damage-pop enemy-pop">-${fx.enemyDamage}</div>`:''}<div class="battle-ground"></div></section>
      <section class="battle-status rpg-window ${fx.stage==='enemy'&&fx.playerDamage?'player-hit':''}"><div class="status-name"><b>${p.name}</b><small>Lv.${p.level}</small></div><div class="player-vitals"><div class="vital-line"><span>HP ${p.hp}/${d.maxHp}</span><div class="battle-player-bar hp"><i style="width:${pct(p.hp,d.maxHp)}%"></i></div></div><div class="vital-line"><span>MP ${p.mp}/${d.maxMp}</span><div class="battle-player-bar mp"><i style="width:${pct(p.mp,d.maxMp)}%"></i></div></div></div><div class="battle-turn"><span>STEP</span><b>${this.state.calendar.totalSteps}</b></div>${fx.stage==='enemy'&&fx.playerDamage?`<div class="damage-pop player-pop">-${fx.playerDamage}</div>`:''}</section>
      <section class="battle-message rpg-window">${b.log.slice(-4).map((x,i)=>`<div class="${i===b.log.slice(-4).length-1?'latest':''}">${esc(x)}</div>`).join('')}</section>
      ${b.over?this.battleEnd():`<section class="battle-command-box rpg-window"><div class="command-title">コマンド <small>1ターン = 1step</small></div><div class="battle-button-grid"><button class="battle-btn attack" data-cmd="attack" ${this.commandLocked?'disabled':''}><span>⚔️</span><b>こうげき</b></button><button class="battle-btn skill" data-cmd="skill" ${this.commandLocked?'disabled':''}><span>🔥</span><b>とくぎ</b><small>MP 3</small></button><button class="battle-btn heal" data-cmd="heal" ${this.commandLocked?'disabled':''}><span>✨</span><b>じゅもん</b><small>MP 4</small></button><button class="battle-btn defend" data-cmd="defend" ${this.commandLocked?'disabled':''}><span>🛡️</span><b>ぼうぎょ</b></button><button class="battle-btn item" data-cmd="herb" ${this.commandLocked?'disabled':''}><span>🌿</span><b>やくそう</b><small>×${herbs}</small></button><button class="battle-btn item" data-cmd="potion" ${this.commandLocked?'disabled':''}><span>🧪</span><b>ポーション</b><small>×${this.state.consumables.potion||0}</small></button></div></section>`}
    </main></div>${this.overlayHtml()}`;this.bindCommon();}
  battleEnd(){return this.state.battle.won?`<section class="battle-command-box rpg-window"><div class="command-title">戦闘終了</div><button class="battle-result-btn win" data-action="finish-battle">勝利！ 周囲へ戻る</button></section>`:`<section class="battle-command-box rpg-window danger-window"><div class="command-title">ちからつきた……</div><button class="battle-result-btn lose" data-action="defeat-return">村へ運ばれる</button></section>`;}
  async performBattleCommand(type){if(this.commandLocked||!this.state.battle||this.state.battle.over)return;this.commandLocked=true;const r=command(this.state,type);if(!r.ok){this.commandLocked=false;await this.onChange();this.render();return;}await this.onChange();this.battleFx={stage:'player',...r};this.render();clearTimeout(this.fxTimer);this.fxTimer=setTimeout(()=>{if(!this.state.battle)return;if(r.playerDamage){this.battleFx={stage:'enemy',...r};this.render();this.fxTimer=setTimeout(()=>{this.battleFx=null;this.commandLocked=false;this.render();},300);}else{this.battleFx=null;this.commandLocked=false;this.render();}},320);}

  startMini(kind,extra={}){clearTimeout(this.fishTimer);clearTimeout(this.fishMissTimer);if(kind==='mining'){this.minigame={kind,start:performance.now()};this.render();return;}if(kind==='fishing'){this.minigame={kind,stage:'waiting'};this.render();this.fishTimer=setTimeout(()=>{if(this.minigame?.kind==='fishing'&&this.minigame.stage==='waiting'){this.minigame.stage='bite';this.render();this.fishMissTimer=setTimeout(()=>{if(this.minigame?.kind==='fishing'&&this.minigame.stage==='bite')this.resolveMini(.05,'魚に逃げられた。');},850);}},800+Math.random()*1700);return;}if(kind==='woodcut'){this.minigame={kind,next:'left',hits:0,errors:0,start:performance.now()};this.render();return;}if(kind==='forge'){this.minigame={kind,recipeId:extra.recipeId,hits:0,total:0,start:performance.now()};this.render();}}
  miningHit(){if(this.minigame?.kind!=='mining')return;const t=(performance.now()-this.minigame.start)%1600,pos=t/1600,quality=1-Math.min(1,Math.abs(pos-.5)*2);this.resolveMini(quality);}
  fishingTap(){if(this.minigame?.kind!=='fishing')return;if(this.minigame.stage==='bite')this.resolveMini(.9);else this.resolveMini(.08,'早合わせで魚が逃げた。');}
  woodTap(side){const m=this.minigame;if(m?.kind!=='woodcut')return;if(side===m.next){m.hits++;m.next=side==='left'?'right':'left';}else m.errors++;if(m.hits>=8){const sec=(performance.now()-m.start)/1000,quality=Math.max(.15,1-(Math.max(0,sec-3)*.08)-m.errors*.14);this.resolveMini(quality);return;}this.render();}
  forgeHit(){const m=this.minigame;if(m?.kind!=='forge')return;const t=(performance.now()-m.start)%1400,pos=t/1400,q=1-Math.min(1,Math.abs(pos-.5)*2);m.total+=q;m.hits++;if(m.hits>=3){const avg=m.total/3,recipeId=m.recipeId;this.minigame=null;this.mutate(()=>{const r=selfCraft(this.state,recipeId,avg);this.toast(r.msg);});return;}m.start=performance.now();this.render();}
  async resolveMini(quality,custom){clearTimeout(this.fishTimer);clearTimeout(this.fishMissTimer);const r=harvestResult(this.state,quality);this.minigame=null;await this.onChange();this.render();this.toast(custom||r.msg);}

  miniHtml(){const m=this.minigame;if(!m)return'';if(m.kind==='mining')return `<div class="modal-backdrop"><div class="modal"><h2>⛏️ 採掘</h2><p class="tiny muted">中央を狙って振り下ろす。</p><div class="timing-bar"><div class="sweet"></div><div class="moving-marker"></div></div><button class="btn primary big" data-action="mine-hit">振り下ろす！</button></div></div>`;if(m.kind==='fishing')return `<div class="modal-backdrop"><div class="modal"><h2>🎣 釣り</h2><div class="fish-water">${m.stage==='bite'?'<div class="bite">！！！</div>':'<div class="float">●</div>'}</div><p class="tiny muted">浮きが沈んだ瞬間に合わせる。</p><button class="btn ${m.stage==='bite'?'good':'primary'} big" data-action="fish-tap">${m.stage==='bite'?'今だ！':'合わせる'}</button></div></div>`;if(m.kind==='woodcut')return `<div class="modal-backdrop"><div class="modal"><h2>🪓 木こり</h2><p class="tiny muted">左右交互に8回。</p><div class="wood-progress">${'▰'.repeat(m.hits)}${'▱'.repeat(8-m.hits)}</div><div class="commands"><button class="btn ${m.next==='left'?'primary':''}" data-action="wood-hit" data-side="left">← 左</button><button class="btn ${m.next==='right'?'primary':''}" data-action="wood-hit" data-side="right">右 →</button></div></div></div>`;if(m.kind==='forge')return `<div class="modal-backdrop"><div class="modal forge-mini"><h2>🔥 自分で鍛える</h2><p class="tiny muted">赤熱した瞬間を狙って3回叩く。完成まで12step。</p><div class="forge-anvil">🔥<span>⚒️</span></div><div class="timing-bar forge-timing"><div class="sweet"></div><div class="moving-marker"></div></div><div class="hammer-count">${'🔨'.repeat(m.hits)}${'▫️'.repeat(3-m.hits)}</div><button class="btn primary big" data-action="forge-hit">カン！</button></div></div>`;return'';}

  overlayHtml(){return this.miniHtml()+this.modalHtml();}
  modalHtml(){if(!this.modal)return'';const m=this.modal;if(m.type==='return'){const cargo=Object.entries(m.data.cargo||{}).filter(([,n])=>n>0).map(([id,n])=>`<div class="line-item"><span>${materials[id].icon} ${materials[id].name}</span><b>×${n}</b></div>`).join(''),fresh=Object.entries(m.data.fresh||{}).filter(([,n])=>n>0).map(([id,n])=>`<div class="line-item"><span>${materials[id].icon} ${materials[id].name}</span><b>×${n}（寿命継続）</b></div>`).join('');return `<div class="modal-backdrop"><div class="modal"><h2>${m.data.method==='rura'?'🌀 帰還':'🏘️ 帰村'}</h2><div class="card">${cargo}${fresh}${(!cargo&&!fresh)?'<div class="empty">持ち帰り素材なし</div>':''}</div><p class="tiny muted top-gap">EXPは探索中にすでに反映済み。</p><button class="btn primary top-gap" data-action="close-modal">閉じる</button></div></div>`;}if(m.type==='lost')return `<div class="modal-backdrop"><div class="modal"><h2>💀 探索失敗</h2><p class="tiny muted">探索中の素材とバッグ内の生鮮品を失った。獲得済みEXPは失わない。</p><button class="btn top-gap" data-action="close-modal">村へ</button></div></div>`;return'';}

  bindCommon(){
    this.root.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>{this.tab=el.dataset.tab;this.render();}));
    this.root.querySelectorAll('[data-scene]').forEach(el=>el.addEventListener('click',()=>{this.itemScene=el.dataset.scene;this.render();}));
    this.root.querySelectorAll('[data-production]').forEach(el=>el.addEventListener('click',()=>{this.productionMode=el.dataset.production;this.render();}));
    this.root.querySelectorAll('[data-equip-slot]').forEach(el=>el.addEventListener('click',()=>{this.equipSlot=el.dataset.equipSlot;this.render();}));
    this.root.querySelectorAll('[data-action="start-expedition"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=startExpedition(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="travel"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=travelTo(this.state,el.dataset.id);if(r.returned){this.modal={type:'return',data:r.report};this.tab='home';}this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="open-run-bag"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=true;this.render();}));
    this.root.querySelectorAll('[data-action="close-run-bag"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=false;this.render();}));
    this.root.querySelectorAll('[data-run-item]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=useFieldItem(this.state,el.dataset.runItem);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="rura"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=false;this.mutate(()=>{const r=useRura(this.state);if(r.ok){this.modal={type:'return',data:r.report};this.tab='home';}this.toast(r.msg);});})); 
    this.root.querySelectorAll('[data-action="camp"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=false;this.mutate(()=>{const r=camp(this.state);this.toast(r.msg);});})); 
    this.root.querySelectorAll('[data-action="gather-herb"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=harvestResult(this.state,1);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="start-mini"]').forEach(el=>el.addEventListener('click',()=>this.startMini(el.dataset.kind)));
    this.root.querySelectorAll('[data-action="mine-hit"]').forEach(el=>el.addEventListener('click',()=>this.miningHit()));
    this.root.querySelectorAll('[data-action="fish-tap"]').forEach(el=>el.addEventListener('click',()=>this.fishingTap()));
    this.root.querySelectorAll('[data-action="wood-hit"]').forEach(el=>el.addEventListener('click',()=>this.woodTap(el.dataset.side)));
    this.root.querySelectorAll('[data-action="forge-hit"]').forEach(el=>el.addEventListener('click',()=>this.forgeHit()));
    this.root.querySelectorAll('[data-cmd]').forEach(el=>el.addEventListener('click',()=>this.performBattleCommand(el.dataset.cmd)));
    this.root.querySelectorAll('[data-action="finish-battle"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=finishBattle(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="defeat-return"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=defeatReturn(this.state);if(r.ok){this.modal={type:'lost',data:r.lost};this.tab='home';}})));
    this.root.querySelectorAll('[data-action="town-rest"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=restAtTown(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="buy"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=buyConsumable(this.state,el.dataset.id);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="upgrade-pack"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=upgradeBackpack(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="sell"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=sellMaterial(this.state,el.dataset.id,1);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="sell-all"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=sellAll(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="order-craft"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=orderCraft(this.state,el.dataset.id);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="self-craft"]').forEach(el=>el.addEventListener('click',()=>this.startMini('forge',{recipeId:el.dataset.id})));
    this.root.querySelectorAll('[data-action="collect-forge"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=collectForgeOrder(this.state,el.dataset.id);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="brew"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=brewPotion(this.state,.6);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="equip"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{if(equip(this.state,el.dataset.id))this.toast('装備した。');}))); 
    this.root.querySelectorAll('[data-action="close-modal"]').forEach(el=>el.addEventListener('click',()=>{this.modal=null;this.render();}));
    this.root.querySelectorAll('[data-action="export"]').forEach(el=>el.addEventListener('click',()=>this.exportSave()));
    this.root.querySelectorAll('[data-action="install"]').forEach(el=>el.addEventListener('click',async()=>{if(!this.installPrompt)return;await this.installPrompt.prompt();this.installPrompt=null;this.render();}));
    const imp=this.root.querySelector('#import-file');if(imp)imp.addEventListener('change',e=>this.importSave(e.target.files?.[0]));
    this.root.querySelectorAll('[data-action="reset"]').forEach(el=>el.addEventListener('click',()=>{if(confirm('セーブデータを完全に消して最初から始めますか？'))window.dispatchEvent(new CustomEvent('gq-reset'));}));
  }

  exportSave(){const blob=new Blob([JSON.stringify(this.state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`grindquest-save-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async importSave(file){if(!file)return;try{const data=JSON.parse(await file.text());window.dispatchEvent(new CustomEvent('gq-import',{detail:data}));this.toast('セーブを読み込んだ。');}catch{this.toast('セーブファイルを読み込めなかった。');}}
}
