import {
  EQUIPMENT_SLOTS, FRESH_STORAGE_UPGRADES, STORAGE_UPGRADES, adjacentNodes, backpackCapacity, backpacks, battleItemStacks,
  battleSkillList, battleSpellList, brewPotion, buyConsumable, camp, campStatus, canAlchemy, canCraft,
  collectForgeOrder, command, consumables, currentLocation, defeatReturn, derived, enemies, equip,
  equipmentList, expToNext, finishBattle, forgeOrders, gearById, gearDisplayName, gearStats, harvestResult,
  ITEM_TAGS, items, lifeSkillInfo, localAdjacentNodes, localAreaEntry, localAreaType, localAreas, localMove, localPatrol, materialCount, materials, orderCraft, patrol, phaseInfo, recipes,
  areaTransitionStatus, bossStatus, currentLocalArea, currentPlace, enterLocalArea, leaveLocalArea, resourceStatus, restAtTown, sellAll, sellAllValuables, sellEquipment, sellStack, selfCraft, sleepDuration,
  stackCount, stackDefinition, stackList, stackQualityLabel, stackRemaining, startExpedition, transferStack,
  travelTo, upgradeBackpack, upgradeFreshWarehouse, upgradeWarehouse, useAreaTransition, useFieldItem, useRura, usedCapacity, usedFreshStorageCapacity, usedStorageCapacity,
  freshWarehouseCapacity, warehouseCapacity, warehouseGroups, WORKMANSHIP_NAMES, worldEdges, worldNodes
} from '../core/game.js';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(a,b)=>Math.max(0,Math.min(100,b?100*a/b:0));
const fmtCost=cost=>Object.entries(cost).map(([id,n])=>`${materials[id].icon}${materials[id].name} ${n}`).join(' / ');
const lifeText=s=>s.remainingLife==null?'保存期限なし':`寿命 ${stackRemaining(s)}step`;
const qText=s=>stackQualityLabel(s)||'品質0';
const tagText=id=>ITEM_TAGS[stackDefinition(id)?.tag]||'その他';

export class AppUI{
  constructor(root,state,onChange){
    this.root=root;this.state=state;this.onChange=onChange;
    this.tab='home';this.itemScene='menu';this.productionMode='forge';this.equipSlot='weapon';
    this.modal=null;this.minigame=null;this.runBagOpen=false;this.installPrompt=null;this.warehouseMode='normal';this.warehouseOpen=new Set();this.freshQualityOpen=new Set();
    this.toastTimer=null;this.fishTimer=null;this.fishMissTimer=null;this.battleVisible=false;this.battleTransitionTimer=null;
    this.battleFx=null;this.commandLocked=false;this.fxTimer=null;this.battleMenu='root';
  }
  setInstallPrompt(e){this.installPrompt=e;this.render();}
  async mutate(fn){const r=fn?.();await this.onChange();this.render();return r;}
  toast(msg){if(!msg)return;const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),2800);if(this.state.settings.vibrate&&navigator.vibrate)navigator.vibrate(15);}

  render(){
    if(this.state.battle){if(!this.battleVisible){this.battleVisible=true;this.battleMenu='root';return this.renderBattleTransition();}return this.renderBattle();}
    this.battleVisible=false;this.commandLocked=false;this.battleFx=null;this.battleMenu='root';clearTimeout(this.battleTransitionTimer);clearTimeout(this.fxTimer);
    if(this.state.run)return this.renderRun();
    const content={home:()=>this.home(),items:()=>this.itemsTab(),production:()=>this.production(),equipment:()=>this.equipment(),settings:()=>this.settings()}[this.tab]?.()||this.home();
    this.root.innerHTML=`<div class="shell">${this.topbar()}<main>${content}</main>${this.nav()}</div>${this.overlayHtml()}`;this.bindCommon();
  }

  timeText(){const p=phaseInfo(this.state);return `${p.icon} ${this.state.calendar.day}日目 ${p.name} ${p.stepInPhase}/${p.phaseSteps}`;}
  topbar(){return `<header class="topbar"><div class="brand">GRINDQUEST<small>field expedition RPG</small></div><div class="topbar-right"><span class="money-pill">${this.state.gold}G</span><div class="time-pill">${this.timeText()}</div></div></header>`;}
  nav(){const tabs=[['home','🏘️','村'],['items','🎒','持ち物'],['production','⚒️','生産'],['equipment','🛡️','装備'],['settings','⚙️','設定']];return `<nav class="bottom-nav five">${tabs.map(([id,ic,l])=>`<button class="nav-btn ${this.tab===id?'active':''}" data-tab="${id}"><span>${ic}</span>${l}</button>`).join('')}</nav>`;}
  fatigueChip(){const stacks=this.state.condition?.fatigueStacks||0,awake=this.state.condition?.awakeSteps||0;if(stacks)return `<span class="fatigue-chip danger-chip">🥱 -${stacks*10}%</span>`;if(awake>=200)return `<span class="fatigue-chip warn-chip">🥱 ${awake}step</span>`;return `<span class="fatigue-chip">覚醒 ${awake}</span>`;}

  playerCard(){const p=this.state.player,d=derived(this.state),need=expToNext(p.level),phase=phaseInfo(this.state);return `<section class="hero-card">
    <div class="row"><div class="avatar">🧑‍⚔️</div><div class="grow"><h1>${esc(p.name)} <span class="tiny muted">Lv.${p.level}</span></h1><div class="tiny muted">${gearDisplayName(this.state,p.equipment.weapon)} / ${gearDisplayName(this.state,p.equipment.body)}</div></div></div>
    <div class="section"><div class="tiny row between"><span>HP ${p.hp}/${d.maxHp}</span><span>MP ${p.mp}/${d.maxMp}</span></div><div class="bar"><i style="width:${pct(p.hp,d.maxHp)}%"></i></div><div class="bar mp"><i style="width:${pct(p.mp,d.maxMp)}%"></i></div><div class="tiny muted top-gap">EXP ${p.exp}/${need}</div><div class="bar exp"><i style="width:${pct(p.exp,need)}%"></i></div></div>
    <div class="stats"><div class="stat"><b>${d.atk}</b><span>こうげき</span></div><div class="stat"><b>${d.def}</b><span>しゅび</span></div><div class="stat"><b>${d.agility}</b><span>すばやさ</span></div></div>
    <div class="base-stats-grid">${[['vitality','たいりょく'],['strength','ちから'],['agility','すばやさ'],['magic','まりょく'],['wisdom','かしこさ'],['knowledge','ちしき'],['dexterity','きようさ']].map(([k,l])=>`<span><b>${d[k]}</b><small>${l}</small></span>`).join('')}</div>
    <div class="calendar-strip"><div><b>${phase.icon} ${this.state.calendar.day}日目 ${phase.name}</b><span>あと${phase.remaining}step</span></div>${this.fatigueChip()}</div>
  </section>`;}

  home(){const sleep=sleepDuration(this.state);return `${this.playerCard()}
    <section class="section"><div class="section-title"><h2>村から出る</h2><span class="tiny muted">バッグの中身をそのまま持っていく</span></div><div class="card"><button class="btn primary big" data-action="start-expedition">🗺️ 周辺探索へ出発</button></div></section>
    <section class="section"><div class="section-title"><h2>家</h2></div><div class="card"><div class="row between"><div class="grow"><b>しっかり眠る</b><div class="tiny muted">今なら${sleep}step。HP/MP全回復、徹夜疲労解除。</div></div><button class="btn" data-action="town-rest">🛏️ 寝る</button></div></div></section>
    <section class="section"><div class="section-title"><h2>最近の記録</h2></div><div class="card">${this.state.log.slice(0,5).map(x=>`<div class="line-item"><span class="tiny">${esc(x)}</span></div>`).join('')}</div></section>`;}

  nextPack(){const ids=['cheap','canvas','explorer'],i=ids.indexOf(this.state.backpack);return i>=0?backpacks[ids[i+1]]:null;}
  sceneBack(){return `<button class="icon-btn" data-scene="menu">←</button>`;}
  itemsTab(){
    if(this.itemScene==='shop')return this.shop();if(this.itemScene==='bag')return this.townBag();if(this.itemScene==='warehouse')return this.warehouse();
    return `<div class="scene-header"><div><h2>持ち物</h2><div class="tiny muted">村でバッグと2種類の倉庫を整理する</div></div><span class="pill">${this.state.gold}G</span></div><div class="facility-grid">
      <button class="facility-card" data-scene="bag"><span>🎒</span><b>バッグ</b><small>${usedCapacity(this.state)}/${backpackCapacity(this.state)} / 生鮮は寿命優先表示</small></button>
      <button class="facility-card" data-scene="warehouse"><span>📦</span><b>倉庫</b><small>通常 ${usedStorageCapacity(this.state)}/${warehouseCapacity(this.state)} / 生鮮 ${usedFreshStorageCapacity(this.state)}/${freshWarehouseCapacity(this.state)}</small></button>
      <button class="facility-card" data-scene="shop"><span>🏪</span><b>道具屋</b><small>保存薬・キャンプ道具・バッグ</small></button>
    </div>`;
  }
  stackRow(s,{townBag=false,battle=false}={}){const def=stackDefinition(s.id),life=lifeText(s),tag=tagText(s.id);return `<div class="stack-row ${s.remainingLife!=null&&stackRemaining(s)<=50?'fresh-critical':''}"><div class="stack-icon">${def.icon}</div><div class="stack-main"><b>${def.name} <span class="quality-badge q${s.quality}">${qText(s)}</span> ×${s.count}</b><small><span class="item-tag tag-${def.tag||'other'}">${tag}</span> ${life}</small></div>${battle?`<button class="btn small primary" data-battle-item="${s.stackId}">使う</button>`:''}${townBag?`<button class="btn small" data-action="to-storage" data-stack="${s.stackId}">${s.remainingLife==null?'通常倉庫へ':'生鮮倉庫へ'}</button>`:''}</div>`;}
  townBag(){const list=stackList(this.state,'bag');return `<div class="scene-header"><div class="row">${this.sceneBack()}<div><h2>バッグ</h2><div class="tiny muted">寿命を品質より優先して並べる</div></div></div><span class="pill">${usedCapacity(this.state)}/${backpackCapacity(this.state)}</span></div><div class="card tiny muted">寿命なしは品質ごとに実スタック。寿命ありは取得バッチごとに寿命を保持する。キャンプセットは ${this.state.consumables.camp_set||0} 個。</div><section class="section stack-list">${list.length?list.map(s=>this.stackRow(s,{townBag:true})).join(''):'<div class="card empty">バッグは空っぽ。</div>'}</section>`;}
  qualityChip(q){return `<span class="warehouse-qchip q${q.quality}">${q.quality?`☆${q.quality}`:'☆0'}: <b>${q.count}個</b></span>`;}
  normalWarehouseGroup(g){const open=this.warehouseOpen.has(g.id);return `<article class="warehouse-group"><button class="warehouse-item-head" data-action="toggle-warehouse-item" data-id="${g.id}"><span class="warehouse-item-icon">${g.def.icon}</span><span class="warehouse-item-name"><b>${g.def.name}</b><small>${ITEM_TAGS[g.def.tag]||'その他'} / 合計${g.count}個</small></span><span class="warehouse-caret">${open?'⌃':'⌄'}</span></button><div class="warehouse-quality-chips">${g.qualities.map(q=>this.qualityChip(q)).join('')}</div>${open?`<div class="warehouse-detail">${g.qualities.map(q=>{const s=q.stacks[0];return `<div class="warehouse-quality-row"><div><b>${q.quality?`☆${q.quality}`:'☆0'} ×${q.count}</b><small>同品質は取得時期を問わず1スタック</small></div><div class="warehouse-row-actions"><button class="btn tiny-btn" data-action="to-bag" data-stack="${s.stackId}" data-count="1">1個出す</button><button class="btn tiny-btn" data-action="to-bag" data-stack="${s.stackId}" data-count="all">全部出す</button>${materials[g.id]?`<button class="btn tiny-btn danger" data-action="sell-stack" data-stack="${s.stackId}" data-count="1">1個売る</button><button class="btn tiny-btn danger" data-action="sell-stack" data-stack="${s.stackId}" data-count="all">全部売る</button>`:''}</div></div>`}).join('')}</div>`:''}</article>`;}
  freshWarehouseGroup(g){const open=this.warehouseOpen.has(g.id);return `<article class="warehouse-group fresh-group"><button class="warehouse-item-head" data-action="toggle-warehouse-item" data-id="${g.id}"><span class="warehouse-item-icon">${g.def.icon}</span><span class="warehouse-item-name"><b>${g.def.name}</b><small>${ITEM_TAGS[g.def.tag]||'その他'} / 合計${g.count}個</small></span><span class="warehouse-caret">${open?'⌃':'⌄'}</span></button><div class="warehouse-quality-chips">${g.qualities.map(q=>this.qualityChip(q)).join('')}</div>${open?`<div class="warehouse-detail">${g.qualities.map(q=>{const key=`${g.id}:${q.quality}`,qOpen=this.freshQualityOpen.has(key);return `<section class="fresh-quality-block"><button class="fresh-quality-head" data-action="toggle-fresh-quality" data-key="${key}"><b>${q.quality?`☆${q.quality}`:'☆0'} ×${q.count}</b><span>${qOpen?'⌃':'⌄'} 寿命別</span></button>${qOpen?`<div class="fresh-life-list">${q.stacks.map(s=>`<div class="fresh-life-row"><div><b>寿命 ${s.remaining}step</b><small>×${s.count} / 保管中は1/3速度</small></div><div class="warehouse-row-actions"><button class="btn tiny-btn" data-action="to-bag" data-stack="${s.stackId}" data-count="1">1個出す</button><button class="btn tiny-btn" data-action="to-bag" data-stack="${s.stackId}" data-count="all">全部出す</button>${materials[g.id]?`<button class="btn tiny-btn danger" data-action="sell-stack" data-stack="${s.stackId}" data-count="1">1個売る</button><button class="btn tiny-btn danger" data-action="sell-stack" data-stack="${s.stackId}" data-count="all">全部売る</button>`:''}</div></div>`).join('')}</div>`:''}</section>`}).join('')}</div>`:''}</article>`;}
  warehouse(){const fresh=this.warehouseMode==='fresh',groups=warehouseGroups(this.state,fresh?'fresh':'normal'),next=fresh?FRESH_STORAGE_UPGRADES[this.state.freshWarehouseLevel+1]:STORAGE_UPGRADES[this.state.warehouseLevel+1],used=fresh?usedFreshStorageCapacity(this.state):usedStorageCapacity(this.state),cap=fresh?freshWarehouseCapacity(this.state):warehouseCapacity(this.state);const valuable=warehouseGroups(this.state,'normal').some(g=>g.def?.tag==='valuable')||warehouseGroups(this.state,'fresh').some(g=>g.def?.tag==='valuable');return `<div class="scene-header"><div class="row">${this.sceneBack()}<div><h2>倉庫</h2><div class="tiny muted">素材名 → 品質 → ${fresh?'寿命':'処理'} の階層表示</div></div></div><span class="pill">${used}/${cap}</span></div>
    <div class="warehouse-tabs"><button class="${fresh?'':'active'}" data-action="warehouse-mode" data-mode="normal">📦 通常倉庫<small>${usedStorageCapacity(this.state)}/${warehouseCapacity(this.state)}</small></button><button class="${fresh?'active':''}" data-action="warehouse-mode" data-mode="fresh">🫙 生鮮倉庫<small>${usedFreshStorageCapacity(this.state)}/${freshWarehouseCapacity(this.state)}</small></button></div>
    <div class="warehouse-header card"><div><b>${fresh?FRESH_STORAGE_UPGRADES[this.state.freshWarehouseLevel].name:STORAGE_UPGRADES[this.state.warehouseLevel].name}</b><div class="tiny muted">${fresh?'寿命あり専用。個体寿命を保持したまま表示だけ疑似スタック。劣化速度1/3。':'寿命なし専用。同一アイテム・同一品質は時系列を問わず実スタック。'}</div></div>${next?`<button class="btn small" data-action="${fresh?'upgrade-fresh-warehouse':'upgrade-warehouse'}">拡張 ${next.price}G → ${next.capacity}</button>`:'<span class="tag">MAX</span>'}</div>
    ${!fresh?`<div class="card top-gap"><div class="row between"><span class="tiny muted">両倉庫の換金タグを一括売却。</span><button class="btn small good" data-action="sell-valuables" ${valuable?'':'disabled'}>💰 換金品を全て売る</button></div></div>`:''}
    <section class="section warehouse-groups">${groups.length?groups.map(g=>fresh?this.freshWarehouseGroup(g):this.normalWarehouseGroup(g)).join(''):`<div class="card empty">${fresh?'生鮮倉庫':'通常倉庫'}は空っぽ。</div>`}</section>`;}
  shop(){const nextPack=this.nextPack();return `<div class="scene-header"><div class="row">${this.sceneBack()}<div><h2>道具屋</h2><div class="tiny muted">「いらっしゃい！」</div></div></div><span class="pill">${this.state.gold}G</span></div><div class="shop-counter">🧑‍💼<div><b>旅支度なら任せな。</b><small>店売り消耗品は品質0。</small></div></div><div class="cards">${Object.values(consumables).map(c=>{const n=c.id==='camp_set'?(this.state.consumables.camp_set||0):stackCount(this.state,c.id,'bag');return `<div class="card shop-row"><div class="item-icon">${c.icon}</div><div class="grow"><b>${c.name}</b><div class="tiny muted">${c.desc}</div><div class="tiny">バッグ所持 ${n} / 容量${c.bulk}</div></div><button class="btn small" data-action="buy" data-id="${c.id}" ${(c.max&&n>=c.max)?'disabled':''}>${c.price}G</button></div>`}).join('')}
    <div class="card shop-row"><div class="item-icon">${backpacks[this.state.backpack].icon}</div><div class="grow"><b>${backpacks[this.state.backpack].name}</b><div class="tiny muted">現在容量 ${backpackCapacity(this.state)}</div>${nextPack?`<div class="tiny">次: ${nextPack.name} / ${nextPack.capacity}</div>`:'<div class="tiny">最大サイズ</div>'}</div>${nextPack?`<button class="btn small" data-action="upgrade-pack">${nextPack.price}G</button>`:'<span class="tag">MAX</span>'}</div></div>`;}

  production(){return `<div class="scene-header"><div><h2>生産</h2><div class="tiny muted">今回は鍛冶を拡張。調合は保留中。</div></div><span class="pill">${this.state.gold}G</span></div>${this.forge()}`;}
  forge(){const orders=forgeOrders(this.state);return `<section class="section"><div class="section-title"><h3>依頼中</h3><span class="tiny muted">鍛冶屋: 60step / 出来栄え「良」基準</span></div>${orders.length?`<div class="cards">${orders.map(o=>{const it=items[o.payload.item],remain=Math.max(0,o.readyAt-this.state.calendar.totalSteps);return `<div class="card shop-row"><div class="item-icon">${it.icon}</div><div class="grow"><b>R${it.rank} ${it.name}</b><div class="tiny ${o.ready?'good-text':'muted'}">${o.ready?'完成済み':`完成まで ${remain}step`}</div></div>${o.ready?`<button class="btn good small" data-action="collect-forge" data-id="${o.id}">受取</button>`:'<span class="tag">作業中</span>'}</div>`}).join('')}</div>`:'<div class="card empty">依頼中の装備はない。</div>'}</section>
    <section class="section"><div class="section-title"><h3>レシピ</h3><span class="tiny muted">この周辺の上限は Rank 2</span></div><div class="cards">${recipes.map(r=>{const it=items[r.item],can=canCraft(this.state,r);return `<div class="card recipe-card"><div class="row"><div class="item-icon">${it.icon}</div><div class="grow"><h3><span class="rank-badge">R${it.rank}</span> ${it.name}</h3><div class="tiny muted">${it.desc}</div><div class="tiny top-gap">${fmtCost(r.cost)}</div></div></div><div class="dual-actions"><button class="btn" data-action="order-craft" data-id="${r.id}" ${can?'':'disabled'}>👨‍🏭 頼む<small>60step後</small></button><button class="btn primary" data-action="self-craft" data-id="${r.id}" ${can?'':'disabled'}>🔨 自分で打つ<small>出来栄え判定</small></button></div></div>`}).join('')}</div></section>`;}
  alchemy(){const ok=canAlchemy(this.state);return `<section class="section"><div class="card"><h3>🧪 調合は一旦保留</h3><p class="tiny muted top-gap">旧ポーションレシピだけ残してある。品質ミニゲームはまだ作らない。</p><button class="btn top-gap" data-action="brew" ${ok?'':'disabled'}>仮調合: 薬草+キノコ+20G</button></div></section>`;}

  equipment(){const p=this.state.player,d=derived(this.state),slotName=Object.fromEntries(EQUIPMENT_SLOTS)[this.equipSlot],available=equipmentList(this.state,this.equipSlot);return `<div class="scene-header"><div><h2>そうび</h2><div class="tiny muted">Rank / 出来栄え / 追加効果</div></div><span class="pill">${this.state.gold}G</span></div><div class="dq9-equip"><section class="equip-character"><div class="equip-avatar">🧑‍⚔️</div><b>${esc(p.name)}</b><div class="equip-statline"><span>こうげき力</span><b>${d.atk}</b></div><div class="equip-statline"><span>しゅび力</span><b>${d.def}</b></div><div class="equip-statline"><span>すばやさ</span><b>${d.agility}</b></div><div class="equip-statline"><span>きようさ</span><b>${d.dexterity}</b></div></section><section class="equip-slots">${EQUIPMENT_SLOTS.map(([slot,label])=>{const gid=p.equipment[slot],g=gearById(this.state,gid),it=g&&items[g.baseId];return `<button class="equip-slot ${this.equipSlot===slot?'selected':''}" data-equip-slot="${slot}"><span>${label}</span><b>${it?`${it.icon} ${gearDisplayName(this.state,g)}`:'－'}</b><i>›</i></button>`}).join('')}</section></div><section class="section"><div class="section-title"><h3>${slotName}</h3></div><div class="cards">${available.length?available.map(g=>{const it=items[g.baseId],gs=gearStats(this.state,g),eq=p.equipment[this.equipSlot]===g.gearId;return `<div class="card equip-choice"><div class="item-icon">${it.icon}</div><div class="grow"><b><span class="rank-badge">R${it.rank}</span> ${gearDisplayName(this.state,g)}</b><div class="tiny muted">攻+${gs.atk||0} 守+${gs.def||0} HP+${gs.hp||0} MP+${gs.mp||0}</div><div class="tiny">${(g.affixes||[]).length?`追加効果: ${g.affixes.map(a=>`${a.stat}+${a.value}`).join(' / ')}`:'追加効果なし'}</div></div>${eq?'<span class="tag">E</span>':`<div class="equip-actions"><button class="btn small" data-action="equip" data-id="${g.gearId}">そうび</button><button class="btn small danger" data-action="sell-gear" data-id="${g.gearId}">売る</button></div>`}</div>`}).join(''):'<div class="card empty">この部位はまだ何もない。</div>'}</div></section>`;}
  settings(){return `<div class="section-title"><h2>設定・セーブ</h2></div><div class="cards">${this.installPrompt?`<div class="card"><h3>📲 ホーム画面に追加</h3><button class="btn primary top-gap" data-action="install">インストール</button></div>`:''}<div class="card"><h3>放置探索</h3><p class="tiny muted">v0.9でも封印中。</p></div><div class="card"><h3>品質</h3><p class="tiny muted">品質0 / ☆1 / ☆2 / ☆3。高品質ほど回復量・寿命・素材価値が上がる。</p></div><div class="card"><h3>セーブ</h3><div class="cards top-gap"><button class="btn" data-action="export">書き出す</button><label class="btn center">読み込む<input type="file" id="import-file" accept="application/json" hidden></label><button class="btn danger" data-action="reset">最初から</button></div></div></div>`;}

  compactRunHud(){const p=this.state.player,d=derived(this.state),need=expToNext(p.level);return `<section class="run-hud-compact"><div class="run-hud-top"><b>Lv.${p.level}</b><div class="mini-gauge hp"><span>HP ${p.hp}</span><i><em style="width:${pct(p.hp,d.maxHp)}%"></em></i></div><div class="mini-gauge mp"><span>MP ${p.mp}</span><i><em style="width:${pct(p.mp,d.maxMp)}%"></em></i></div><span class="run-exp">EXP ${p.exp}/${need}</span><span class="run-pack">🎒${usedCapacity(this.state)}/${backpackCapacity(this.state)}</span><button class="bag-open-btn" data-action="open-run-bag">🎒</button></div>${this.state.condition.fatigueStacks?`<div class="run-fatigue">🥱 -${this.state.condition.fatigueStacks*10}%</div>`:''}</section>`;}
  renderRun(){return this.state.run?.area?this.renderLocalRun():this.renderWorldRun();}
  renderWorldRun(){const run=this.state.run,loc=currentLocation(this.state),adj=new Set(adjacentNodes(loc.id).map(x=>x.id)),resource=resourceStatus(this.state),entry=localAreaEntry(this.state),edges=worldEdges.map(e=>{const a=worldNodes[e.a],b=worldNodes[e.b];return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="field-edge"/>`;}).join('');
    const nodes=Object.values(worldNodes).map(n=>{const current=n.id===loc.id,can=adj.has(n.id),visited=run.visited.includes(n.id),camp=n.campSafety==='safe'?' ⛺':n.campSafety==='semi'?' ⚠️':'',inside=n.interior?'<i class="interior-mark">↳</i>':'';const action=current?'patrol':'travel',enabled=current||can;return `<button class="field-node ${can?'reachable':''} ${current?'current-location':''} ${visited?'visited':''}" style="left:${n.x}%;top:${n.y}%" data-action="${action}" data-id="${n.id}" ${enabled?'':'disabled'}>${inside}${current?'<i class="map-player-marker">🧑‍⚔️</i>':''}<span>${n.icon}</span><small>${n.name}${camp}</small>${current?`<em class="patrol-hint">${n.id==='town'?'村へ戻る':'足踏み'}</em>`:''}</button>`;}).join('');
    this.root.innerHTML=`<div class="shell run-shell"><header class="run-topbar"><div><b>${loc.icon} ${loc.name}</b><small>${loc.desc}</small></div><span>${this.timeText()}</span></header><main>${this.compactRunHud()}${run.lastEvent?`<section class="event-strip"><b>出来事</b><span>${esc(run.lastEvent)}</span></section>`:''}<section class="section"><div class="section-title"><h2>周辺地図</h2><span class="tiny muted">現在地タップ=巡回 / ↳は進入可能</span></div><div class="map-stage"><div class="map-viewport" id="map-viewport"><div class="field-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${edges}</svg>${nodes}</div></div>${this.mapAction(resource)}${entry?`<button class="area-entry-overlay" data-action="enter-area"><span>🚪</span><b>入る</b><small>${entry.area.name}</small></button>`:''}</div></section><section class="location-mini"><b>${loc.icon} ${loc.name}</b><span>${loc.desc}</span>${entry?`<em>ローカルエリア：${entry.area.typeName}「${entry.area.name}」</em>`:''}</section></main></div>${this.overlayHtml()}${this.runBagOpen?this.runBagHtml():''}`;this.bindCommon();setTimeout(()=>this.centerMap(),0);}
  renderLocalRun(){const run=this.state.run,area=currentLocalArea(this.state),loc=currentPlace(this.state),adj=new Set(localAdjacentNodes(this.state).map(x=>x.id)),resource=resourceStatus(this.state),transition=areaTransitionStatus(this.state),edges=area.edges.map(e=>{const a=area.nodes[e.a],b=area.nodes[e.b];return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="field-edge local-edge"/>`;}).join('');
    const nodes=Object.values(area.nodes).map(n=>{const current=n.id===run.area.nodeId,can=adj.has(n.id),visited=run.area.visited.includes(n.id),key=`${area.id}:${n.id}`,defeated=run.defeatedSymbols.includes(key),bs=n.bossEnemy?bossStatus(this.state,area.id,n.id):null,symbolAlive=n.symbolEnemy&&!defeated,bossAlive=n.bossEnemy&&bs?.ready,icon=bossAlive?'👑':n.bossEnemy&&!bs?.ready?'💤':symbolAlive?(enemies[n.symbolEnemy]?.icon||'👾'):n.icon,camp=n.campSafety==='safe'?' ⛺':n.campSafety==='semi'?' ⚠️':'';const action=current?'local-patrol':'local-move',enabled=current||can;return `<button class="field-node local-node ${can?'reachable':''} ${current?'current-location':''} ${visited?'visited':''} ${(symbolAlive||bossAlive)?'symbol-active':''}" style="left:${n.x}%;top:${n.y}%" data-action="${action}" data-id="${n.id}" ${enabled?'':'disabled'}>${current?'<i class="map-player-marker">🧑‍⚔️</i>':''}<span>${icon}</span><small>${n.name}${camp}</small>${n.bossEnemy&&!bs?.ready?`<em class="respawn-hint">復活 ${bs.remaining}step</em>`:''}${current?`<em class="patrol-hint">${(symbolAlive||bossAlive)?'接触':'足踏み'}</em>`:''}</button>`;}).join('');
    const canExit=!!area.entryWorld&&run.area.nodeId===area.entry;
    this.root.innerHTML=`<div class="shell run-shell local-run-shell"><header class="run-topbar local-topbar"><div><b>${loc.icon||'📍'} ${loc.name}</b><small>${area.name} / ${area.typeName}　${loc.desc}</small></div><span>${this.timeText()}</span></header><main>${this.compactRunHud()}${run.lastEvent?`<section class="event-strip"><b>出来事</b><span>${esc(run.lastEvent)}</span></section>`:''}<section class="section"><div class="section-title"><div><h2>${area.name}</h2><span class="area-type-badge ${area.type}">${area.typeName}</span></div><span class="tiny muted">移動 ${area.moveSteps||0}step基準</span></div><div class="map-stage local-map-stage"><div class="map-viewport local-map-viewport" id="map-viewport"><div class="field-map local-map ${area.type}"><svg viewBox="0 0 100 100" preserveAspectRatio="none">${edges}</svg>${nodes}</div></div>${this.mapAction(resource)}${transition?`<button class="area-entry-overlay transition" data-action="area-transition"><span>↪️</span><b>移動</b><small>${transition.transition.label||transition.destination.name}</small></button>`:''}${area.entryWorld?`<button class="area-exit-overlay" data-action="leave-area" ${canExit?'':'disabled'}>← 外へ</button>`:''}</div></section><section class="location-mini"><b>${loc.icon||'📍'} ${loc.name}</b><span>${loc.desc}</span><em>${area.type==='dungeon'?'階層・シンボル敵・ボスを持つダンジョン':'採集や寄り道に向いた小規模フィールド'}</em></section></main></div>${this.overlayHtml()}${this.runBagOpen?this.runBagHtml():''}`;this.bindCommon();setTimeout(()=>this.centerMap(),0);}
  mapAction(rs){if(!rs)return'';const skill=lifeSkillInfo(this.state,rs.kind),remain=rs.area?`残${rs.remainingUses}/${rs.maxUses}`:'';if(rs.used)return `<div class="map-action-overlay used">✓ 採集済み</div>`;if(rs.kind==='herb')return `<button class="map-action-overlay resource" data-action="gather-herb">🌿 採取 <small>Lv.${skill.level}/難${rs.difficulty}${remain?` / ${remain}`:''}</small></button>`;const labels={mining:'⛏️ 採掘',fishing:'🎣 釣る',woodcut:'🪓 伐採'};return `<button class="map-action-overlay resource" data-action="start-mini" data-kind="${rs.kind}">${labels[rs.kind]} <small>Lv.${skill.level}/難${rs.difficulty}${remain?` / ${remain}`:''}</small></button>`;}
  centerMap(){const vp=this.root.querySelector('#map-viewport'),node=this.root.querySelector('.current-location');if(!vp||!node)return;vp.scrollTo?.({left:Math.max(0,node.offsetLeft-vp.clientWidth/2),top:Math.max(0,node.offsetTop-vp.clientHeight/2),behavior:'instant'});}
  runBagHtml(){const p=this.state.player,d=derived(this.state),list=stackList(this.state,'bag'),cs=campStatus(this.state),place=currentPlace(this.state);return `<div class="run-bag-backdrop"><section class="run-bag-panel"><header><div><h2>🎒 バックパック</h2><small>${usedCapacity(this.state)}/${backpackCapacity(this.state)}　${place.name}</small></div><button class="icon-btn" data-action="close-run-bag">×</button></header><div class="bag-health"><div><span>HP ${p.hp}/${d.maxHp}</span><div class="bar"><i style="width:${pct(p.hp,d.maxHp)}%"></i></div></div><div><span>MP ${p.mp}/${d.maxMp}</span><div class="bar mp"><i style="width:${pct(p.mp,d.maxMp)}%"></i></div></div></div>${cs?.allowed?`<div class="bag-section"><button class="btn big ${cs.safety==='safe'?'good':'warn-btn'}" data-action="camp" ${cs.hasSet?'':'disabled'}>⛺ キャンプ　${cs.safety==='safe'?'安全':'襲撃の可能性'}</button></div>`:''}<div class="bag-section"><h3>持ち物</h3><div class="stack-list">${list.length?list.map(s=>{const def=stackDefinition(s.id),usable=!!def.consumable&&s.id!=='rura_potion',rura=s.id==='rura_potion';return `<div class="stack-row"><div class="stack-icon">${def.icon}</div><div class="stack-main"><b>${def.name} <span class="quality-badge q${s.quality}">${qText(s)}</span> ×${s.count}</b><small>${lifeText(s)}</small></div>${usable?`<button class="btn small primary" data-run-item="${s.stackId}">使う</button>`:''}${rura?`<button class="btn small magic" data-rura-stack="${s.stackId}">ルーラ</button>`:''}</div>`}).join(''):'<div class="empty">空っぽ。</div>'}</div></div></section></div>`;}


  renderBattleTransition(){clearTimeout(this.battleTransitionTimer);this.root.querySelector('.encounter-transition-overlay')?.remove();const overlay=document.createElement('div');overlay.className='encounter-transition-overlay';overlay.innerHTML='<div class="encounter-flash">魔物の気配……</div><div class="encounter-blackout"></div>';this.root.appendChild(overlay);this.battleTransitionTimer=setTimeout(()=>{if(this.state.battle)this.renderBattle();},620);}
  renderBattle(){const b=this.state.battle,e=enemies[b.enemyId],p=this.state.player,d=derived(this.state),phase=phaseInfo(this.state),fx=this.battleFx||{};this.root.innerHTML=`<div class="battle-shell retro-battle"><div class="battle-topline"><span>${currentPlace(this.state).name}</span><span>${phase.icon} ${this.state.calendar.day}日目 ${phase.name}　TURN ${b.turn}</span></div><main class="battle-main"><section class="battle-scene ${fx.stage==='player'?'player-strike':''}"><div class="enemy-name-window rpg-window"><b>${e.name}</b><span>HP ${b.enemyHp}/${b.enemyMaxHp}</span><div class="retro-hp"><i style="width:${pct(b.enemyHp,b.enemyMaxHp)}%"></i></div></div><div class="enemy-sprite retro-enemy ${fx.stage==='player'&&fx.enemyDamage?'enemy-hit':''}">${e.icon}</div>${fx.stage==='player'&&fx.enemyDamage?`<div class="damage-pop enemy-pop">-${fx.enemyDamage}</div><div class="slash-fx">／</div>`:''}<div class="battle-ground"></div></section><section class="battle-status rpg-window ${fx.stage==='enemy'&&fx.playerDamage?'player-hit':''}"><div class="status-name"><b>${p.name}</b><small>Lv.${p.level}</small></div><div class="player-vitals"><div class="vital-line"><span>HP ${p.hp}/${d.maxHp}</span><div class="battle-player-bar hp"><i style="width:${pct(p.hp,d.maxHp)}%"></i></div></div><div class="vital-line"><span>MP ${p.mp}/${d.maxMp}</span><div class="battle-player-bar mp"><i style="width:${pct(p.mp,d.maxMp)}%"></i></div></div></div><div class="battle-turn"><span>STEP</span><b>${this.state.calendar.totalSteps}</b></div>${fx.stage==='enemy'&&fx.playerDamage?`<div class="damage-pop player-pop">-${fx.playerDamage}</div>`:''}</section><section class="battle-message rpg-window">${b.log.slice(-4).map((x,i)=>`<div class="${i===b.log.slice(-4).length-1?'latest':''}">${esc(x)}</div>`).join('')}</section>${b.over?this.battleEnd():this.battleCommands()}</main></div>${this.overlayHtml()}`;this.bindCommon();}
  battleCommands(){if(this.battleMenu==='skills')return this.battleListMenu('とくぎ',battleSkillList().map(x=>({icon:x.icon,name:x.name,sub:`MP ${x.mp}`,attr:`data-battle-skill="${x.id}"`})));if(this.battleMenu==='magic')return this.battleListMenu('じゅもん',battleSpellList().map(x=>({icon:x.icon,name:x.name,sub:`MP ${x.mp}`,attr:`data-battle-spell="${x.id}"`})));if(this.battleMenu==='items')return this.battleListMenu('どうぐ',battleItemStacks(this.state).map(s=>{const d=stackDefinition(s.id);return{icon:d.icon,name:`${d.name} ${qText(s)} ×${s.count}`,sub:lifeText(s),attr:`data-battle-item="${s.stackId}"`};}));const escN=(this.state.battle.escapeAttempts||0)+1,escP=Math.min(100,Math.round(escN/3*100));return `<section class="battle-command-box rpg-window"><div class="command-title">コマンド <small>すばやさで行動順変動 / 1ターン=1step</small></div><div class="battle-button-grid six-command"><button class="battle-btn attack" data-cmd="attack"><span>⚔️</span><b>こうげき</b></button><button class="battle-btn skill" data-battle-menu="skills"><span>🔥</span><b>とくぎ</b></button><button class="battle-btn heal" data-battle-menu="magic"><span>✨</span><b>じゅもん</b></button><button class="battle-btn defend" data-cmd="defend"><span>🛡️</span><b>ぼうぎょ</b></button><button class="battle-btn item" data-battle-menu="items"><span>🎒</span><b>どうぐ</b><small>${battleItemStacks(this.state).length} stacks</small></button><button class="battle-btn escape" data-cmd="escape"><span>🏃</span><b>にげる</b><small>次 ${escP}%</small></button></div></section>`;}
  battleListMenu(title,rows){return `<section class="battle-command-box rpg-window battle-list-menu"><div class="command-title"><button class="battle-back" data-battle-menu="root">←</button>${title}</div><div class="battle-list">${rows.length?rows.map(r=>`<button class="battle-list-btn" ${r.attr}><span>${r.icon}</span><b>${r.name}</b><small>${r.sub}</small></button>`).join(''):'<div class="empty">使えるものがない。</div>'}</div></section>`;}
  battleEnd(){if(this.state.battle.won)return `<section class="battle-command-box rpg-window"><button class="battle-result-btn win" data-action="finish-battle">勝利！ 周囲へ戻る</button></section>`;if(this.state.battle.escaped)return `<section class="battle-command-box rpg-window"><button class="battle-result-btn escape-result" data-action="finish-battle">逃走成功！ 周囲へ戻る</button></section>`;return `<section class="battle-command-box rpg-window danger-window"><button class="battle-result-btn lose" data-action="defeat-return">村へ運ばれる</button></section>`;}
  async performBattleCommand(type,payload={}){if(this.commandLocked||!this.state.battle||this.state.battle.over)return;this.commandLocked=true;const r=command(this.state,type,payload);if(!r.ok){this.commandLocked=false;await this.onChange();this.render();return;}this.battleMenu='root';await this.onChange();const first=r.order==='enemy-first'?'enemy':'player',second=r.order==='enemy-first'?'player':'enemy';this.battleFx={stage:first,...r};this.render();clearTimeout(this.fxTimer);this.fxTimer=setTimeout(()=>{if(!this.state.battle){this.commandLocked=false;return;}const needsSecond=(second==='enemy'&&r.playerDamage)||(second==='player'&&(r.enemyDamage||r.heal));if(needsSecond){this.battleFx={stage:second,...r};this.render();this.fxTimer=setTimeout(()=>{this.battleFx=null;this.commandLocked=false;this.render();},360);}else{this.battleFx=null;this.commandLocked=false;this.render();}},360);}

  startMini(kind,extra={}){clearTimeout(this.fishTimer);clearTimeout(this.fishMissTimer);if(kind==='mining'){this.minigame={kind,start:performance.now()};this.render();return;}if(kind==='fishing'){this.minigame={kind,stage:'waiting'};this.render();this.fishTimer=setTimeout(()=>{if(this.minigame?.kind==='fishing'&&this.minigame.stage==='waiting'){this.minigame.stage='bite';this.render();this.fishMissTimer=setTimeout(()=>{if(this.minigame?.kind==='fishing'&&this.minigame.stage==='bite')this.resolveMini(.05,'魚に逃げられた。');},850);}},800+Math.random()*1700);return;}if(kind==='woodcut'){this.minigame={kind,next:'left',hits:0,errors:0,start:performance.now()};this.render();return;}if(kind==='forge'){this.minigame={kind,recipeId:extra.recipeId,hits:0,total:0,start:performance.now()};this.render();}}
  miningHit(){if(this.minigame?.kind!=='mining')return;const t=(performance.now()-this.minigame.start)%1600,pos=t/1600,quality=1-Math.min(1,Math.abs(pos-.5)*2);this.resolveMini(quality);}
  fishingTap(){if(this.minigame?.kind!=='fishing')return;if(this.minigame.stage==='bite')this.resolveMini(.9);else this.resolveMini(.08,'早合わせで魚が逃げた。');}
  woodTap(side){const m=this.minigame;if(m?.kind!=='woodcut')return;if(side===m.next){m.hits++;m.next=side==='left'?'right':'left';}else m.errors++;if(m.hits>=8){const sec=(performance.now()-m.start)/1000,quality=Math.max(.15,1-(Math.max(0,sec-3)*.08)-m.errors*.14);this.resolveMini(quality);return;}this.render();}
  forgeHit(){const m=this.minigame;if(m?.kind!=='forge')return;const t=(performance.now()-m.start)%1400,pos=t/1400,q=1-Math.min(1,Math.abs(pos-.5)*2);m.total+=q;m.hits++;if(m.hits>=3){const avg=m.total/3,recipeId=m.recipeId;this.minigame=null;this.mutate(()=>{const r=selfCraft(this.state,recipeId,avg);this.toast(r.msg);});return;}m.start=performance.now();this.render();}
  async resolveMini(quality,custom){clearTimeout(this.fishTimer);clearTimeout(this.fishMissTimer);const r=harvestResult(this.state,quality);this.minigame=null;await this.onChange();this.render();this.toast(custom||r.msg);}
  miniHtml(){const m=this.minigame;if(!m)return'';if(m.kind==='mining')return `<div class="modal-backdrop"><div class="modal"><h2>⛏️ 採掘</h2><p class="tiny muted">中央を狙う。採掘Lvと難度も品質に影響。</p><div class="timing-bar"><div class="sweet"></div><div class="moving-marker"></div></div><button class="btn primary big" data-action="mine-hit">振り下ろす！</button></div></div>`;if(m.kind==='fishing')return `<div class="modal-backdrop"><div class="modal"><h2>🎣 釣り</h2><div class="fish-water">${m.stage==='bite'?'<div class="bite">！！！</div>':'<div class="float">●</div>'}</div><button class="btn ${m.stage==='bite'?'good':'primary'} big" data-action="fish-tap">${m.stage==='bite'?'今だ！':'合わせる'}</button></div></div>`;if(m.kind==='woodcut')return `<div class="modal-backdrop"><div class="modal"><h2>🪓 木こり</h2><p class="tiny muted">左右交互に8回。</p><div class="wood-progress">${'▰'.repeat(m.hits)}${'▱'.repeat(8-m.hits)}</div><div class="commands"><button class="btn ${m.next==='left'?'primary':''}" data-action="wood-hit" data-side="left">← 左</button><button class="btn ${m.next==='right'?'primary':''}" data-action="wood-hit" data-side="right">右 →</button></div></div></div>`;if(m.kind==='forge')return `<div class="modal-backdrop"><div class="modal forge-mini"><h2>🔥 自分で鍛える</h2><div class="forge-anvil">🔥<span>⚒️</span></div><div class="timing-bar forge-timing"><div class="sweet"></div><div class="moving-marker"></div></div><div class="hammer-count">${'🔨'.repeat(m.hits)}${'▫️'.repeat(3-m.hits)}</div><button class="btn primary big" data-action="forge-hit">カン！</button></div></div>`;return'';}
  overlayHtml(){return this.miniHtml()+this.modalHtml();}
  modalHtml(){if(!this.modal)return'';const m=this.modal;if(m.type==='return')return `<div class="modal-backdrop"><div class="modal"><h2>${m.data.method==='rura'?'🌀 帰還':'🏘️ 帰村'}</h2><p class="tiny muted">帰村時に素材・換金品は倉庫へ自動収納。冒険用アイテムだけバッグに残る。</p><button class="btn primary top-gap" data-action="close-modal">閉じる</button></div></div>`;if(m.type==='lost')return `<div class="modal-backdrop"><div class="modal"><h2>💀 探索失敗</h2><p class="tiny muted">バッグ内の探索素材を失った。EXPは残る。</p><button class="btn top-gap" data-action="close-modal">村へ</button></div></div>`;return'';}

  bindCommon(){
    this.root.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>{this.tab=el.dataset.tab;this.itemScene='menu';this.render();}));
    this.root.querySelectorAll('[data-scene]').forEach(el=>el.addEventListener('click',()=>{this.itemScene=el.dataset.scene;this.render();}));
    this.root.querySelectorAll('[data-production]').forEach(el=>el.addEventListener('click',()=>{this.productionMode=el.dataset.production;this.render();}));
    this.root.querySelectorAll('[data-equip-slot]').forEach(el=>el.addEventListener('click',()=>{this.equipSlot=el.dataset.equipSlot;this.render();}));
    this.root.querySelectorAll('[data-action="start-expedition"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=startExpedition(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="travel"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=travelTo(this.state,el.dataset.id);if(r.returned){this.modal={type:'return',data:r.report};this.tab='home';}this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="patrol"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=patrol(this.state);if(r.returned){this.modal={type:'return',data:r.report};this.tab='home';}this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="enter-area"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=enterLocalArea(this.state);this.toast(r.msg);})));
    this.root.querySelectorAll('[data-action="leave-area"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=leaveLocalArea(this.state);this.toast(r.msg);})));
    this.root.querySelectorAll('[data-action="local-move"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=localMove(this.state,el.dataset.id);this.toast(r.msg);})));
    this.root.querySelectorAll('[data-action="local-patrol"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=localPatrol(this.state);this.toast(r.msg);})));
    this.root.querySelectorAll('[data-action="area-transition"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=useAreaTransition(this.state);this.toast(r.msg);})));
    this.root.querySelectorAll('[data-action="open-run-bag"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=true;this.render();}));
    this.root.querySelectorAll('[data-action="close-run-bag"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=false;this.render();}));
    this.root.querySelectorAll('[data-run-item]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=useFieldItem(this.state,el.dataset.runItem);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-rura-stack]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=false;this.mutate(()=>{const r=useRura(this.state,el.dataset.ruraStack);if(r.ok){this.modal={type:'return',data:r.report};this.tab='home';}this.toast(r.msg);});}));
    this.root.querySelectorAll('[data-action="camp"]').forEach(el=>el.addEventListener('click',()=>{this.runBagOpen=false;this.mutate(()=>{const r=camp(this.state);this.toast(r.msg);});}));
    this.root.querySelectorAll('[data-action="gather-herb"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=harvestResult(this.state,.72);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="start-mini"]').forEach(el=>el.addEventListener('click',()=>this.startMini(el.dataset.kind)));
    this.root.querySelectorAll('[data-action="mine-hit"]').forEach(el=>el.addEventListener('click',()=>this.miningHit()));this.root.querySelectorAll('[data-action="fish-tap"]').forEach(el=>el.addEventListener('click',()=>this.fishingTap()));this.root.querySelectorAll('[data-action="wood-hit"]').forEach(el=>el.addEventListener('click',()=>this.woodTap(el.dataset.side)));this.root.querySelectorAll('[data-action="forge-hit"]').forEach(el=>el.addEventListener('click',()=>this.forgeHit()));
    this.root.querySelectorAll('[data-battle-menu]').forEach(el=>el.addEventListener('click',()=>{this.battleMenu=el.dataset.battleMenu;this.render();}));
    this.root.querySelectorAll('[data-cmd]').forEach(el=>el.addEventListener('click',()=>this.performBattleCommand(el.dataset.cmd)));
    this.root.querySelectorAll('[data-battle-skill]').forEach(el=>el.addEventListener('click',()=>this.performBattleCommand('skill',{id:el.dataset.battleSkill})));
    this.root.querySelectorAll('[data-battle-spell]').forEach(el=>el.addEventListener('click',()=>this.performBattleCommand('spell',{id:el.dataset.battleSpell})));
    this.root.querySelectorAll('[data-battle-item]').forEach(el=>el.addEventListener('click',()=>this.performBattleCommand('item',{stackId:el.dataset.battleItem})));
    this.root.querySelectorAll('[data-action="finish-battle"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=finishBattle(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="defeat-return"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=defeatReturn(this.state);if(r.ok){this.modal={type:'lost',data:r.lost};this.tab='home';}})));
    this.root.querySelectorAll('[data-action="town-rest"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=restAtTown(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="buy"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=buyConsumable(this.state,el.dataset.id);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="upgrade-pack"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=upgradeBackpack(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="to-storage"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=transferStack(this.state,el.dataset.stack,'storage',el.dataset.count||'all');this.toast(r.msg);})));this.root.querySelectorAll('[data-action="to-bag"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=transferStack(this.state,el.dataset.stack,'bag',el.dataset.count||'all');this.toast(r.msg);})));this.root.querySelectorAll('[data-action="warehouse-mode"]').forEach(el=>el.addEventListener('click',()=>{this.warehouseMode=el.dataset.mode;this.render();}));this.root.querySelectorAll('[data-action="toggle-warehouse-item"]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.id;this.warehouseOpen.has(id)?this.warehouseOpen.delete(id):this.warehouseOpen.add(id);this.render();}));this.root.querySelectorAll('[data-action="toggle-fresh-quality"]').forEach(el=>el.addEventListener('click',()=>{const key=el.dataset.key;this.freshQualityOpen.has(key)?this.freshQualityOpen.delete(key):this.freshQualityOpen.add(key);this.render();}));this.root.querySelectorAll('[data-action="upgrade-warehouse"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=upgradeWarehouse(this.state);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="upgrade-fresh-warehouse"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=upgradeFreshWarehouse(this.state);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="sell-stack"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const s=stackList(this.state).find(x=>x.stackId===el.dataset.stack),n=el.dataset.count==='all'?(s?.count||1):Number(el.dataset.count||1),r=sellStack(this.state,el.dataset.stack,n);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="sell-all"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=sellAll(this.state);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="sell-valuables"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=sellAllValuables(this.state);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="order-craft"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=orderCraft(this.state,el.dataset.id);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="self-craft"]').forEach(el=>el.addEventListener('click',()=>this.startMini('forge',{recipeId:el.dataset.id})));this.root.querySelectorAll('[data-action="collect-forge"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=collectForgeOrder(this.state,el.dataset.id);this.toast(r.msg);})));this.root.querySelectorAll('[data-action="brew"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=brewPotion(this.state,.4);this.toast(r.msg);}))); 
    this.root.querySelectorAll('[data-action="equip"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{if(equip(this.state,el.dataset.id))this.toast('装備した。');})));this.root.querySelectorAll('[data-action="sell-gear"]').forEach(el=>el.addEventListener('click',()=>this.mutate(()=>{const r=sellEquipment(this.state,el.dataset.id);this.toast(r.msg);}))); this.root.querySelectorAll('[data-action="close-modal"]').forEach(el=>el.addEventListener('click',()=>{this.modal=null;this.render();}));
    this.root.querySelectorAll('[data-action="export"]').forEach(el=>el.addEventListener('click',()=>this.exportSave()));this.root.querySelectorAll('[data-action="install"]').forEach(el=>el.addEventListener('click',async()=>{if(!this.installPrompt)return;await this.installPrompt.prompt();this.installPrompt=null;this.render();}));const imp=this.root.querySelector('#import-file');if(imp)imp.addEventListener('change',e=>this.importSave(e.target.files?.[0]));this.root.querySelectorAll('[data-action="reset"]').forEach(el=>el.addEventListener('click',()=>{if(confirm('セーブデータを完全に消して最初から始めますか？'))window.dispatchEvent(new CustomEvent('gq-reset'));}));
  }
  exportSave(){const blob=new Blob([JSON.stringify(this.state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`grindquest-save-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async importSave(file){if(!file)return;try{const data=JSON.parse(await file.text());window.dispatchEvent(new CustomEvent('gq-import',{detail:data}));this.toast('セーブを読み込んだ。');}catch{this.toast('セーブファイルを読み込めなかった。');}}
}
