import { materials, localAreas, randomEvents, worldEdges, worldNodes, zones } from '../../data/index.js';
import { beginEncounter } from '../battle/battle.js';
import { addExp, characterById, derived, derivedCharacter, partyMembers } from '../characters/characters.js';
import { addStack, ageStacks, isPerishable, moveStackInternal, removeFromStack, stackList } from '../inventory/inventory.js';
import { allDefs, qualityLabel, tagOf } from '../items/catalog.js';
import { PHASE_STEPS, QUALITY_MULT } from '../shared/constants.js';
import { clamp, pick } from '../shared/utils.js';
import { advanceTime, phaseInfo, timeMessages } from '../time/clock.js';

function edgeBetween(a,b){return worldEdges.find(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a));}
export function adjacentNodes(id){return worldEdges.filter(e=>e.a===id||e.b===id).map(e=>({id:e.a===id?e.b:e.a,edge:e,node:worldNodes[e.a===id?e.b:e.a]}));}
export function currentLocalArea(state){return state.run?.area?localAreas[state.run.area.areaId]||null:null;}
export function currentPlace(state){const area=currentLocalArea(state);return area?.nodes?.[state.run.area.nodeId]||worldNodes[state.run?.location||'town'];}
export function localAdjacentNodes(state){const area=currentLocalArea(state);if(!area)return[];const id=state.run.area.nodeId;return area.edges.filter(e=>e.a===id||e.b===id).map(e=>{const next=e.a===id?e.b:e.a;return{id:next,edge:e,node:area.nodes[next]};});}
export function localAreaEntry(state){if(!state.run||state.run.area)return null;const world=worldNodes[state.run.location],area=world?.interior?localAreas[world.interior]:null;return area?{area,world}:null;}
export function localAreaType(state){const a=currentLocalArea(state);return a?{id:a.type,name:a.typeName||a.type}:null;}
export function startExpedition(state){if(state.run)return{ok:false,msg:'すでに探索中。'};if(!partyMembers(state,{living:true}).length)return{ok:false,msg:'戦える仲間がいない。村で休もう。'};state.run={location:'town',harvested:[],visited:['town'],lastEvent:null,moves:0,effects:{encounterMod:0,moves:0},startedAtStep:state.calendar.totalSteps,patrols:0,area:null,resourceUses:{},defeatedSymbols:[]};state.battle=null;return{ok:true,msg:'村の周辺へ出た。村アイコンをもう一度押せば町へ戻れる。'};}
function weightedEvent(zone,phase){const pool=randomEvents.filter(e=>(!e.zones||e.zones.includes(zone))&&(!e.phases||e.phases.includes(phase)));const total=pool.reduce((a,e)=>a+(e.weight||1),0);let r=Math.random()*total;for(const e of pool){r-=e.weight||1;if(r<=0)return e;}return pool.at(-1);}
function gatheringQuality(state,difficulty=1,performance=.5,kind='herb'){const skill=lifeSkillInfo(state,kind).level,dex=derived(state).dexterity;const score=performance*1.8+(skill-difficulty)*.62+(dex-7)*.055+(Math.random()-.5)*.7;if(score>=2.75)return 3;if(score>=1.85)return 2;if(score>=.9)return 1;return 0;}
function applyEvent(state,event){const ef=event.effect||{};let suffix='';if(ef.herb){const q=gatheringQuality(state,currentLocation(state).resourceDifficulty||1,.55,'herb'),n=addStack(state,'fresh_herb',ef.herb,{quality:q,container:'bag'});suffix=n?` 薬草${qualityLabel(q)}+${n}`:' バッグがいっぱいで薬草は置いてきた。';}if(ef.cargo){const[id,n]=ef.cargo,q=materials[id]?.consumable?gatheringQuality(state,1,.5,'herb'):clamp(Math.floor(Math.random()*2),0,3),a=addStack(state,id,n,{quality:q,container:'bag'});suffix+=a?` ${materials[id].name}${qualityLabel(q)}+${a}`:' バッグがいっぱいで持てない。';}if(ef.randomCargo){const id=pick(ef.randomCargo),q=clamp(Math.floor(Math.random()*2),0,3),a=addStack(state,id,1,{quality:q,container:'bag'});suffix+=a?` ${materials[id].name}${qualityLabel(q)}+1`:' バッグがいっぱいで持てない。';}if(ef.encounterMod!=null)state.run.effects={encounterMod:ef.encounterMod,moves:ef.moves||1};if(ef.steps){const t=advanceTime(state,ef.steps);suffix+=` ${ef.steps}step経過。 ${timeMessages(t).join(' ')}`;}const xp=ef.exp??(event.id==='nothing'?0:1);if(xp)suffix+=` ${addExp(state,xp,'探索').msg}`;return event.text+suffix;}
function resolveArrivalEvent(state,chance=.48){if(!state.run||state.run.area)return null;const node=currentLocation(state);if(node.zone==='village')return null;if(Math.random()>chance){state.run.lastEvent='特に目立った出来事はなかった。';return state.run.lastEvent;}const ev=weightedEvent(node.zone,phaseInfo(state).key);state.run.lastEvent=applyEvent(state,ev);return state.run.lastEvent;}
function areaSymbolKey(areaId,nodeId){return`${areaId}:${nodeId}`;}
export function bossStatus(state,areaId,nodeId){const a=localAreas[areaId],n=a?.nodes?.[nodeId];if(!n?.bossEnemy)return null;const key=areaSymbolKey(areaId,nodeId),last=state.worldState?.bossDefeatedAt?.[key],respawn=n.bossRespawn||300,remaining=last==null?0:Math.max(0,respawn-(state.calendar.totalSteps-last));return{key,ready:last==null||remaining<=0,remaining,last,enemyId:n.bossEnemy};}
function localSymbolEncounter(state,node){const area=currentLocalArea(state);if(!area||!node)return false;const key=areaSymbolKey(area.id,node.id);if(node.bossEnemy){const bs=bossStatus(state,area.id,node.id);if(bs?.ready)return beginEncounter(state,node.bossEnemy,'boss_symbol',{symbolKey:key,bossSymbol:true});return false;}if(node.symbolEnemy&&!state.run.defeatedSymbols.includes(key))return beginEncounter(state,node.symbolEnemy,'symbol',{symbolKey:key});return false;}
function maybeWorldEncounter(state,edge=null,mult=1){const node=currentLocation(state),zone=zones[node.zone],phase=phaseInfo(state);if(!zone?.encounter)return false;let chance=zone.encounter*(edge?.risk||1)*mult;if(phase.key==='night')chance+=.08;if(state.run.effects?.moves>0){chance+=state.run.effects.encounterMod||0;state.run.effects.moves--;if(state.run.effects.moves<=0)state.run.effects={encounterMod:0,moves:0};}if(Math.random()>clamp(chance,0,.82))return false;const pool=zone.pools[phase.key]||zone.pools.day;if(!pool?.length)return false;const first=pick(pool);return beginEncounter(state,first,'encounter',{groupPool:pool});}
function maybeLocalEncounter(state,mult=1){const area=currentLocalArea(state);if(!area)return false;const phase=phaseInfo(state),zone=zones[area.zone];let chance=(area.encounter??zone?.encounter??0)*mult;if(phase.key==='night')chance+=.05;if(Math.random()>clamp(chance,0,.8))return false;const pool=zone?.pools?.[phase.key]||zone?.pools?.day;if(!pool?.length)return false;const first=pick(pool);return beginEncounter(state,first,'local_encounter',{groupPool:pool});}
function maybeContextEncounter(state,mult=1){if(state.run?.area&&localSymbolEncounter(state,currentPlace(state)))return true;return state.run?.area?maybeLocalEncounter(state,mult):maybeWorldEncounter(state,null,mult);}
export function travelTo(state,target){if(!state.run||state.battle||state.run.area)return{ok:false,msg:'今は周辺地図を移動できない。'};const from=state.run.location,edge=edgeBetween(from,target);if(!edge)return{ok:false,msg:'そこへ直接は行けない。'};let steps=edge.steps;if(state.run.effects?.nextDiscount){steps=Math.max(1,steps-state.run.effects.nextDiscount);delete state.run.effects.nextDiscount;}const firstVisit=!state.run.visited.includes(target),time=advanceTime(state,steps);state.run.location=target;state.run.moves++;if(firstVisit)state.run.visited.push(target);const notes=timeMessages(time);if(firstVisit&&target!=='town'){const z=worldNodes[target]?.zone,xp={outskirts:2,river:3,forest:4,mountain:5,ruins:6}[z]||2;notes.push(addExp(state,xp,'新しい場所').msg);}if(target==='town'){state.run.lastEvent='ミナト村の入口まで戻ってきた。村アイコンをタップすると探索を終える。';return{ok:true,atTown:true,msg:[state.run.lastEvent,...notes].join(' ')}}if(maybeWorldEncounter(state,edge)){state.run.lastEvent=notes.join(' ')||'移動中に魔物の気配！';return{ok:true,battle:true,msg:state.run.lastEvent};}const ev=resolveArrivalEvent(state);return{ok:true,msg:[notes.join(' '),ev||`${worldNodes[target].name}に着いた。`].filter(Boolean).join(' ')};}
export function enterLocalArea(state){if(!state.run||state.battle||state.run.area)return{ok:false,msg:'今は入れない。'};const entry=localAreaEntry(state);if(!entry)return{ok:false,msg:'ここには入れる場所がない。'};const a=entry.area;state.run.area={areaId:a.id,nodeId:a.entry,visited:[a.entry]};state.run.lastEvent=`${a.name}へ入った。`;return{ok:true,area:a,msg:`${a.typeName}「${a.name}」へ入った。`};}
export function leaveLocalArea(state){if(!state.run?.area||state.battle)return{ok:false,msg:'今は外へ戻れない。'};const a=currentLocalArea(state);if(!a.entryWorld)return{ok:false,msg:'ここから外へは出られない。移動ポイントから前の区画へ戻ろう。'};const entry=a.nodes[a.entry];if(state.run.area.nodeId!==a.entry)return{ok:false,msg:`${entry?.name||'入口'}まで戻ろう。`};state.run.location=a.entryWorld;if(!state.run.visited.includes(a.entryWorld))state.run.visited.push(a.entryWorld);state.run.area=null;state.run.lastEvent=`${worldNodes[state.run.location].name}へ戻った。`;return{ok:true,msg:state.run.lastEvent};}
export function localMove(state,target){if(!state.run?.area||state.battle)return{ok:false,msg:'今は移動できない。'};const area=currentLocalArea(state),from=state.run.area.nodeId;if(target===from)return localPatrol(state);const edge=area.edges.find(e=>(e.a===from&&e.b===target)||(e.a===target&&e.b===from));if(!edge)return{ok:false,msg:'そこへ直接は行けない。'};const steps=edge.steps==null?area.moveSteps||0:edge.steps,t=advanceTime(state,steps);state.run.area.nodeId=target;if(!state.run.area.visited.includes(target))state.run.area.visited.push(target);state.run.moves++;const node=area.nodes[target],notes=timeMessages(t);if(localSymbolEncounter(state,node)){state.run.lastEvent=`${node.name}で魔物が道を塞いだ！`;return{ok:true,battle:true,steps,msg:[state.run.lastEvent,...notes].join(' ')}}if(steps>0&&area.encounterOnMove&&maybeLocalEncounter(state)){state.run.lastEvent=`${area.name}を移動中、魔物と遭遇した！`;return{ok:true,battle:true,steps,msg:[state.run.lastEvent,...notes].join(' ')}}state.run.lastEvent=`${node.name}へ移動した。${steps?` ${steps}step。`:''}`;return{ok:true,steps,msg:[state.run.lastEvent,...notes].join(' ')};}
export function localPatrol(state){if(!state.run?.area||state.battle)return{ok:false,msg:'今は巡回できない。'};const node=currentPlace(state);if(localSymbolEncounter(state,node)){state.run.lastEvent='目の前のシンボルと接触した！';return{ok:true,battle:true,steps:0,msg:state.run.lastEvent};}const t=advanceTime(state,1),notes=timeMessages(t);if(maybeLocalEncounter(state,.92)){state.run.lastEvent='その場を探っていると魔物と遭遇した！';return{ok:true,battle:true,steps:1,msg:[state.run.lastEvent,...notes].join(' ')}}state.run.lastEvent='周辺を1step見て回った。';return{ok:true,steps:1,msg:[state.run.lastEvent,...notes].join(' ')};}
export function areaTransitionStatus(state){const a=currentLocalArea(state),node=currentPlace(state),tr=node?.transition;if(!a||!tr)return null;const dest=localAreas[tr.areaId];return dest?{from:a,node,transition:tr,destination:dest}:null;}
export function useAreaTransition(state){const st=areaTransitionStatus(state);if(!st||state.battle)return{ok:false,msg:'ここから移動できない。'};const dest=st.destination,target=dest.nodes[st.transition.nodeId]?st.transition.nodeId:dest.entry,steps=st.transition.steps??1,t=advanceTime(state,steps);state.run.area={areaId:dest.id,nodeId:target,visited:[target]};const notes=timeMessages(t);if(steps>0&&dest.encounterOnMove&&maybeLocalEncounter(state)){state.run.lastEvent=`${dest.name}へ移動した直後、魔物と遭遇した！`;return{ok:true,battle:true,steps,msg:[state.run.lastEvent,...notes].join(' ')}}state.run.lastEvent=`${dest.name}へ移動した。`;return{ok:true,steps,msg:[`${st.transition.label||'移動'}：${dest.name} / ${steps}step`,...notes].join(' ')}};
function autoStoreNonAdventure(state){ageStacks(state,state.calendar.totalSteps);let moved=0,left=0,freshMoved=0,normalMoved=0;for(const s of [...stackList(state,'bag')]){if(tagOf(s.id)==='adventure')continue;const r=moveStackInternal(state,s.stackId,'storage','all');if(r.ok){moved+=r.count;if(isPerishable(s.id))freshMoved+=r.count;else normalMoved+=r.count;}else left+=s.count;}return{moved,left,freshMoved,normalMoved};}
function returnToTown(state,method){const auto=autoStoreNonAdventure(state),report={items:stackList(state,'bag').map(x=>({...x})),method,auto};state.run=null;state.battle=null;state.log.unshift(method==='rura'?'ルーラのポーションで村へ帰還した。':`歩いて村へ戻った。素材${auto.moved}個を倉庫へ送った。`);return report;}
export function patrol(state){if(!state.run||state.battle||state.run.area)return{ok:false,msg:'今は巡回できない。'};if(currentLocation(state).zone==='village'){const report=returnToTown(state,'walk');return{ok:true,returned:true,report,steps:0,msg:`村へ戻った。冒険用以外を倉庫へ自動収納した（${report.auto.moved}個${report.auto.left?` / 入らず${report.auto.left}個残留`:''}）。`};}const t=advanceTime(state,1);state.run.patrols=(state.run.patrols||0)+1;const notes=timeMessages(t);if(maybeWorldEncounter(state,null,.92)){state.run.lastEvent='周辺を巡回していると魔物と遭遇した！';return{ok:true,battle:true,steps:1,msg:[state.run.lastEvent,...notes].join(' ')}}let ev=null;if(Math.random()<.12)ev=resolveArrivalEvent(state,1);state.run.lastEvent=ev||'周辺を1step巡回した。魔物の気配はない。';return{ok:true,battle:false,steps:1,msg:[state.run.lastEvent,...notes].join(' ')};}
export function useRura(state,stackId=null){if(!state.run||state.battle)return{ok:false,msg:'今は使えない。'};const list=stackList(state,'bag','rura_potion'),s=stackId?list.find(x=>x.stackId===stackId):list[0];if(!s)return{ok:false,msg:'ルーラのポーションを持っていない。'};removeFromStack(state,s.stackId,1);const stepCost=[2,1,1,0][s.quality]??2,t=advanceTime(state,stepCost),report=returnToTown(state,'rura');return{ok:true,report,msg:`ルーラのポーション${qualityLabel(s.quality)}で村へ直行した。${stepCost}step経過。冒険用以外は倉庫へ。${timeMessages(t).join(' ')}`};}
export function currentLocation(state){return worldNodes[state.run?.location||'town'];}
export function resourceStatus(state){if(!state.run)return null;const node=currentPlace(state);if(!node?.resource)return null;const area=currentLocalArea(state),key=area?`${area.id}:${node.id}`:node.id,maxUses=area?(node.resourceUses||1):1,usedCount=area?(state.run.resourceUses?.[key]||0):(state.run.harvested.includes(node.id)?1:0);return{kind:node.resource,used:usedCount>=maxUses,usedCount,maxUses,remainingUses:Math.max(0,maxUses-usedCount),key,node,difficulty:node.resourceDifficulty||1,area};}
function lifeSkillKey(kind){return kind==='herb'?'gathering':kind;}
export function lifeSkillInfo(state,kind){const key=lifeSkillKey(kind),s=state.lifeSkills[key]||{level:1,xp:0};return{key,...s,next:8+s.level*6};}
function gainLifeSkill(state,kind,amount=2){const key=lifeSkillKey(kind),s=state.lifeSkills[key];if(!s)return null;s.xp+=amount;const next=()=>8+s.level*6;let up=0;while(s.xp>=next()){s.xp-=next();s.level++;up++;const leader=characterById(state,state.party?.[0]||'hero')||characterById(state,'hero');if(leader){leader.stats.dexterity+=1;if(key==='gathering')leader.stats.knowledge+=1;else if(key==='mining'&&s.level%2===0)leader.stats.vitality+=1;else if(key==='fishing'&&s.level%2===0)leader.stats.agility+=1;else if(key==='woodcut'&&s.level%2===0)leader.stats.strength+=1;}}return{...s,up,key};}
function harvestQuality(state,kind,performance,difficulty){return gatheringQuality(state,difficulty,performance,kind);}
export function resolveGatherEncounter(state,rate=.92){
  if(!state.run||state.battle)return false;
  const encounter=maybeContextEncounter(state,rate);
  if(encounter&&state.run)state.run.lastEvent='作業音に気づいた魔物が近づいてきた！';
  return encounter;
}
export function harvestResult(state,performance=.5,{deferEncounter=false}={}){
  const rs=resourceStatus(state);if(!rs||rs.used)return{ok:false,msg:'ここではもう採れない。'};
  if(rs.area){state.run.resourceUses=state.run.resourceUses||{};state.run.resourceUses[rs.key]=(state.run.resourceUses[rs.key]||0)+1;}
  else if(!state.run.harvested.includes(rs.node.id))state.run.harvested.push(rs.node.id);
  const q=harvestQuality(state,rs.kind,clamp(performance,0,1),rs.difficulty);let got={},msg='';
  if(rs.kind==='herb'){
    const id=rs.node.id==='mushroom_ring'?'mushroom':'fresh_herb',n=performance>.82?3:performance>.42?2:1,a=addStack(state,id,n,{quality:q,container:'bag'});got[id]=a;msg=`${materials[id].name}${qualityLabel(q)}を ${a} 個採った。${a<n?' バッグがいっぱいだ。':''}`;
  }else if(rs.kind==='mining'){
    let id='iron_ore';if(['crystal_ledge','blue_wall','crystal_pocket'].includes(rs.node.id)&&performance>.72)id=Math.random()<.28?'flame_crystal':'magic_crystal';else if(performance>.86&&Math.random()<.5)id=['hidden_cave','shard_floor'].includes(rs.node.id)?'magic_crystal':'iron_ore';const n=performance>.72&&id==='iron_ore'?2:1,a=addStack(state,id,n,{quality:q,container:'bag'});got[id]=a;msg=`${materials[id].name}${qualityLabel(q)}を ${a} 個採掘した。${a<n?' バッグがいっぱいだ。':''}`;
  }else if(rs.kind==='fishing'){
    if(performance<.2)msg='魚に逃げられた。';else{const id=performance>.82&&Math.random()<.5?'silver_fish':'river_fish',a=addStack(state,id,1,{quality:q,container:'bag'});got[id]=a;msg=a?`${materials[id].name}${qualityLabel(q)}を釣り上げた！`:'バッグがいっぱいで魚を持てない。';}
  }else if(rs.kind==='woodcut'){
    const id=performance>.8&&Math.random()<.45?'hardwood':'softwood',n=performance>.62?2:1,a=addStack(state,id,n,{quality:q,container:'bag'});got[id]=a;msg=`${materials[id].name}${qualityLabel(q)}を ${a} 個切り出した。${a<n?' バッグがいっぱいだ。':''}`;
  }else return{ok:false,msg:'何も起きない。'};
  const stepCost={herb:2,mining:5,fishing:4,woodcut:5}[rs.kind]||2,t=advanceTime(state,stepCost),xp=addExp(state,{herb:2,mining:4,fishing:3,woodcut:4}[rs.kind]||2,'採集'),life=gainLifeSkill(state,rs.kind,2),notes=timeMessages(t);const remaining=rs.area?Math.max(0,rs.maxUses-(state.run.resourceUses[rs.key]||0)):0;
  let encounter=false;if(!deferEncounter){encounter=resolveGatherEncounter(state,.92);if(encounter)notes.push('作業音に気づいた魔物が近づいてきた！');}
  return{ok:true,battle:encounter,encounterPending:deferEncounter,msg:`${msg} ${stepCost}step経過。 ${xp.msg}${life?.up?` / ${life.key} Lv.${life.level}！ きようさ+${life.up}`:''}${rs.area?` / この地点あと${remaining}回`:''}${notes.length?` ${notes.join(' ')}`:''}`,got,steps:stepCost,xp,quality:q,life,remainingUses:remaining};
}
function healWithStack(state,stackId,targetId){const s=state.itemStacks.find(x=>x.stackId===stackId&&x.container==='bag');if(!s||!allDefs(s.id)?.consumable)return{ok:false,msg:'その道具は使えない。'};const target=characterById(state,targetId);if(!target||!state.party?.includes(target.id))return{ok:false,msg:'その仲間には使えない。'};if(target.hp<=0)return{ok:false,msg:'戦闘不能の仲間には使えない。'};const def=allDefs(s.id),removed=removeFromStack(state,stackId,1),d=derivedCharacter(state,target),before=target.hp,amount=Math.round((def.heal||0)*QUALITY_MULT[removed.quality]);target.hp=Math.min(d.maxHp,target.hp+amount);return{ok:true,heal:target.hp-before,stack:removed,target};}
export function useFieldItem(state,idOrStack,targetId=null){if(!state.run||state.battle)return{ok:false,msg:'探索中に使う道具ではない。'};let s=state.itemStacks.find(x=>x.stackId===idOrStack&&x.container==='bag');if(!s)s=stackList(state,'bag',idOrStack)[0];if(!s)return{ok:false,msg:'その道具を持っていない。'};if(s.id==='rura_potion')return useRura(state,s.stackId);const target=targetId?characterById(state,targetId):partyMembers(state,{living:true})[0];const r=healWithStack(state,s.stackId,target?.id);if(!r.ok)return r;const t=advanceTime(state,2),def=allDefs(r.stack.id),encounter=maybeContextEncounter(state,.92),notes=timeMessages(t);if(encounter)notes.push('道具を使っている間に魔物が近づいてきた！');return{ok:true,battle:encounter,steps:2,targetId:r.target.id,msg:`${r.target.name}に${def.name}${qualityLabel(r.stack.quality)}を使った。HP +${r.heal} / 2step経過。 ${notes.join(' ')}`};}
export function sleepDuration(state){const r=phaseInfo(state).remaining;return r>=20?r:r+PHASE_STEPS;}
export function restAtTown(state){if(state.run)return{ok:false,msg:'探索中は村で休めない。'};const steps=sleepDuration(state),t=advanceTime(state,steps,{resting:true});for(const c of partyMembers(state)){const d=derivedCharacter(state,c);c.hp=d.maxHp;c.mp=d.maxMp;}state.log.unshift(`${steps}ステップ眠って${t.after.name}になった。`);return{ok:true,steps,msg:`${steps}step休息。パーティ全員のHP/MP全回復。${t.after.icon} ${t.after.name}になった。`};}
export function campStatus(state){if(!state.run)return null;const node=currentPlace(state);return{allowed:!!node.campSafety,safety:node.campSafety||null,node,hasSet:(state.consumables.camp_set||0)>0};}
function recoverCamp(state,ratio){let hp=0,mp=0;for(const c of partyMembers(state)){const d=derivedCharacter(state,c),h=Math.floor((d.maxHp-c.hp)*ratio),m=Math.floor((d.maxMp-c.mp)*ratio);c.hp=Math.min(d.maxHp,c.hp+h);c.mp=Math.min(d.maxMp,c.mp+m);hp+=h;mp+=m;}return{hp,mp};}
export function camp(state){if(!state.run||state.battle)return{ok:false,msg:'今はキャンプできない。'};const cs=campStatus(state);if(!cs.allowed)return{ok:false,msg:'ここは野営に向かない。'};if(!cs.hasSet)return{ok:false,msg:'キャンプセットを持っていない。'};const steps=sleepDuration(state);if(cs.safety==='semi'&&Math.random()<.35){const interrupted=Math.max(10,Math.ceil(steps/2)),t=advanceTime(state,interrupted,{awake:false}),rec=recoverCamp(state,.20),zone=zones[cs.node.zone||currentLocalArea(state)?.zone||currentLocation(state).zone],pool=zone?.pools?.[phaseInfo(state).key]||zone?.pools?.day||['slime'];beginEncounter(state,pick(pool),'camp_raid');state.run.lastEvent=`野営中に襲撃！ ${interrupted}step経過。`;return{ok:true,raided:true,battle:true,steps:interrupted,msg:`うとうとしたところを襲われた！ HP+${rec.hp} / MP+${rec.mp}。${timeMessages(t).join(' ')}`};}const t=advanceTime(state,steps,{resting:true}),rec=recoverCamp(state,.70);state.run.lastEvent=`キャンプで${steps}step休んだ。`;return{ok:true,raided:false,steps,msg:`キャンプ成功。HP+${rec.hp} / MP+${rec.mp}。疲労も解消。${timeMessages(t).join(' ')}`};}
