import { consumables, enemies, items, localAreas, materials, zones } from '../../data/index.js';
import { allDefs, rarityOf } from '../items/catalog.js';
import { isItemDiscovered, isItemObtained, isMonsterDiscovered, isMonsterSeen, itemKnowledge, monsterKnowledge } from '../discovery/discovery.js';

const BOOK_ITEM_IDS=[...Object.keys(items),...Object.keys(consumables),...Object.keys(materials)];
const BOOK_ENEMY_IDS=Object.keys(enemies);
const bookNo=(ids,id)=>String(Math.max(0,ids.indexOf(id))+1).padStart(3,'0');
const itemKind=d=>d?.slot?'装備':d?.tag==='adventure'?'冒険用アイテム':d?.tag==='valuable'?'換金アイテム':'素材アイテム';
const itemEffect=d=>{if(!d)return'―';if(d.slot){const parts=[];if(d.atk)parts.push(`攻撃+${d.atk}`);if(d.def)parts.push(`守備+${d.def}`);if(d.hp)parts.push(`HP+${d.hp}`);if(d.mp)parts.push(`MP+${d.mp}`);return parts.join(' / ')||'装備品';}if(d.heal)return`HPを基本${d.heal}回復。品質が高いほど効果が上がる。`;if(d.id==='rura_potion')return'探索中、現在地から村へ直帰する。';if(d.id==='camp_set')return'セーフティエリア等でキャンプできる。';if(d.shelfLife)return`寿命 ${d.shelfLife}step（品質で延長）`;return d.tag==='valuable'?'主に売却して資金へ換える。':d.tag==='material'?'鍛冶・調合などの材料として使う。':'特別な効果はまだない。';};
const itemFlavor=d=>d?.desc||(d?.tag==='valuable'?'商人が価値を見出す品。持ち帰ればまとまった資金になる。':d?.tag==='material'?'加工や生産に利用できる素材。地域によって採れ方が異なる。':'冒険者が携帯する道具。');
export function itemBookEntry(state,id){const d=items[id]||allDefs(id);if(!d)return null;const sell=d.slot?Math.max(1,Math.round((d.price||50)*.45)):materials[id]?(d.value||0):null;return{id,number:bookNo(BOOK_ITEM_IDS,id),icon:d.icon||'📦',name:d.name||id,rank:rarityOf(d),kind:itemKind(d),effect:itemEffect(d),flavor:itemFlavor(d),sell,shelfLife:d.shelfLife??null,slot:d.slot||null,discovered:isItemDiscovered(state,id),obtained:isItemObtained(state,id),knowledge:itemKnowledge(state,id)};}
export function itemBookEntries(state){return BOOK_ITEM_IDS.map(id=>itemBookEntry(state,id)).filter(Boolean);}
function enemyHabitats(id){const rows=[];const labels={morning:'朝',day:'昼',night:'夜'};for(const [zid,z] of Object.entries(zones)){const phases=[];for(const [ph,pool] of Object.entries(z.pools||{}))if((pool||[]).includes(id))phases.push(labels[ph]||ph);if(phases.length)rows.push({place:z.name||zid,time:phases.join('・')});}for(const area of Object.values(localAreas)){for(const node of Object.values(area.nodes||{})){if(node.symbolEnemy===id||node.bossEnemy===id)rows.push({place:`${area.name}・${node.name}`,time:'常駐'});}}const seen=new Set();return rows.filter(r=>{const k=`${r.place}|${r.time}`;if(seen.has(k))return false;seen.add(k);return true;});}
export function monsterBookEntry(state,id){const e=enemies[id];if(!e)return null;return{id,number:bookNo(BOOK_ENEMY_IDS,id),icon:e.icon,name:e.name,kills:Math.max(0,Number(state?.encyclopedia?.kills?.[id])||0),flavor:e.flavor||'',habitats:enemyHabitats(id),slots:(e.slots||[]).map(([count,p])=>({count,p})),drops:(e.loot||[]).map(x=>({id:x.id,name:allDefs(x.id)?.name||x.id,icon:allDefs(x.id)?.icon||'📦',weight:x.w,min:x.min||1,max:x.max||x.min||1,rank:rarityOf(x.id),discovered:isItemDiscovered(state,x.id)})),stats:{hp:e.hp,atk:e.atk,def:e.def,agi:e.agi,exp:e.exp},discovered:isMonsterDiscovered(state,id),seen:isMonsterSeen(state,id),knowledge:monsterKnowledge(state,id)};}
export function monsterBookEntries(state){return BOOK_ENEMY_IDS.map(id=>monsterBookEntry(state,id)).filter(Boolean);}
