import { backpacks, consumables } from '../../data/index.js';
import { FRESH_STORAGE_BASE_CAPACITY, FRESH_STORAGE_UPGRADES, QUALITY_LIFE, STORAGE_BASE_CAPACITY, STORAGE_UPGRADES } from '../shared/constants.js';
import { clamp, sum } from '../shared/utils.js';
import { allDefs, isStackItem, qualityLabel, tagOf } from '../items/catalog.js';
import { obtainItem } from '../discovery/discovery.js';
import { recordItemGain } from '../expedition/expedition.js';

const tagPriority={adventure:0,material:1,valuable:2};
export function newStackId(state){return`stk_${state.nextStackId++}`;}
export function baseLife(id,quality=0){const def=allDefs(id);return def?.shelfLife?Math.round(def.shelfLife*QUALITY_LIFE[clamp(quality,0,3)]):null;}
export function isPerishable(id){return baseLife(id,0)!=null;}
export function storageContainerFor(id){return isPerishable(id)?'fresh_storage':'storage';}
export function normalizeContainer(id,container){if(container==='bag')return'bag';if(container==='fresh_storage')return isPerishable(id)?'fresh_storage':'storage';if(container==='storage')return storageContainerFor(id);return'bag';}
export function normalizeStack(state,raw){const id=raw.id;if(!isStackItem(id)||!(raw.count>0))return null;const q=clamp(Number(raw.quality)||0,0,3),life=raw.remainingLife==null?baseLife(id,q):Math.max(0,Number(raw.remainingLife));return{stackId:raw.stackId||newStackId(state),id,count:Math.max(1,Math.floor(raw.count)),quality:q,container:normalizeContainer(id,raw.container),remainingLife:life,lastAgedStep:Number.isFinite(raw.lastAgedStep)?raw.lastAgedStep:state.calendar.totalSteps};}
export function consolidatePermanentStacks(state){const keep=[],map=new Map();for(const s of state.itemStacks||[]){if(s.remainingLife!=null){keep.push(s);continue;}const key=`${s.container}:${s.id}:${s.quality}`;const ex=map.get(key);if(ex)ex.count+=s.count;else{map.set(key,s);keep.push(s);}}state.itemStacks=keep;}
export function ageStacks(state,toStep){const expired=[];for(const s of state.itemStacks||[]){if(s.remainingLife==null){s.lastAgedStep=toStep;continue;}const from=Number.isFinite(s.lastAgedStep)?s.lastAgedStep:toStep,delta=Math.max(0,toStep-from),rate=s.container==='fresh_storage'?1/3:1;s.remainingLife=Math.max(0,s.remainingLife-delta*rate);s.lastAgedStep=toStep;if(s.remainingLife<=0)expired.push({...s});}if(expired.length)state.itemStacks=state.itemStacks.filter(x=>x.remainingLife==null||x.remainingLife>0);return expired;}
export function stackDefinition(id){return allDefs(id);}
export function stackQualityLabel(x){return qualityLabel(typeof x==='object'?x.quality:x);}
export function stackRemaining(s){return s.remainingLife==null?null:Math.max(0,Math.ceil(s.remainingLife));}
export function stackList(state,container=null,id=null){
  ageStacks(state,state.calendar.totalSteps);
  return(state.itemStacks||[]).filter(x=>(!container||x.container===container)&&(!id||x.id===id)).sort((a,b)=>{
    const ta=tagPriority[tagOf(a.id)]??9,tb=tagPriority[tagOf(b.id)]??9;if(ta!==tb)return ta-tb;
    const na=allDefs(a.id)?.name||a.id,nb=allDefs(b.id)?.name||b.id,nn=na.localeCompare(nb,'ja');if(nn)return nn;
    if((container==='bag'||(!container&&a.container==='bag'&&b.container==='bag'))){const la=a.remainingLife??1e12,lb=b.remainingLife??1e12;if(la!==lb)return la-lb;if(a.quality!==b.quality)return b.quality-a.quality;}
    else{if(a.quality!==b.quality)return b.quality-a.quality;const la=a.remainingLife??1e12,lb=b.remainingLife??1e12;if(la!==lb)return la-lb;}
    return String(a.stackId).localeCompare(String(b.stackId));
  });
}
export function stackCount(state,id,container=null){return sum(stackList(state,container,id),x=>x.count);}
export function perishableCount(state,id,container){return sum(stackList(state,container,id).filter(x=>x.remainingLife!=null),x=>x.count);}
export function perishableSummary(state,container){return stackList(state,container).filter(x=>x.remainingLife!=null).map(x=>({id:x.id,count:x.count,remaining:stackRemaining(x),quality:x.quality,stackId:x.stackId}));}
export function materialCount(state,id){return stackCount(state,id);}
export function backpackCapacity(state){return backpacks[state.backpack]?.capacity||40;}
export function warehouseCapacity(state){return STORAGE_UPGRADES[state.warehouseLevel]?.capacity||STORAGE_BASE_CAPACITY;}
export function freshWarehouseCapacity(state){return FRESH_STORAGE_UPGRADES[state.freshWarehouseLevel]?.capacity||FRESH_STORAGE_BASE_CAPACITY;}
export function usedStorageCapacity(state){return sum(stackList(state,'storage'),x=>(allDefs(x.id)?.bulk||1)*x.count);}
export function usedFreshStorageCapacity(state){return sum(stackList(state,'fresh_storage'),x=>(allDefs(x.id)?.bulk||1)*x.count);}
export function usedCapacity(state){let used=(consumables.camp_set?.bulk||0)*(state.consumables.camp_set||0);used+=sum(stackList(state,'bag'),x=>(allDefs(x.id)?.bulk||1)*x.count);return used;}
export function freeCapacity(state){return Math.max(0,backpackCapacity(state)-usedCapacity(state));}
export function freeStorageCapacity(state){return Math.max(0,warehouseCapacity(state)-usedStorageCapacity(state));}
export function freeFreshStorageCapacity(state){return Math.max(0,freshWarehouseCapacity(state)-usedFreshStorageCapacity(state));}
export function containerFree(state,container){return container==='storage'?freeStorageCapacity(state):container==='fresh_storage'?freeFreshStorageCapacity(state):freeCapacity(state);}
export function addStack(state,id,count=1,{quality=0,container='bag',remainingLife=null}={}){if(!isStackItem(id)||count<=0)return 0;container=normalizeContainer(id,container);const def=allDefs(id),bulk=def.bulk||1,space=containerFree(state,container),added=Math.min(count,Math.floor(space/bulk));if(added<=0)return 0;quality=clamp(Math.floor(quality),0,3);const life=remainingLife==null?baseLife(id,quality):remainingLife;if(life==null){const existing=state.itemStacks.find(x=>x.id===id&&x.container===container&&x.quality===quality&&x.remainingLife==null);if(existing)existing.count+=added;else state.itemStacks.push({stackId:newStackId(state),id,count:added,quality,container,remainingLife:null,lastAgedStep:state.calendar.totalSteps});}else{state.itemStacks.push({stackId:newStackId(state),id,count:added,quality,container,remainingLife:Math.max(1,life),lastAgedStep:state.calendar.totalSteps});}recordItemGain(state,id,added,quality);obtainItem(state,id,{source:'inventory',announce:true});return added;}
export function removeFromStack(state,stackId,count=1){const s=state.itemStacks.find(x=>x.stackId===stackId);if(!s)return null;const n=Math.min(Math.max(1,count),s.count),copy={...s,count:n};s.count-=n;if(s.count<=0)state.itemStacks=state.itemStacks.filter(x=>x.stackId!==stackId);return copy;}
export function takeItems(state,id,count,{containers=['storage','fresh_storage','bag'],preferLowQuality=true}={}){let need=count,taken=[];let list=stackList(state).filter(x=>x.id===id&&containers.includes(x.container));list.sort((a,b)=>{const life=(a.remainingLife??1e12)-(b.remainingLife??1e12);if(life)return life;return preferLowQuality?a.quality-b.quality:b.quality-a.quality;});for(const s of list){if(need<=0)break;const r=removeFromStack(state,s.stackId,Math.min(need,s.count));if(r){taken.push(r);need-=r.count;}}return{count:count-need,taken};}
export function moveStackInternal(state,stackId,to,count='all'){ageStacks(state,state.calendar.totalSteps);const s=state.itemStacks.find(x=>x.stackId===stackId);if(!s)return{ok:false,msg:'その品は見つからない。'};const target=to==='bag'?'bag':storageContainerFor(s.id);if(s.container===target)return{ok:false,msg:'すでにそこにある。'};const n=count==='all'?s.count:Math.min(s.count,Math.max(1,Math.floor(count||1))),whole=n===s.count,bulk=(allDefs(s.id)?.bulk||1)*n,free=containerFree(state,target);if(bulk>free)return{ok:false,msg:target==='bag'?'バッグに入らない。':target==='fresh_storage'?'生鮮倉庫に空きがない。':'通常倉庫に空きがない。'};const moved=removeFromStack(state,stackId,n);if(!moved)return{ok:false,msg:'その品は見つからない。'};if(moved.remainingLife==null){const ex=state.itemStacks.find(x=>x.id===moved.id&&x.container===target&&x.quality===moved.quality&&x.remainingLife==null);if(ex)ex.count+=moved.count;else state.itemStacks.push({...moved,stackId:whole?moved.stackId:newStackId(state),container:target,lastAgedStep:state.calendar.totalSteps});}else state.itemStacks.push({...moved,stackId:whole?moved.stackId:newStackId(state),container:target,lastAgedStep:state.calendar.totalSteps});const where=target==='bag'?'バッグ':target==='fresh_storage'?'生鮮倉庫':'通常倉庫';return{ok:true,count:n,msg:`${allDefs(moved.id).name}${qualityLabel(moved.quality)}×${n}を${where}へ移した。`};}
export function transferStack(state,stackId,to,count='all'){if(state.run)return{ok:false,msg:'倉庫整理は村にいる時だけ。'};return moveStackInternal(state,stackId,to,count);}
export function upgradeWarehouse(state){if(state.run)return{ok:false,msg:'村にいる時だけ拡張できる。'};const next=STORAGE_UPGRADES[state.warehouseLevel+1];if(!next)return{ok:false,msg:'これ以上拡張できない。'};if(state.gold<next.price)return{ok:false,msg:'お金が足りない。'};state.gold-=next.price;state.warehouseLevel++;return{ok:true,msg:`通常倉庫を拡張した！ 容量 ${next.capacity}`};}
export function upgradeFreshWarehouse(state){if(state.run)return{ok:false,msg:'村にいる時だけ拡張できる。'};const next=FRESH_STORAGE_UPGRADES[state.freshWarehouseLevel+1];if(!next)return{ok:false,msg:'これ以上拡張できない。'};if(state.gold<next.price)return{ok:false,msg:'お金が足りない。'};state.gold-=next.price;state.freshWarehouseLevel++;return{ok:true,msg:`生鮮倉庫を拡張した！ 容量 ${next.capacity}`};}
export function warehouseGroups(state,kind='normal'){const container=kind==='fresh'?'fresh_storage':'storage',list=stackList(state,container),by=new Map();for(const s of list){let g=by.get(s.id);if(!g){g={id:s.id,def:allDefs(s.id),count:0,qualities:new Map()};by.set(s.id,g);}g.count+=s.count;let q=g.qualities.get(s.quality);if(!q){q={quality:s.quality,count:0,stacks:[]};g.qualities.set(s.quality,q);}q.count+=s.count;q.stacks.push({...s,remaining:stackRemaining(s)});}const warehousePriority={material:0,valuable:1,adventure:2};return[...by.values()].sort((a,b)=>(warehousePriority[tagOf(a.id)]??9)-(warehousePriority[tagOf(b.id)]??9)||(a.def?.name||a.id).localeCompare(b.def?.name||b.id,'ja')).map(g=>({...g,qualities:[...g.qualities.values()].sort((a,b)=>a.quality-b.quality).map(q=>({...q,stacks:q.stacks.sort((a,b)=>(a.remaining??1e12)-(b.remaining??1e12))}))}));}
