import {
  backpacks, battleSkills, battleSpells, consumables, enemies, items, materials,
  randomEvents, recipes, worldEdges, worldNodes, zones
} from '../data/gameData.js';

const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
const pick=a=>a[rand(0,a.length-1)];
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const sum=(xs,fn)=>xs.reduce((a,x)=>a+fn(x),0);
const deep=x=>JSON.parse(JSON.stringify(x));
const PHASE_STEPS=50,DAY_STEPS=PHASE_STEPS*3;

export const EQUIPMENT_SLOTS=[['weapon','武器'],['shield','盾'],['head','頭'],['body','からだ上'],['arms','腕'],['legs','からだ下'],['feet','足'],['accessory','アクセ']];
export const QUALITY_NAMES=['','☆1','☆2','☆3'];
export const QUALITY_MULT=[1,1.22,1.48,1.82];
export const QUALITY_LIFE=[1,1.25,1.6,2.0];
export const STORAGE_BASE_CAPACITY=200;
export const STORAGE_UPGRADES=[
  {capacity:200,price:0,name:'木箱倉庫'},
  {capacity:320,price:900,name:'棚付き倉庫'},
  {capacity:500,price:2600,name:'大型倉庫'},
  {capacity:800,price:6500,name:'商会式倉庫'},
  {capacity:1200,price:14500,name:'大倉庫'}
];
export const FRESH_STORAGE_BASE_CAPACITY=36;
export const FRESH_STORAGE_UPGRADES=[
  {capacity:36,price:0,name:'小さな保存棚'},
  {capacity:60,price:700,name:'瓶詰め保存棚'},
  {capacity:90,price:2100,name:'地下保存棚'},
  {capacity:140,price:5200,name:'大型保存庫'},
  {capacity:220,price:12000,name:'商会式保存庫'}
];
export const WORKMANSHIP_NAMES=['並','良','上','極'];
export const ITEM_TAGS={adventure:'冒険用',material:'素材',valuable:'換金'};
export const EQUIPMENT_AFFIXES={
  sturdy:{id:'sturdy',name:'丈夫な',minWorkmanship:1,stat:'hp',min:2,max:6},
  keen:{id:'keen',name:'鋭い',minWorkmanship:1,stat:'atk',min:1,max:3},
  guarded:{id:'guarded',name:'堅牢な',minWorkmanship:1,stat:'def',min:1,max:3},
  swift:{id:'swift',name:'軽快な',minWorkmanship:2,stat:'agility',min:1,max:3},
  wise:{id:'wise',name:'知恵ある',minWorkmanship:2,stat:'wisdom',min:1,max:3},
  skillful:{id:'skillful',name:'精巧な',minWorkmanship:2,stat:'dexterity',min:1,max:3}
};

const allDefs=id=>materials[id]||consumables[id];
const isStackItem=id=>!!allDefs(id)&&id!=='camp_set';
const qualityLabel=q=>QUALITY_NAMES[clamp(Number(q)||0,0,3)]||'';
const tagOf=id=>allDefs(id)?.tag||'material';
const tagPriority={adventure:0,material:1,valuable:2};

function starterGear(){return[
  {gearId:'gear_1',baseId:'novice_sword',workmanship:0,affixes:[]},
  {gearId:'gear_2',baseId:'travel_clothes',workmanship:0,affixes:[]},
  {gearId:'gear_3',baseId:'travel_pants',workmanship:0,affixes:[]},
  {gearId:'gear_4',baseId:'travel_boots',workmanship:0,affixes:[]}
];}
export function defaultState(){return{
  version:8,
  player:{
    name:'冒険者',level:1,exp:0,
    stats:{vitality:46,strength:8,agility:8,magic:8,wisdom:8,knowledge:6,dexterity:7},
    hp:46,mp:16,
    equipment:{weapon:'gear_1',shield:null,head:null,body:'gear_2',arms:null,legs:'gear_3',feet:'gear_4',accessory:null}
  },
  gold:80,backpack:'cheap',consumables:{camp_set:0},
  gear:starterGear(),nextGearId:5,ownedItems:{},inventory:{},
  itemStacks:[{stackId:'stk_1',id:'potion',count:1,quality:0,container:'bag',remainingLife:1200,lastAgedStep:0}],nextStackId:2,
  warehouseLevel:0,freshWarehouseLevel:0,
  lifeSkills:{gathering:{level:1,xp:0},mining:{level:1,xp:0},fishing:{level:1,xp:0},woodcut:{level:1,xp:0}},
  calendar:{day:1,stepOfDay:0,totalSteps:0},condition:{awakeSteps:0,fatigueStacks:0},
  timedProcesses:[],run:null,battle:null,idle:null,
  log:['ミナト村での暮らしがはじまった。'],settings:{vibrate:true}
};}

export function expToNext(level){return 28+level*level*14;}
export function fatiguePenalty(state){return clamp((state.condition?.fatigueStacks||0)*.10,0,.7);}
export function gearById(state,gearId){return (state.gear||[]).find(g=>g.gearId===gearId)||null;}
export function gearBase(state,gearId){const g=gearById(state,gearId);return g?items[g.baseId]:null;}
export function gearDisplayName(state,gearOrId){const g=typeof gearOrId==='string'?gearById(state,gearOrId):gearOrId;if(!g)return'なし';const base=items[g.baseId];const aff=(g.affixes||[]).map(a=>EQUIPMENT_AFFIXES[a.id]?.name).filter(Boolean);return `${base?.name||g.baseId}${g.workmanship?` ☆${g.workmanship}`:''}${aff.length?` [${aff.join('・')}]`:''}`;}
function workmanshipMul(q){return [1,1.03,1.07,1.12][clamp(q||0,0,3)];}
export function gearStats(state,g){if(!g)return{};const b=items[g.baseId]||{},m=workmanshipMul(g.workmanship);const out={atk:Math.round((b.atk||0)*m),def:Math.round((b.def||0)*m),hp:Math.round((b.hp||0)*m),mp:Math.round((b.mp||0)*m),agility:0,wisdom:0,dexterity:0};for(const a of g.affixes||[])out[a.stat]=(out[a.stat]||0)+(a.value||0);return out;}
export function derived(state){
  const p=state.player,mul=1-fatiguePenalty(state),base=p.stats||{};
  const primary={};for(const k of ['vitality','strength','agility','magic','wisdom','knowledge','dexterity'])primary[k]=Math.max(1,Math.floor((base[k]||1)*mul));
  const eq=Object.values(p.equipment||{}).map(id=>gearById(state,id)).filter(Boolean),bonus=k=>sum(eq,g=>gearStats(state,g)[k]||0);
  primary.agility+=bonus('agility');primary.wisdom+=bonus('wisdom');primary.dexterity+=bonus('dexterity');
  const maxHp=Math.max(1,primary.vitality+bonus('hp'));
  const maxMp=Math.max(0,primary.magic+primary.wisdom+bonus('mp'));
  const atk=Math.max(1,primary.strength+bonus('atk'));
  const def=Math.max(0,Math.floor(primary.vitality/11)+bonus('def'));
  return{...primary,maxHp,maxMp,atk,def,fatiguePenalty:1-mul};
}

function newStackId(state){return`stk_${state.nextStackId++}`;}
function newGearId(state){return`gear_${state.nextGearId++}`;}
function baseLife(id,quality=0){const def=allDefs(id);return def?.shelfLife?Math.round(def.shelfLife*QUALITY_LIFE[clamp(quality,0,3)]):null;}
export function isPerishable(id){return baseLife(id,0)!=null;}
export function storageContainerFor(id){return isPerishable(id)?'fresh_storage':'storage';}
function normalizeContainer(id,container){if(container==='bag')return'bag';if(container==='fresh_storage')return isPerishable(id)?'fresh_storage':'storage';if(container==='storage')return storageContainerFor(id);return'bag';}
function normalizeStack(state,raw){const id=raw.id;if(!isStackItem(id)||!(raw.count>0))return null;const q=clamp(Number(raw.quality)||0,0,3),life=raw.remainingLife==null?baseLife(id,q):Math.max(0,Number(raw.remainingLife));return{stackId:raw.stackId||newStackId(state),id,count:Math.max(1,Math.floor(raw.count)),quality:q,container:normalizeContainer(id,raw.container),remainingLife:life,lastAgedStep:Number.isFinite(raw.lastAgedStep)?raw.lastAgedStep:state.calendar.totalSteps};}
function consolidatePermanentStacks(state){const keep=[],map=new Map();for(const s of state.itemStacks||[]){if(s.remainingLife!=null){keep.push(s);continue;}const key=`${s.container}:${s.id}:${s.quality}`;const ex=map.get(key);if(ex)ex.count+=s.count;else{map.set(key,s);keep.push(s);}}state.itemStacks=keep;}
function migrateLegacyStacks(s,old){
  if(Array.isArray(old.itemStacks)&&old.itemStacks.length){for(const x of old.itemStacks){const n=normalizeStack(s,x);if(n)s.itemStacks.push(n);}return;}
  const now=s.calendar.totalSteps;
  for(const [id,n0] of Object.entries(old.inventory||{})){const n=Math.max(0,Number(n0)||0);if(n&&isStackItem(id))s.itemStacks.push(normalizeStack(s,{id,count:n,quality:0,container:'storage',lastAgedStep:now}));}
  for(const p of old.perishables||[]){if(isStackItem(p.id)&&p.count>0)s.itemStacks.push(normalizeStack(s,{id:p.id,count:p.count,quality:p.quality||0,container:p.container==='storage'?'storage':'bag',remainingLife:Math.max(1,(p.expiresAt||now)-now),lastAgedStep:now}));}
  for(const id of ['potion','rura_potion']){const n=Math.max(0,Number(old.consumables?.[id])||0);if(n)s.itemStacks.push(normalizeStack(s,{id,count:n,quality:0,container:'bag',lastAgedStep:now}));}
  if(old.run?.cargo)for(const [id,n0] of Object.entries(old.run.cargo)){const n=Math.max(0,Number(n0)||0);if(n&&isStackItem(id))s.itemStacks.push(normalizeStack(s,{id,count:n,quality:0,container:'bag',lastAgedStep:now}));}
}
function legacyStats(old){if(old.player?.stats)return{...old.player.stats};const level=old.player?.level||1;return{vitality:(old.player?.baseMaxHp||46)+(level-1)*5,strength:(old.player?.baseAtk||8)+(level-1)*2,agility:8+Math.floor((level-1)*1.2),magic:8+(level-1),wisdom:8+(level-1),knowledge:6+Math.floor((level-1)/2),dexterity:7+Math.floor((level-1)/2)};}
function migrateGear(s,old){
  if(Array.isArray(old.gear)&&old.gear.length){s.gear=old.gear.map(g=>({gearId:g.gearId||newGearId(s),baseId:g.baseId,workmanship:clamp(g.workmanship||0,0,3),affixes:Array.isArray(g.affixes)?g.affixes:[]})).filter(g=>items[g.baseId]);return;}
  s.gear=[];const counts={...(old.ownedItems||{})};const eq=old.player?.equipment||{};for(const baseId of Object.values(eq)){if(items[baseId])counts[baseId]=Math.max(counts[baseId]||0,1);}if(!Object.keys(counts).length){s.gear=starterGear();s.nextGearId=5;return;}
  for(const [baseId,n] of Object.entries(counts))if(items[baseId])for(let i=0;i<n;i++)s.gear.push({gearId:newGearId(s),baseId,workmanship:0,affixes:[]});
}
function mapLegacyEquipment(s,old){if(Array.isArray(old.gear)&&old.gear.length)return{...s.player.equipment,...(old.player?.equipment||{})};const eq=old.player?.equipment||{},out={weapon:null,shield:null,head:null,body:null,arms:null,legs:null,feet:null,accessory:null};if(eq.armor&&!eq.body)eq.body=eq.armor;for(const slot of Object.keys(out)){const baseId=eq[slot];if(!baseId)continue;const g=s.gear.find(x=>x.baseId===baseId&&!Object.values(out).includes(x.gearId));if(g)out[slot]=g.gearId;}return out;}

export function normalize(state){
  const base=defaultState(),old=state||{},s={...base,...old,version:8};
  s.calendar={...base.calendar,...(old.calendar||{})};if(!Number.isFinite(s.calendar.totalSteps))s.calendar.totalSteps=Math.max(0,(Math.max(1,s.calendar.day||1)-1)*DAY_STEPS+(s.calendar.stepOfDay||0));s.calendar.day=Math.floor(s.calendar.totalSteps/DAY_STEPS)+1;s.calendar.stepOfDay=s.calendar.totalSteps%DAY_STEPS;
  s.player={...base.player,...(old.player||{}),stats:{...base.player.stats,...legacyStats(old)}};
  s.gold=Number.isFinite(old.gold)?old.gold:(old.player?.gold||base.gold);s.backpack=backpacks[old.backpack]?old.backpack:'cheap';s.consumables={camp_set:Math.max(0,Number(old.consumables?.camp_set)||0)};
  s.nextGearId=Math.max(1,Number(old.nextGearId)||1);migrateGear(s,old);s.player.equipment=mapLegacyEquipment(s,old);
  s.condition={...base.condition,...(old.condition||{})};s.settings={...base.settings,...(old.settings||{})};s.timedProcesses=Array.isArray(old.timedProcesses)?old.timedProcesses.map(x=>({...x})) : [];
  s.lifeSkills=deep(base.lifeSkills);for(const [k,v] of Object.entries(old.lifeSkills||{}))if(s.lifeSkills[k])s.lifeSkills[k]={...s.lifeSkills[k],...v};
  s.warehouseLevel=clamp(Number(old.warehouseLevel)||0,0,STORAGE_UPGRADES.length-1);s.freshWarehouseLevel=clamp(Number(old.freshWarehouseLevel)||0,0,FRESH_STORAGE_UPGRADES.length-1);s.nextStackId=Math.max(1,Number(old.nextStackId)||1);s.itemStacks=[];migrateLegacyStacks(s,old);consolidatePermanentStacks(s);
  if(old.run){s.run={location:'town',harvested:[],visited:['town'],lastEvent:null,moves:0,effects:{encounterMod:0,moves:0},startedAtStep:s.calendar.totalSteps,patrols:0,...old.run};delete s.run.cargo;delete s.run.freshHerbs;delete s.run.pendingExp;}else s.run=null;
  if(s.run&&(!s.run.location||!worldNodes[s.run.location])){s.run=null;s.battle=null;}if(old.battle)s.battle={menu:'root',escapeAttempts:0,...old.battle};else s.battle=null;
  s.log=Array.isArray(old.log)?old.log:base.log;s.idle=old.idle||null;s.ownedItems={};s.inventory={};s.perishables=[];
  ageStacks(s,s.calendar.totalSteps);matureProcesses(s);const d=derived(s);s.player.hp=clamp(Number.isFinite(old.player?.hp)?old.player.hp:d.maxHp,0,d.maxHp);s.player.mp=clamp(Number.isFinite(old.player?.mp)?old.player.mp:d.maxMp,0,d.maxMp);return s;
}

export function phaseInfo(state){const step=state.calendar.stepOfDay||0,idx=Math.floor(step/PHASE_STEPS)%3;return{index:idx,key:['morning','day','night'][idx],name:['朝','昼','夜'][idx],icon:['🌅','☀️','🌙'][idx],remaining:PHASE_STEPS-(step%PHASE_STEPS),stepInPhase:step%PHASE_STEPS,phaseSteps:PHASE_STEPS};}
function matureProcesses(state){const now=state.calendar.totalSteps||0,m=[];for(const p of state.timedProcesses||[]){if(!p.ready&&p.readyAt<=now){p.ready=true;m.push(p.id);}}return m;}
function fatigueStacksForAwake(awake){return awake>=DAY_STEPS*2?clamp(Math.floor((awake-DAY_STEPS*2)/PHASE_STEPS)+1,1,7):0;}
function ageStacks(state,toStep){const expired=[];for(const s of state.itemStacks||[]){if(s.remainingLife==null){s.lastAgedStep=toStep;continue;}const from=Number.isFinite(s.lastAgedStep)?s.lastAgedStep:toStep,delta=Math.max(0,toStep-from),rate=s.container==='fresh_storage'?1/3:1;s.remainingLife=Math.max(0,s.remainingLife-delta*rate);s.lastAgedStep=toStep;if(s.remainingLife<=0)expired.push({...s});}if(expired.length)state.itemStacks=state.itemStacks.filter(x=>x.remainingLife==null||x.remainingLife>0);return expired;}
function groupedExpired(xs){const out={};for(const x of xs){const key=`${x.id}:${x.quality}`;out[key]=(out[key]||0)+x.count;}return out;}
export function advanceTime(state,steps,opts={}){steps=Math.max(0,Math.floor(steps||0));const before=phaseInfo(state),beforeDay=state.calendar.day,oldFatigue=state.condition.fatigueStacks||0,newTotal=(state.calendar.totalSteps||0)+steps,expired=ageStacks(state,newTotal);state.calendar.totalSteps=newTotal;state.calendar.day=Math.floor(newTotal/DAY_STEPS)+1;state.calendar.stepOfDay=newTotal%DAY_STEPS;if(opts.resting){state.condition.awakeSteps=0;state.condition.fatigueStacks=0;}else if(opts.awake!==false){state.condition.awakeSteps=(state.condition.awakeSteps||0)+steps;state.condition.fatigueStacks=fatigueStacksForAwake(state.condition.awakeSteps);}const matured=matureProcesses(state),after=phaseInfo(state),d=derived(state);state.player.hp=Math.min(state.player.hp,d.maxHp);state.player.mp=Math.min(state.player.mp,d.maxMp);return{before,after,changed:before.key!==after.key||beforeDay!==state.calendar.day,day:state.calendar.day,steps,expired:groupedExpired(expired),matured,fatigueBefore:oldFatigue,fatigueAfter:state.condition.fatigueStacks||0};}
function timeMessages(t){const out=[];if(t.changed)out.push(`${t.after.icon} ${t.day}日目 ${t.after.name}になった。`);for(const [key,n] of Object.entries(t.expired||{})){const [id,q]=key.split(':');out.push(`${allDefs(id)?.name||id}${qualityLabel(Number(q))}×${n}が傷んだ。`);}if(t.fatigueAfter>t.fatigueBefore)out.push(`徹夜疲労が進行。全能力 -${t.fatigueAfter*10}%。`);if((t.matured||[]).length)out.push(`完成した作業が ${t.matured.length} 件ある。`);return out;}
export function startTimedProcess(state,id,duration,payload={}){const job={id,startedAt:state.calendar.totalSteps,readyAt:state.calendar.totalSteps+Math.max(1,duration),ready:false,payload};state.timedProcesses.push(job);return job;}
export function collectTimedProcess(state,id){const i=state.timedProcesses.findIndex(x=>x.id===id&&x.ready);if(i<0)return null;return state.timedProcesses.splice(i,1)[0];}
function growMainLevel(state){const s=state.player.stats;s.vitality+=5;s.strength+=2;s.agility+=state.player.level%2?1:2;s.magic+=1;s.wisdom+=1;s.knowledge+=state.player.level%2?0:1;s.dexterity+=1;}
export function addExp(state,amount,source='経験'){amount=Math.max(0,Math.floor(amount||0));if(!amount)return{amount:0,levels:0,msg:''};state.player.exp+=amount;let levels=0;while(state.player.exp>=expToNext(state.player.level)){state.player.exp-=expToNext(state.player.level);state.player.level++;growMainLevel(state);levels++;state.log.unshift(`レベル ${state.player.level} になった！ HP/MPはそのまま。`);}const d=derived(state);state.player.hp=Math.min(state.player.hp,d.maxHp);state.player.mp=Math.min(state.player.mp,d.maxMp);return{amount,levels,msg:`${source} EXP +${amount}${levels?` / Lv.${state.player.level}！`:''}`};}

export function stackDefinition(id){return allDefs(id);}export function stackQualityLabel(x){return qualityLabel(typeof x==='object'?x.quality:x);}export function stackRemaining(s){return s.remainingLife==null?null:Math.max(0,Math.ceil(s.remainingLife));}
export function stackList(state,container=null,id=null){
  ageStacks(state,state.calendar.totalSteps);
  return(state.itemStacks||[]).filter(x=>(!container||x.container===container)&&(!id||x.id===id)).sort((a,b)=>{
    const ta=tagPriority[tagOf(a.id)]??9,tb=tagPriority[tagOf(b.id)]??9;if(ta!==tb)return ta-tb;
    const na=allDefs(a.id)?.name||a.id,nb=allDefs(b.id)?.name||b.id,nn=na.localeCompare(nb,'ja');if(nn)return nn;
    if((container==='bag'||(!container&&a.container==='bag'&&b.container==='bag'))){const la=a.remainingLife??1e12,lb=b.remainingLife??1e12;if(la!==lb)return la-lb;if(a.quality!==b.quality)return b.quality-a.quality;}
    else{if(a.quality!==b.quality)return b.quality-a.quality;const la=a.remainingLife??1e12,lb=b.remainingLife??1e12;if(la!==lb)return la-lb;}
    return String(a.stackId).localeCompare(String(b.stackId));
  });
}
export function stackCount(state,id,container=null){return sum(stackList(state,container,id),x=>x.count);}export function perishableCount(state,id,container){return sum(stackList(state,container,id).filter(x=>x.remainingLife!=null),x=>x.count);}export function perishableSummary(state,container){return stackList(state,container).filter(x=>x.remainingLife!=null).map(x=>({id:x.id,count:x.count,remaining:stackRemaining(x),quality:x.quality,stackId:x.stackId}));}export function materialCount(state,id){return stackCount(state,id);}
export function backpackCapacity(state){return backpacks[state.backpack]?.capacity||40;}
export function warehouseCapacity(state){return STORAGE_UPGRADES[state.warehouseLevel]?.capacity||STORAGE_BASE_CAPACITY;}
export function freshWarehouseCapacity(state){return FRESH_STORAGE_UPGRADES[state.freshWarehouseLevel]?.capacity||FRESH_STORAGE_BASE_CAPACITY;}
export function usedStorageCapacity(state){return sum(stackList(state,'storage'),x=>(allDefs(x.id)?.bulk||1)*x.count);}
export function usedFreshStorageCapacity(state){return sum(stackList(state,'fresh_storage'),x=>(allDefs(x.id)?.bulk||1)*x.count);}
export function usedCapacity(state){let used=(consumables.camp_set?.bulk||0)*(state.consumables.camp_set||0);used+=sum(stackList(state,'bag'),x=>(allDefs(x.id)?.bulk||1)*x.count);return used;}
export function freeCapacity(state){return Math.max(0,backpackCapacity(state)-usedCapacity(state));}
export function freeStorageCapacity(state){return Math.max(0,warehouseCapacity(state)-usedStorageCapacity(state));}
export function freeFreshStorageCapacity(state){return Math.max(0,freshWarehouseCapacity(state)-usedFreshStorageCapacity(state));}
function containerFree(state,container){return container==='storage'?freeStorageCapacity(state):container==='fresh_storage'?freeFreshStorageCapacity(state):freeCapacity(state);}
function addStack(state,id,count=1,{quality=0,container='bag',remainingLife=null}={}){if(!isStackItem(id)||count<=0)return 0;container=normalizeContainer(id,container);const def=allDefs(id),bulk=def.bulk||1,space=containerFree(state,container),added=Math.min(count,Math.floor(space/bulk));if(added<=0)return 0;quality=clamp(Math.floor(quality),0,3);const life=remainingLife==null?baseLife(id,quality):remainingLife;if(life==null){const existing=state.itemStacks.find(x=>x.id===id&&x.container===container&&x.quality===quality&&x.remainingLife==null);if(existing)existing.count+=added;else state.itemStacks.push({stackId:newStackId(state),id,count:added,quality,container,remainingLife:null,lastAgedStep:state.calendar.totalSteps});}else{state.itemStacks.push({stackId:newStackId(state),id,count:added,quality,container,remainingLife:Math.max(1,life),lastAgedStep:state.calendar.totalSteps});}return added;}
function removeFromStack(state,stackId,count=1){const s=state.itemStacks.find(x=>x.stackId===stackId);if(!s)return null;const n=Math.min(Math.max(1,count),s.count),copy={...s,count:n};s.count-=n;if(s.count<=0)state.itemStacks=state.itemStacks.filter(x=>x.stackId!==stackId);return copy;}
function takeItems(state,id,count,{containers=['storage','fresh_storage','bag'],preferLowQuality=true}={}){let need=count,taken=[];let list=stackList(state).filter(x=>x.id===id&&containers.includes(x.container));list.sort((a,b)=>{const life=(a.remainingLife??1e12)-(b.remainingLife??1e12);if(life)return life;return preferLowQuality?a.quality-b.quality:b.quality-a.quality;});for(const s of list){if(need<=0)break;const r=removeFromStack(state,s.stackId,Math.min(need,s.count));if(r){taken.push(r);need-=r.count;}}return{count:count-need,taken};}
function moveStackInternal(state,stackId,to,count='all'){ageStacks(state,state.calendar.totalSteps);const s=state.itemStacks.find(x=>x.stackId===stackId);if(!s)return{ok:false,msg:'その品は見つからない。'};const target=to==='bag'?'bag':storageContainerFor(s.id);if(s.container===target)return{ok:false,msg:'すでにそこにある。'};const n=count==='all'?s.count:Math.min(s.count,Math.max(1,Math.floor(count||1))),whole=n===s.count,bulk=(allDefs(s.id)?.bulk||1)*n,free=containerFree(state,target);if(bulk>free)return{ok:false,msg:target==='bag'?'バッグに入らない。':target==='fresh_storage'?'生鮮倉庫に空きがない。':'通常倉庫に空きがない。'};const moved=removeFromStack(state,stackId,n);if(!moved)return{ok:false,msg:'その品は見つからない。'};if(moved.remainingLife==null){const ex=state.itemStacks.find(x=>x.id===moved.id&&x.container===target&&x.quality===moved.quality&&x.remainingLife==null);if(ex)ex.count+=moved.count;else state.itemStacks.push({...moved,stackId:whole?moved.stackId:newStackId(state),container:target,lastAgedStep:state.calendar.totalSteps});}else state.itemStacks.push({...moved,stackId:whole?moved.stackId:newStackId(state),container:target,lastAgedStep:state.calendar.totalSteps});const where=target==='bag'?'バッグ':target==='fresh_storage'?'生鮮倉庫':'通常倉庫';return{ok:true,count:n,msg:`${allDefs(moved.id).name}${qualityLabel(moved.quality)}×${n}を${where}へ移した。`};}
export function transferStack(state,stackId,to,count='all'){if(state.run)return{ok:false,msg:'倉庫整理は村にいる時だけ。'};return moveStackInternal(state,stackId,to,count);}
export function upgradeWarehouse(state){if(state.run)return{ok:false,msg:'村にいる時だけ拡張できる。'};const next=STORAGE_UPGRADES[state.warehouseLevel+1];if(!next)return{ok:false,msg:'これ以上拡張できない。'};if(state.gold<next.price)return{ok:false,msg:'お金が足りない。'};state.gold-=next.price;state.warehouseLevel++;return{ok:true,msg:`通常倉庫を拡張した！ 容量 ${next.capacity}`};}
export function upgradeFreshWarehouse(state){if(state.run)return{ok:false,msg:'村にいる時だけ拡張できる。'};const next=FRESH_STORAGE_UPGRADES[state.freshWarehouseLevel+1];if(!next)return{ok:false,msg:'これ以上拡張できない。'};if(state.gold<next.price)return{ok:false,msg:'お金が足りない。'};state.gold-=next.price;state.freshWarehouseLevel++;return{ok:true,msg:`生鮮倉庫を拡張した！ 容量 ${next.capacity}`};}
export function warehouseGroups(state,kind='normal'){const container=kind==='fresh'?'fresh_storage':'storage',list=stackList(state,container),by=new Map();for(const s of list){let g=by.get(s.id);if(!g){g={id:s.id,def:allDefs(s.id),count:0,qualities:new Map()};by.set(s.id,g);}g.count+=s.count;let q=g.qualities.get(s.quality);if(!q){q={quality:s.quality,count:0,stacks:[]};g.qualities.set(s.quality,q);}q.count+=s.count;q.stacks.push({...s,remaining:stackRemaining(s)});}const warehousePriority={material:0,valuable:1,adventure:2};return[...by.values()].sort((a,b)=>(warehousePriority[tagOf(a.id)]??9)-(warehousePriority[tagOf(b.id)]??9)||(a.def?.name||a.id).localeCompare(b.def?.name||b.id,'ja')).map(g=>({...g,qualities:[...g.qualities.values()].sort((a,b)=>a.quality-b.quality).map(q=>({...q,stacks:q.stacks.sort((a,b)=>(a.remaining??1e12)-(b.remaining??1e12))}))}));}

function edgeBetween(a,b){return worldEdges.find(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a));}export function adjacentNodes(id){return worldEdges.filter(e=>e.a===id||e.b===id).map(e=>({id:e.a===id?e.b:e.a,edge:e,node:worldNodes[e.a===id?e.b:e.a]}));}
export function startExpedition(state){if(state.run)return{ok:false,msg:'すでに探索中。'};if(state.player.hp<=0)return{ok:false,msg:'HPが0だ。村で休もう。'};state.run={location:'town',harvested:[],visited:['town'],lastEvent:null,moves:0,effects:{encounterMod:0,moves:0},startedAtStep:state.calendar.totalSteps,patrols:0};state.battle=null;return{ok:true,msg:'村の周辺へ出た。村アイコンをもう一度押せば町へ戻れる。'};}
function weightedEvent(zone,phase){const pool=randomEvents.filter(e=>(!e.zones||e.zones.includes(zone))&&(!e.phases||e.phases.includes(phase)));const total=pool.reduce((a,e)=>a+(e.weight||1),0);let r=Math.random()*total;for(const e of pool){r-=e.weight||1;if(r<=0)return e;}return pool.at(-1);}
function gatheringQuality(state,difficulty=1,performance=.5,kind='herb'){const skill=lifeSkillInfo(state,kind).level,dex=derived(state).dexterity;const score=performance*1.8+(skill-difficulty)*.62+(dex-7)*.055+(Math.random()-.5)*.7;if(score>=2.75)return 3;if(score>=1.85)return 2;if(score>=.9)return 1;return 0;}
function applyEvent(state,event){const ef=event.effect||{};let suffix='';if(ef.herb){const q=gatheringQuality(state,currentLocation(state).resourceDifficulty||1,.55,'herb'),n=addStack(state,'fresh_herb',ef.herb,{quality:q,container:'bag'});suffix=n?` 薬草${qualityLabel(q)}+${n}`:' バッグがいっぱいで薬草は置いてきた。';}if(ef.cargo){const[id,n]=ef.cargo,q=materials[id]?.consumable?gatheringQuality(state,1,.5,'herb'):clamp(Math.floor(Math.random()*2),0,3),a=addStack(state,id,n,{quality:q,container:'bag'});suffix+=a?` ${materials[id].name}${qualityLabel(q)}+${a}`:' バッグがいっぱいで持てない。';}if(ef.randomCargo){const id=pick(ef.randomCargo),q=clamp(Math.floor(Math.random()*2),0,3),a=addStack(state,id,1,{quality:q,container:'bag'});suffix+=a?` ${materials[id].name}${qualityLabel(q)}+1`:' バッグがいっぱいで持てない。';}if(ef.encounterMod!=null)state.run.effects={encounterMod:ef.encounterMod,moves:ef.moves||1};if(ef.steps){const t=advanceTime(state,ef.steps);suffix+=` ${ef.steps}step経過。 ${timeMessages(t).join(' ')}`;}const xp=ef.exp??(event.id==='nothing'?0:1);if(xp)suffix+=` ${addExp(state,xp,'探索').msg}`;return event.text+suffix;}
function resolveArrivalEvent(state,chance=.48){if(!state.run)return null;const node=currentLocation(state);if(node.zone==='village')return null;if(Math.random()>chance){state.run.lastEvent='特に目立った出来事はなかった。';return state.run.lastEvent;}const ev=weightedEvent(node.zone,phaseInfo(state).key);state.run.lastEvent=applyEvent(state,ev);return state.run.lastEvent;}
function beginEncounter(state,enemyId,reason='encounter'){const e=enemies[enemyId];state.battle={enemyId,enemyHp:e.hp,enemyMaxHp:e.hp,enemyAtk:e.atk,enemyDef:e.def,enemyAgi:e.agi||8,expReward:e.exp,over:false,won:false,escaped:false,guarding:false,turn:1,escapeAttempts:0,reason,log:[`${e.name}が あらわれた！`]};}
function maybeEncounter(state,edge=null,mult=1){const node=currentLocation(state),zone=zones[node.zone],phase=phaseInfo(state);if(!zone?.encounter)return false;let chance=zone.encounter*(edge?.risk||1)*mult;if(phase.key==='night')chance+=.08;if(state.run.effects?.moves>0){chance+=state.run.effects.encounterMod||0;state.run.effects.moves--;if(state.run.effects.moves<=0)state.run.effects={encounterMod:0,moves:0};}if(Math.random()>clamp(chance,0,.82))return false;const pool=zone.pools[phase.key]||zone.pools.day;if(!pool?.length)return false;beginEncounter(state,pick(pool));return true;}
export function travelTo(state,target){if(!state.run||state.battle)return{ok:false,msg:'今は移動できない。'};const from=state.run.location,edge=edgeBetween(from,target);if(!edge)return{ok:false,msg:'そこへ直接は行けない。'};let steps=edge.steps;if(state.run.effects?.nextDiscount){steps=Math.max(1,steps-state.run.effects.nextDiscount);delete state.run.effects.nextDiscount;}const firstVisit=!state.run.visited.includes(target),time=advanceTime(state,steps);state.run.location=target;state.run.moves++;if(firstVisit)state.run.visited.push(target);const notes=timeMessages(time);if(firstVisit&&target!=='town'){const z=worldNodes[target]?.zone,xp={outskirts:2,river:3,forest:4,mountain:5,ruins:6}[z]||2;notes.push(addExp(state,xp,'新しい場所').msg);}if(target==='town'){state.run.lastEvent='ミナト村の入口まで戻ってきた。村アイコンをタップすると探索を終える。';return{ok:true,atTown:true,msg:[state.run.lastEvent,...notes].join(' ')}}if(maybeEncounter(state,edge)){state.run.lastEvent=notes.join(' ')||'移動中に魔物の気配！';return{ok:true,battle:true,msg:state.run.lastEvent};}const ev=resolveArrivalEvent(state);return{ok:true,msg:[notes.join(' '),ev||`${worldNodes[target].name}に着いた。`].filter(Boolean).join(' ')};}
function autoStoreNonAdventure(state){ageStacks(state,state.calendar.totalSteps);let moved=0,left=0,freshMoved=0,normalMoved=0;for(const s of [...stackList(state,'bag')]){if(tagOf(s.id)==='adventure')continue;const r=moveStackInternal(state,s.stackId,'storage','all');if(r.ok){moved+=r.count;if(isPerishable(s.id))freshMoved+=r.count;else normalMoved+=r.count;}else left+=s.count;}return{moved,left,freshMoved,normalMoved};}
function returnToTown(state,method){const auto=autoStoreNonAdventure(state),report={items:stackList(state,'bag').map(x=>({...x})),method,auto};state.run=null;state.battle=null;state.log.unshift(method==='rura'?'ルーラのポーションで村へ帰還した。':`歩いて村へ戻った。素材${auto.moved}個を倉庫へ送った。`);return report;}
export function patrol(state){if(!state.run||state.battle)return{ok:false,msg:'今は巡回できない。'};if(currentLocation(state).zone==='village'){const report=returnToTown(state,'walk');return{ok:true,returned:true,report,steps:0,msg:`村へ戻った。冒険用以外を倉庫へ自動収納した（${report.auto.moved}個${report.auto.left?` / 入らず${report.auto.left}個残留`:''}）。`};}const t=advanceTime(state,1);state.run.patrols=(state.run.patrols||0)+1;const notes=timeMessages(t);if(maybeEncounter(state,null,.92)){state.run.lastEvent='周辺を巡回していると魔物と遭遇した！';return{ok:true,battle:true,steps:1,msg:[state.run.lastEvent,...notes].join(' ')}}let ev=null;if(Math.random()<.12)ev=resolveArrivalEvent(state,1);state.run.lastEvent=ev||'周辺を1step巡回した。魔物の気配はない。';return{ok:true,battle:false,steps:1,msg:[state.run.lastEvent,...notes].join(' ')};}

const pushBattle=(b,m)=>{b.log.push(m);if(b.log.length>28)b.log.shift();};function finishBattleTurn(state,b){const t=advanceTime(state,1);b.turn++;for(const m of timeMessages(t))pushBattle(b,m);}export function battleItemStacks(state){return stackList(state,'bag').filter(s=>allDefs(s.id)?.consumable&&['fresh_herb','potion','honey_drop'].includes(s.id));}export function battleSkillList(){return Object.values(battleSkills);}export function battleSpellList(){return Object.values(battleSpells);}
function useHealingStack(state,b,stackId){const s=state.itemStacks.find(x=>x.stackId===stackId&&x.container==='bag');if(!s||!allDefs(s.id)?.consumable)return{valid:false};const def=allDefs(s.id),removed=removeFromStack(state,stackId,1);if(!removed)return{valid:false};const amount=Math.max(1,Math.round((def.heal||0)*QUALITY_MULT[removed.quality])),d=derived(state),before=state.player.hp;state.player.hp=Math.min(d.maxHp,state.player.hp+amount);const heal=state.player.hp-before;pushBattle(b,`${def.name}${qualityLabel(removed.quality)}を使った。HPが ${heal} 回復した。`);return{valid:true,heal};}
function playerAction(state,b,type,payload,st,e){let valid=true,enemyDamage=0,heal=0,action=type;b.guarding=false;if(type==='attack'){enemyDamage=Math.max(1,st.atk+rand(-2,3)-Math.floor(b.enemyDef*.55));b.enemyHp=Math.max(0,b.enemyHp-enemyDamage);pushBattle(b,`${state.player.name}の攻撃！ ${e.name}に ${enemyDamage} ダメージ！`);}else if(type==='skill'){const sk=battleSkills[payload.id||'flame_slash'];if(!sk)valid=false;else if(state.player.mp<sk.mp){pushBattle(b,'MPが たりない！');valid=false;}else{state.player.mp-=sk.mp;const rate=sk.id==='heavy_slash'?1.45:1.7;enemyDamage=Math.max(2,Math.floor(st.atk*rate)+rand(-2,4)-Math.floor(b.enemyDef*.35));b.enemyHp=Math.max(0,b.enemyHp-enemyDamage);pushBattle(b,`${sk.name}！ ${e.name}に ${enemyDamage} ダメージ！`);action='skill';}}else if(type==='spell'){const sp=battleSpells[payload.id||'heal'];if(!sp)valid=false;else if(state.player.mp<sp.mp){pushBattle(b,'MPが たりない！');valid=false;}else{state.player.mp-=sp.mp;const before=state.player.hp;state.player.hp=Math.min(st.maxHp,state.player.hp+18+state.player.level*4+Math.floor(st.wisdom*.35)+rand(0,5));heal=state.player.hp-before;pushBattle(b,`${sp.name}！ HPが ${heal} 回復した。`);action='spell';}}else if(type==='defend'){b.guarding=true;pushBattle(b,'身を守っている。');}else if(type==='item'){const r=useHealingStack(state,b,payload.stackId);valid=r.valid;heal=r.heal||0;action='item';if(!valid)pushBattle(b,'その道具は使えない。');}else valid=false;return{valid,enemyDamage,heal,action};}
function enemyTurn(state){const b=state.battle,e=enemies[b.enemyId],st=derived(state);let dmg=Math.max(1,b.enemyAtk+rand(-2,3)-Math.floor(st.def*.45));if(b.guarding)dmg=Math.max(1,Math.floor(dmg*.45));state.player.hp=Math.max(0,state.player.hp-dmg);pushBattle(b,`${e.name}の攻撃！ ${state.player.name}は ${dmg} ダメージ。`);if(state.player.hp<=0){b.over=true;b.won=false;pushBattle(b,'ちからつきた……。冒険用品以外のバッグ内容を失う。');}return dmg;}
function rollSlots(e){let r=Math.random(),acc=0;for(const[n,p]of e.slots||[[1,1]]){acc+=p;if(r<=acc)return n;}return(e.slots||[[1,1]]).at(-1)[0];}
function rollLoot(e){const total=(e.loot||[]).reduce((a,x)=>a+x.w,0);let r=Math.random()*total;for(const x of e.loot||[]){r-=x.w;if(r<=0)return{id:x.id,count:rand(x.min||1,x.max||x.min||1)};}return null;}
function dropQuality(e,id){const def=allDefs(id),base=e.exp>=70?.65:e.exp>=35?.36:.16;let q=Math.random()<base?1:0;if(Math.random()<.07)q++;if(Math.random()<.018)q++;if(def?.tag==='valuable')q=Math.min(q,2);return clamp(q,0,3);}
function victory(state){const b=state.battle,e=enemies[b.enemyId];b.over=true;b.won=true;const xp=addExp(state,b.expReward,'戦闘'),drops=[],lost=[];for(let i=0;i<rollSlots(e);i++){const d=rollLoot(e);if(!d)continue;const q=dropQuality(e,d.id),a=addStack(state,d.id,d.count,{quality:q,container:'bag'});if(a)drops.push(`${allDefs(d.id).name}${qualityLabel(q)}×${a}`);if(a<d.count)lost.push(`${allDefs(d.id).name}×${d.count-a}`);}pushBattle(b,`${e.name}を たおした！ ${xp.msg}`);if(drops.length)pushBattle(b,`戦利品: ${drops.join(' / ')}`);if(lost.length)pushBattle(b,`バッグに入らず置いてきた: ${lost.join(' / ')}`);return{xp,drops,lost};}
export function command(state,type,payload={}){const b=state.battle;if(!b||b.over)return{ok:false};const e=enemies[b.enemyId],st=derived(state);if(type==='escape'){b.escapeAttempts=(b.escapeAttempts||0)+1;const chance=Math.min(1,b.escapeAttempts/3),success=Math.random()<chance;pushBattle(b,`逃げ道を探した！ 成功率 ${Math.round(chance*100)}%。`);let playerDamage=0;if(success){b.over=true;b.escaped=true;pushBattle(b,'うまく逃げ切った！');}else{pushBattle(b,'しかし回り込まれた！');playerDamage=enemyTurn(state);}finishBattleTurn(state,b);return{ok:true,action:'escape',escaped:success,playerDamage,escapeChance:chance,order:'escape'};}
  const pInit=st.agility+rand(-3,3),eInit=(e.agi||8)+rand(-3,3),enemyFirst=eInit>pInit;let playerDamage=0,enemyDamage=0,heal=0,action=type,victoryInfo=null,acted=false;
  if(enemyFirst){pushBattle(b,`${e.name}が先に動いた！`);playerDamage=enemyTurn(state);if(!b.over){const r=playerAction(state,b,type,payload,st,e);if(!r.valid)return{ok:false};({enemyDamage,heal,action}=r);acted=true;if(b.enemyHp<=0)victoryInfo=victory(state);}}
  else{const r=playerAction(state,b,type,payload,st,e);if(!r.valid)return{ok:false};({enemyDamage,heal,action}=r);acted=true;if(b.enemyHp<=0)victoryInfo=victory(state);else playerDamage=enemyTurn(state);}
  finishBattleTurn(state,b);return{ok:true,action,enemyDamage,playerDamage,heal,victory:victoryInfo,order:enemyFirst?'enemy-first':'player-first',acted};
}
export function finishBattle(state){if(!state.battle?.over||(!state.battle.won&&!state.battle.escaped))return{ok:false};const msg=state.battle.escaped?'逃走して周囲へ戻った。':'周囲へ戻った。';state.battle=null;return{ok:true,msg};}
function loseExplorationBag(state){const keep=[],lost=[];for(const s of state.itemStacks){if(s.container==='bag'&&tagOf(s.id)!=='adventure')lost.push(s);else keep.push(s);}state.itemStacks=keep;return lost;}
export function defeatReturn(state){if(!state.run)return{ok:false};const lost=loseExplorationBag(state);state.run=null;state.battle=null;state.player.hp=1;state.log.unshift('力尽き、探索品を失って村まで運ばれた。');return{ok:true,lost};}
export function useRura(state,stackId=null){if(!state.run||state.battle)return{ok:false,msg:'今は使えない。'};const list=stackList(state,'bag','rura_potion'),s=stackId?list.find(x=>x.stackId===stackId):list[0];if(!s)return{ok:false,msg:'ルーラのポーションを持っていない。'};removeFromStack(state,s.stackId,1);const stepCost=[2,1,1,0][s.quality]??2,t=advanceTime(state,stepCost),report=returnToTown(state,'rura');return{ok:true,report,msg:`ルーラのポーション${qualityLabel(s.quality)}で村へ直行した。${stepCost}step経過。冒険用以外は倉庫へ。${timeMessages(t).join(' ')}`};}

export function currentLocation(state){return worldNodes[state.run?.location||'town'];}export function resourceStatus(state){if(!state.run)return null;const node=currentLocation(state);if(!node.resource)return null;return{kind:node.resource,used:state.run.harvested.includes(node.id),node,difficulty:node.resourceDifficulty||1};}function lifeSkillKey(kind){return kind==='herb'?'gathering':kind;}export function lifeSkillInfo(state,kind){const key=lifeSkillKey(kind),s=state.lifeSkills[key]||{level:1,xp:0};return{key,...s,next:8+s.level*6};}
function gainLifeSkill(state,kind,amount=2){const key=lifeSkillKey(kind),s=state.lifeSkills[key];if(!s)return null;s.xp+=amount;const next=()=>8+s.level*6;let up=0;while(s.xp>=next()){s.xp-=next();s.level++;up++;state.player.stats.dexterity+=1;if(key==='gathering')state.player.stats.knowledge+=1;else if(key==='mining'&&s.level%2===0)state.player.stats.vitality+=1;else if(key==='fishing'&&s.level%2===0)state.player.stats.agility+=1;else if(key==='woodcut'&&s.level%2===0)state.player.stats.strength+=1;}return{...s,up,key};}
function harvestQuality(state,kind,performance,difficulty){return gatheringQuality(state,difficulty,performance,kind);}export function harvestResult(state,performance=.5){const rs=resourceStatus(state);if(!rs||rs.used)return{ok:false,msg:'ここではもう採れない。'};state.run.harvested.push(rs.node.id);const q=harvestQuality(state,rs.kind,clamp(performance,0,1),rs.difficulty);let got={},msg='';if(rs.kind==='herb'){const id=rs.node.id==='mushroom_ring'?'mushroom':'fresh_herb',n=performance>.82?3:performance>.42?2:1,a=addStack(state,id,n,{quality:q,container:'bag'});got[id]=a;msg=`${materials[id].name}${qualityLabel(q)}を ${a} 個採った。${a<n?' バッグがいっぱいだ。':''}`;}else if(rs.kind==='mining'){let id='iron_ore';if(rs.node.id==='crystal_ledge'&&performance>.72)id=Math.random()<.28?'flame_crystal':'magic_crystal';else if(performance>.86&&Math.random()<.5)id=rs.node.id==='hidden_cave'?'magic_crystal':'iron_ore';const n=performance>.72&&id==='iron_ore'?2:1,a=addStack(state,id,n,{quality:q,container:'bag'});got[id]=a;msg=`${materials[id].name}${qualityLabel(q)}を ${a} 個採掘した。${a<n?' バッグがいっぱいだ。':''}`;}else if(rs.kind==='fishing'){if(performance<.2)msg='魚に逃げられた。今日はこの場所ではもう釣れそうにない。';else{const id=performance>.82&&Math.random()<.5?'silver_fish':'river_fish',a=addStack(state,id,1,{quality:q,container:'bag'});got[id]=a;msg=a?`${materials[id].name}${qualityLabel(q)}を釣り上げた！`:'バッグがいっぱいで魚を持てない。';}}else if(rs.kind==='woodcut'){const id=performance>.8&&Math.random()<.45?'hardwood':'softwood',n=performance>.62?2:1,a=addStack(state,id,n,{quality:q,container:'bag'});got[id]=a;msg=`${materials[id].name}${qualityLabel(q)}を ${a} 個切り出した。${a<n?' バッグがいっぱいだ。':''}`;}else return{ok:false,msg:'何も起きない。'};const stepCost={herb:2,mining:5,fishing:4,woodcut:5}[rs.kind]||2,t=advanceTime(state,stepCost),xp=addExp(state,{herb:2,mining:4,fishing:3,woodcut:4}[rs.kind]||2,'採集'),life=gainLifeSkill(state,rs.kind,2),notes=timeMessages(t);return{ok:true,msg:`${msg} ${stepCost}step経過。 ${xp.msg}${life?.up?` / ${life.key} Lv.${life.level}！ きようさ+${life.up}`:''}${notes.length?` ${notes.join(' ')}`:''}`,got,steps:stepCost,xp,quality:q,life};}

function healWithStack(state,stackId){const s=state.itemStacks.find(x=>x.stackId===stackId&&x.container==='bag');if(!s||!allDefs(s.id)?.consumable)return{ok:false,msg:'その道具は使えない。'};const def=allDefs(s.id),removed=removeFromStack(state,stackId,1),d=derived(state),before=state.player.hp,amount=Math.round((def.heal||0)*QUALITY_MULT[removed.quality]);state.player.hp=Math.min(d.maxHp,state.player.hp+amount);return{ok:true,heal:state.player.hp-before,stack:removed};}
export function useFieldItem(state,idOrStack){if(!state.run||state.battle)return{ok:false,msg:'探索中に使う道具ではない。'};let s=state.itemStacks.find(x=>x.stackId===idOrStack&&x.container==='bag');if(!s)s=stackList(state,'bag',idOrStack)[0];if(!s)return{ok:false,msg:'その道具を持っていない。'};if(s.id==='rura_potion')return useRura(state,s.stackId);const r=healWithStack(state,s.stackId);if(!r.ok)return r;const t=advanceTime(state,2),def=allDefs(r.stack.id);return{ok:true,steps:2,msg:`${def.name}${qualityLabel(r.stack.quality)}を使った。HP +${r.heal} / 2step経過。 ${timeMessages(t).join(' ')}`};}
export function sleepDuration(state){const r=phaseInfo(state).remaining;return r>=20?r:r+PHASE_STEPS;}export function restAtTown(state){if(state.run)return{ok:false,msg:'探索中は村で休めない。'};const steps=sleepDuration(state),t=advanceTime(state,steps,{resting:true}),d=derived(state);state.player.hp=d.maxHp;state.player.mp=d.maxMp;state.log.unshift(`${steps}ステップ眠って${t.after.name}になった。`);return{ok:true,steps,msg:`${steps}step休息。HP/MP全回復。${t.after.icon} ${t.after.name}になった。`};}
export function campStatus(state){if(!state.run)return null;const node=currentLocation(state);return{allowed:!!node.campSafety,safety:node.campSafety||null,node,hasSet:(state.consumables.camp_set||0)>0};}function recoverCamp(state,ratio){const d=derived(state),hp=Math.floor((d.maxHp-state.player.hp)*ratio),mp=Math.floor((d.maxMp-state.player.mp)*ratio);state.player.hp=Math.min(d.maxHp,state.player.hp+hp);state.player.mp=Math.min(d.maxMp,state.player.mp+mp);return{hp,mp};}
export function camp(state){if(!state.run||state.battle)return{ok:false,msg:'今はキャンプできない。'};const cs=campStatus(state);if(!cs.allowed)return{ok:false,msg:'ここは野営に向かない。'};if(!cs.hasSet)return{ok:false,msg:'キャンプセットを持っていない。'};const steps=sleepDuration(state);if(cs.safety==='semi'&&Math.random()<.35){const interrupted=Math.max(10,Math.ceil(steps/2)),t=advanceTime(state,interrupted,{awake:false}),rec=recoverCamp(state,.20),zone=zones[cs.node.zone],pool=zone?.pools?.[phaseInfo(state).key]||zone?.pools?.day||['slime'];beginEncounter(state,pick(pool),'camp_raid');state.run.lastEvent=`野営中に襲撃！ ${interrupted}step経過。`;return{ok:true,raided:true,battle:true,steps:interrupted,msg:`うとうとしたところを襲われた！ HP+${rec.hp} / MP+${rec.mp}。${timeMessages(t).join(' ')}`};}const t=advanceTime(state,steps,{resting:true}),rec=recoverCamp(state,.70);state.run.lastEvent=`キャンプで${steps}step休んだ。`;return{ok:true,raided:false,steps,msg:`キャンプ成功。HP+${rec.hp} / MP+${rec.mp}。疲労も解消。${timeMessages(t).join(' ')}`};}

export function buyConsumable(state,id){const x=consumables[id];if(!x)return{ok:false,msg:'商品がない。'};if(id==='camp_set'){if((state.consumables.camp_set||0)>=1)return{ok:false,msg:'キャンプセットはもう持っている。'};if(state.gold<x.price)return{ok:false,msg:'お金が足りない。'};if(freeCapacity(state)<x.bulk)return{ok:false,msg:'バッグに入らない。'};state.gold-=x.price;state.consumables.camp_set=1;return{ok:true,msg:'キャンプセットを買った。'};}if(state.gold<x.price)return{ok:false,msg:'お金が足りない。'};const a=addStack(state,id,1,{quality:0,container:'bag'});if(!a)return{ok:false,msg:'バッグに入らない。'};state.gold-=x.price;return{ok:true,msg:`${x.name}を買った。品質0。`};}
export function upgradeBackpack(state){const order=['cheap','canvas','explorer'],idx=order.indexOf(state.backpack),next=backpacks[order[idx+1]];if(!next)return{ok:false,msg:'これ以上大きなバッグはない。'};if(state.gold<next.price)return{ok:false,msg:'お金が足りない。'};state.gold-=next.price;state.backpack=next.id;return{ok:true,msg:`${next.name}に買い替えた！`};}
function sellValue(stack,n=1){const def=materials[stack.id];return Math.round((def?.value||0)*[1,1.25,1.6,2.15][stack.quality]*n);}export function sellStack(state,stackId,count=1){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};const s=state.itemStacks.find(x=>x.stackId===stackId);if(!s||!materials[s.id])return{ok:false,msg:'売れる品がない。'};const n=Math.min(s.count,Math.max(1,count)),gain=sellValue(s,n),removed=removeFromStack(state,stackId,n);state.gold+=gain;return{ok:true,msg:`${materials[s.id].name}${qualityLabel(s.quality)}×${removed.count}を ${gain}G で売った。`,gain};}
export function sellMaterial(state,id,count=1){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};const list=stackList(state).filter(x=>x.id===id&&materials[id]);if(!list.length)return{ok:false,msg:'売れる品がない。'};let need=count==='all'?sum(list,x=>x.count):Math.max(1,count),gain=0,n=0;for(const s of [...list]){if(need<=0)break;const take=Math.min(need,s.count);gain+=sellValue(s,take);removeFromStack(state,s.stackId,take);n+=take;need-=take;}state.gold+=gain;return{ok:true,msg:`${materials[id].name}×${n}を ${gain}G で売った。`,gain};}
export function sellAll(state){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};let gain=0,count=0;for(const s of [...stackList(state)])if(materials[s.id]){gain+=sellValue(s,s.count);count+=s.count;removeFromStack(state,s.stackId,s.count);}state.gold+=gain;return{ok:true,msg:`品物${count}個をまとめて ${gain}G で売った。`,gain};}
export function sellAllValuables(state){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};let gain=0,count=0;for(const s of [...stackList(state).filter(x=>x.container==='storage'||x.container==='fresh_storage')])if(tagOf(s.id)==='valuable'){gain+=sellValue(s,s.count);count+=s.count;removeFromStack(state,s.stackId,s.count);}state.gold+=gain;return{ok:true,msg:count?`換金アイテム${count}個を ${gain}G で売った。`:'換金アイテムはない。',gain,count};}

function consumeMaterial(state,id,count){return takeItems(state,id,count,{containers:['storage','fresh_storage','bag'],preferLowQuality:true}).count;}export function canCraft(state,r){return Object.entries(r.cost).every(([id,n])=>materialCount(state,id)>=n);}function consumeRecipe(state,r){if(!r||!canCraft(state,r))return false;for(const[id,n]of Object.entries(r.cost))consumeMaterial(state,id,n);return true;}
function rollAffixes(workmanship){const eligible=Object.values(EQUIPMENT_AFFIXES).filter(a=>workmanship>=a.minWorkmanship),count=workmanship>=3?(Math.random()<.55?2:1):workmanship>=2?(Math.random()<.45?1:0):workmanship>=1?(Math.random()<.15?1:0):0,out=[];for(let i=0;i<count&&eligible.length;i++){const idx=rand(0,eligible.length-1),a=eligible.splice(idx,1)[0];out.push({id:a.id,stat:a.stat,value:rand(a.min,a.max)});}return out;}
function createGear(state,baseId,workmanship=0){const g={gearId:newGearId(state),baseId,workmanship:clamp(Math.floor(workmanship),0,3),affixes:[]};g.affixes=rollAffixes(g.workmanship);state.gear.push(g);return g;}
export function orderCraft(state,recipeId){if(state.run)return{ok:false,msg:'鍛冶は村で。'};const r=recipes.find(x=>x.id===recipeId);if(!r||!consumeRecipe(state,r))return{ok:false,msg:'素材が足りない。'};const id=`forge_${state.calendar.totalSteps}_${Math.random().toString(36).slice(2,8)}`,job=startTimedProcess(state,id,60,{type:'forge',item:r.item,recipeId:r.id,workmanship:1});return{ok:true,job,msg:`${items[r.item].name}を鍛冶屋に依頼した。60step後に完成。`};}
export function selfCraft(state,recipeId,performance=.5){if(state.run)return{ok:false,msg:'鍛冶は村で。'};const r=recipes.find(x=>x.id===recipeId);if(!r||!consumeRecipe(state,r))return{ok:false,msg:'素材が足りない。'};const steps=12,t=advanceTime(state,steps),q=performance>.9?3:performance>.7?2:performance>.42?1:0,g=createGear(state,r.item,q);return{ok:true,steps,quality:q,gear:g,msg:`${gearDisplayName(state,g)}が完成！ 出来栄え${WORKMANSHIP_NAMES[q]}。${steps}step経過。 ${timeMessages(t).join(' ')}`};}
export function forgeOrders(state){return(state.timedProcesses||[]).filter(x=>x.payload?.type==='forge');}export function collectForgeOrder(state,id){const job=collectTimedProcess(state,id);if(!job||job.payload?.type!=='forge')return{ok:false,msg:'まだ受け取れない。'};const g=createGear(state,job.payload.item,job.payload.workmanship||1);return{ok:true,gear:g,msg:`${gearDisplayName(state,g)}を受け取った。`};}
export function canAlchemy(state){return!state.run&&materialCount(state,'fresh_herb')>=1&&materialCount(state,'mushroom')>=1&&state.gold>=20&&freeCapacity(state)>=1;}export function brewPotion(state,quality=.5){if(state.run)return{ok:false,msg:'調合は村で。'};if(!canAlchemy(state))return{ok:false,msg:'薬草×1、森キノコ×1、瓶代20Gが必要。'};consumeMaterial(state,'fresh_herb',1);consumeMaterial(state,'mushroom',1);state.gold-=20;const q=clamp(Math.floor(quality*4),0,3),steps=8,t=advanceTime(state,steps);addStack(state,'potion',1,{quality:q,container:'bag'});return{ok:true,steps,msg:`ポーション${qualityLabel(q)}を調合した。瓶代20G / ${steps}step経過。 ${timeMessages(t).join(' ')}`};}
export function equipmentList(state,slot=null){return(state.gear||[]).filter(g=>!slot||items[g.baseId]?.slot===slot).sort((a,b)=>(items[b.baseId]?.rank||0)-(items[a.baseId]?.rank||0)||b.workmanship-a.workmanship);}
export function equip(state,gearId){let g=gearById(state,gearId);if(!g&&items[gearId])g=equipmentList(state,items[gearId].slot).find(x=>x.baseId===gearId);if(!g)return false;const slot=items[g.baseId]?.slot;if(!slot)return false;state.player.equipment[slot]=g.gearId;const d=derived(state);state.player.hp=Math.min(state.player.hp,d.maxHp);state.player.mp=Math.min(state.player.mp,d.maxMp);return true;}
export function sellEquipment(state,gearId){if(state.run)return{ok:false,msg:'装備売却は村で。'};const g=gearById(state,gearId);if(!g)return{ok:false,msg:'装備がない。'};if(Object.values(state.player.equipment||{}).includes(g.gearId))return{ok:false,msg:'装備中の品は売れない。'};const b=items[g.baseId],affixBonus=(g.affixes||[]).length*.08,gain=Math.max(1,Math.round((b.price||50)*(.45+g.workmanship*.08+affixBonus)));state.gear=state.gear.filter(x=>x.gearId!==g.gearId);state.gold+=gain;return{ok:true,gain,msg:`${gearDisplayName(state,g)}を ${gain}G で売った。`};}

export function startIdle(state,area='outskirts'){state.idle={area,startedAt:Date.now()};return{ok:true};}export function idleStatus(state,now=Date.now()){if(!state.idle)return null;const elapsed=Math.min(now-state.idle.startedAt,8*60*60*1000);return{elapsed,cycles:Math.floor(elapsed/(10*60*1000))};}export function claimIdle(state,now=Date.now()){const s=idleStatus(state,now);if(!s||s.cycles<1)return{ok:false};state.idle=null;return{ok:true,result:{cycles:s.cycles}};}

export {backpacks,battleSkills,battleSpells,consumables,enemies,items,materials,recipes,worldEdges,worldNodes,zones};
