import { backpacks, consumables, materials } from '../../data/index.js';
import { addStack, freeCapacity, removeFromStack, stackList } from '../inventory/inventory.js';
import { qualityLabel, tagOf } from '../items/catalog.js';
import { sum } from '../shared/utils.js';
import { obtainItem } from '../discovery/discovery.js';

export function buyConsumable(state,id){const x=consumables[id];if(!x)return{ok:false,msg:'商品がない。'};if(id==='camp_set'){if((state.consumables.camp_set||0)>=1)return{ok:false,msg:'キャンプセットはもう持っている。'};if(state.gold<x.price)return{ok:false,msg:'お金が足りない。'};if(freeCapacity(state)<x.bulk)return{ok:false,msg:'バッグに入らない。'};state.gold-=x.price;state.consumables.camp_set=1;obtainItem(state,'camp_set',{source:'shop',announce:true});return{ok:true,msg:'キャンプセットを買った。'};}if(state.gold<x.price)return{ok:false,msg:'お金が足りない。'};const a=addStack(state,id,1,{quality:0,container:'bag'});if(!a)return{ok:false,msg:'バッグに入らない。'};state.gold-=x.price;return{ok:true,msg:`${x.name}を買った。品質0。`};}
export function upgradeBackpack(state){const order=['cheap','canvas','explorer'],idx=order.indexOf(state.backpack),next=backpacks[order[idx+1]];if(!next)return{ok:false,msg:'これ以上大きなバッグはない。'};if(state.gold<next.price)return{ok:false,msg:'お金が足りない。'};state.gold-=next.price;state.backpack=next.id;return{ok:true,msg:`${next.name}に買い替えた！`};}
function sellValue(stack,n=1){const def=materials[stack.id];return Math.round((def?.value||0)*[1,1.25,1.6,2.15][stack.quality]*n);}
export function sellStack(state,stackId,count=1){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};const s=state.itemStacks.find(x=>x.stackId===stackId);if(!s||!materials[s.id])return{ok:false,msg:'売れる品がない。'};const n=Math.min(s.count,Math.max(1,count)),gain=sellValue(s,n),removed=removeFromStack(state,stackId,n);state.gold+=gain;return{ok:true,msg:`${materials[s.id].name}${qualityLabel(s.quality)}×${removed.count}を ${gain}G で売った。`,gain};}
export function sellMaterial(state,id,count=1){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};const list=stackList(state).filter(x=>x.id===id&&materials[id]);if(!list.length)return{ok:false,msg:'売れる品がない。'};let need=count==='all'?sum(list,x=>x.count):Math.max(1,count),gain=0,n=0;for(const s of [...list]){if(need<=0)break;const take=Math.min(need,s.count);gain+=sellValue(s,take);removeFromStack(state,s.stackId,take);n+=take;need-=take;}state.gold+=gain;return{ok:true,msg:`${materials[id].name}×${n}を ${gain}G で売った。`,gain};}
export function sellAll(state){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};let gain=0,count=0;for(const s of [...stackList(state)])if(materials[s.id]){gain+=sellValue(s,s.count);count+=s.count;removeFromStack(state,s.stackId,s.count);}state.gold+=gain;return{ok:true,msg:`品物${count}個をまとめて ${gain}G で売った。`,gain};}
export function sellAllValuables(state){if(state.run)return{ok:false,msg:'売却は村にいる時だけ。'};let gain=0,count=0;for(const s of [...stackList(state).filter(x=>x.container==='storage'||x.container==='fresh_storage')])if(tagOf(s.id)==='valuable'){gain+=sellValue(s,s.count);count+=s.count;removeFromStack(state,s.stackId,s.count);}state.gold+=gain;return{ok:true,msg:count?`換金アイテム${count}個を ${gain}G で売った。`:'換金アイテムはない。',gain,count};}
